const modules={dashboard:['▣','Dashboard','Centro general de operaciones.'],clients:['♙','Clientes','Contactos, empresas e historial.'],products:['▦','Productos','Catálogo, precios y modelos.'],services:['◇','Servicios','Servicios, tarifas y especialidades.'],inventory:['▤','Inventario','Stock, movimientos y almacén.'],quotes:['▧','Cotizaciones','Proformas y presupuestos comerciales.'],reports:['☷','Informes técnicos','Diagnósticos, trabajos y entregas.'],documents:['□','Documentos','Archivos y documentos del negocio.'],ai:['✦','Inteligencia Artificial','Análisis y asistencia inteligente.'],settings:['⚙','Configuración','Empresa, usuarios y preferencias.']};
const navItems=document.querySelectorAll('.nav-item'),title=document.getElementById('pageTitle'),cards=document.getElementById('cards'),sidebar=document.getElementById('sidebar');
const clientKey='marc_clients_v1';let clients=loadClients();
function loadClients(){try{return JSON.parse(localStorage.getItem(clientKey))||[]}catch{return []}}
function saveClients(){localStorage.setItem(clientKey,JSON.stringify(clients))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(section='dashboard'){title.textContent=modules[section][1];if(section==='clients')return renderClients();cards.innerHTML=Object.entries(modules).filter(([k])=>k!=='dashboard'||section==='dashboard').map(([k,m])=>`<article class="module-card" data-go="${k}"><div class="module-icon">${m[0]}</div><h3>${m[1]}</h3><p>${m[2]}</p><span class="tag">${k===section?'Actual':'Próximamente'}</span></article>`).join('');bindCards()}
function bindCards(){document.querySelectorAll('[data-go]').forEach(c=>c.onclick=()=>activate(c.dataset.go))}
function renderClients(){cards.innerHTML=`<div class="module-page clients-page"><div class="page-head"><div><p class="eyebrow">GESTIÓN COMERCIAL</p><h2>Clientes</h2><p>Empresas y personas, listas para cotizaciones e informes.</p></div><button class="primary-btn" id="newClient">＋ Nuevo cliente</button></div><div class="client-toolbar"><input id="clientSearch" class="search-input" type="search" placeholder="Buscar cliente, documento, teléfono o correo…"><span class="record-count" id="clientCount"></span></div><div class="client-table-wrap"><table class="client-table"><thead><tr><th>Cliente</th><th>Documento</th><th>Contacto</th><th>Tipo</th><th>Acciones</th></tr></thead><tbody id="clientRows"></tbody></table><div class="empty-state" id="clientEmpty"><div>♙</div><h3>Aún no hay clientes</h3><p>Crea tu primer cliente para comenzar.</p><button class="secondary-btn" id="firstClient">Crear primer cliente</button></div></div></div><div class="modal-backdrop" id="clientModal" hidden><div class="client-modal"><div class="modal-head"><div><p class="eyebrow">M.A.R.C. / CLIENTES</p><h3 id="modalTitle">Nuevo cliente</h3></div><button class="close-btn" id="closeModal">×</button></div><form id="clientForm" class="client-form"><div class="form-grid"><label>Tipo<select name="type"><option>Empresa</option><option>Persona</option></select></label><label>Nombre / razón social *<input name="name" required maxlength="120" placeholder="Ej. Condominio Los Álamos"></label><label>Documento<input name="document" maxlength="30" placeholder="RUC / DNI / CE"></label><label>Teléfono<input name="phone" maxlength="30" inputmode="tel" placeholder="+51 999 999 999"></label><label>Correo electrónico<input name="email" type="email" maxlength="120"></label><label>Dirección<input name="address" maxlength="180"></label></div><label>Notas<textarea name="notes" maxlength="500" rows="3"></textarea></label><div class="form-actions"><button type="button" class="secondary-btn" id="cancelModal">Cancelar</button><button type="submit" class="primary-btn">Guardar cliente</button></div></form></div></div>`;
const search=document.getElementById('clientSearch'),modal=document.getElementById('clientModal'),form=document.getElementById('clientForm');let editing=null;
function draw(){const q=search.value.trim().toLowerCase(),list=clients.filter(c=>[c.name,c.document,c.phone,c.email,c.type].some(v=>String(v||'').toLowerCase().includes(q)));document.getElementById('clientCount').textContent=`${list.length} ${list.length===1?'cliente':'clientes'}`;document.getElementById('clientEmpty').hidden=list.length>0;document.getElementById('clientRows').innerHTML=list.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(c.address||'Sin dirección')}</small></td><td>${esc(c.document||'—')}</td><td><span>${esc(c.phone||'—')}</span><small>${esc(c.email||'')}</small></td><td><span class="type-pill">${esc(c.type)}</span></td><td><div class="row-actions"><button class="icon-btn" data-edit="${c.id}">✎</button><button class="icon-btn danger" data-del="${c.id}">×</button></div></td></tr>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(clients.find(c=>c.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(b.dataset.del))}
function open(c=null){editing=c?.id||null;document.getElementById('modalTitle').textContent=c?'Editar cliente':'Nuevo cliente';form.reset();if(c)Object.entries(c).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v||''});modal.hidden=false;form.elements.name.focus()}
function close(){modal.hidden=true;editing=null;form.reset()}
function remove(id){const c=clients.find(x=>x.id===id);if(c&&confirm(`¿Eliminar a ${c.name}?`)){clients=clients.filter(x=>x.id!==id);saveClients();draw()}}
document.getElementById('newClient').onclick=()=>open();document.getElementById('firstClient').onclick=()=>open();document.getElementById('closeModal').onclick=close;document.getElementById('cancelModal').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};search.oninput=draw;form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(editing)clients=clients.map(c=>c.id===editing?{...c,...data}:c);else clients.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),...data});saveClients();draw();close()};draw()}
function activate(section){navItems.forEach(n=>n.classList.toggle('active',n.dataset.section===section));render(section);sidebar.classList.remove('open')}
navItems.forEach(n=>n.onclick=()=>activate(n.dataset.section));document.getElementById('menu').onclick=()=>sidebar.classList.toggle('open');render();console.log('M.A.R.C. v0.2 iniciado correctamente.');