/* M.A.R.C. — Catálogos PDF: motor único, página por página */
(()=>{
'use strict';
const BUCKET='catalog-pdfs';
let running=false;
const oldRender=window.render;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
function css(){if(document.querySelector('#marcCatalogCss'))return;const l=document.createElement('link');l.id='marcCatalogCss';l.rel='stylesheet';l.href='./catalogos-ui.css?v=4';document.head.appendChild(l)}
css();
function progress(t){const e=document.querySelector('#catv2Progress');if(e){e.hidden=false;e.textContent=t}}
window.render=function(section='dashboard'){oldRender(section);if(section==='inventory')setTimeout(mount,80)};
function mount(){const main=document.querySelector('.main');if(!main)return;let p=document.querySelector('#catv2Panel');if(p){load();return}p=document.createElement('section');p.id='catv2Panel';p.className='panel';p.innerHTML=`<div class="cat-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h2>Catálogos PDF</h2><p>Lee cada página completa. Usa texto cuando es fiable, visión IA cuando está disponible y OCR local como respaldo.</p></div><div class="cat-engine"><b>Motor seguro</b><span>Texto → IA → OCR local</span></div></div><div class="cat-upload-grid"><label class="cat-upload"><input id="catOwn" type="file" accept="application/pdf,.pdf"><span>📘</span><b>Mi catálogo</b><small>Precio → venta</small><strong>Seleccionar PDF</strong></label><label class="cat-upload"><input id="catSupplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><b>Catálogo de proveedor</b><small>Precio → compra</small><strong>Seleccionar PDF</strong></label></div><div id="catv2Progress" class="cat-progress" hidden></div><div id="catv2List" class="cat-list">Cargando...</div><div id="catv2Items" class="cat-items" hidden></div>`;main.appendChild(p);p.querySelector('#catOwn').onchange=e=>upload(e.target.files?.[0],'PROPIO');p.querySelector('#catSupplier').onchange=e=>upload(e.target.files?.[0],'PROVEEDOR');load()}
async function getUser(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
async function load(){const w=document.querySelector('#catv2List');if(!w)return;try{const u=await getUser();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toLowerCase(),p=Number(c.paginas_procesadas||0),err=esc(c.error_detalle||`Detenido en página ${p+1}`);return `<article class="cat-row"><div class="cat-file">PDF</div><div class="cat-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Mi catálogo'} · ${c.paginas||'?'} páginas</span><small>${s==='procesado'?`✓ ${c.productos_encontrados||0} productos listos`:s==='procesando'?`Página ${p}/${c.paginas||'?'} · ${c.productos_encontrados||0} productos`:`⚠ ${err}`}</small></div>${s==='procesado'?`<button class="btn btn-secondary cat-view" data-id="${c.id}">📦 Revisar</button>`:''}${s==='error'||s==='procesando'?`<button class="btn btn-secondary cat-resume" data-id="${c.id}">▶ ${s==='error'?'Reintentar':'Continuar'}</button>`:''}<button class="cat-delete cat-del" data-id="${c.id}">×</button></article>`}).join('')||'<div class="cat-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF arriba.</span></div>';w.querySelectorAll('.cat-view').forEach(b=>b.onclick=()=>showItems(b.dataset.id));w.querySelectorAll('.cat-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.cat-del').forEach(b=>b.onclick=()=>removeCatalog(b.dataset.id))}catch(e){w.innerHTML=`<div class="cat-empty">${esc(e.message)}</div>`}}
async function upload(file,tipo){if(!file)return;if(file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name)){alert('Selecciona un PDF.');return}if(file.size>95*1024*1024){alert('El PDF supera 95 MB.');return}try{const u=await getUser();progress('Subiendo PDF...');const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await process(file,r.data.id,tipo,0)}catch(e){progress('Error: '+e.message);await load()}}
async function loadPdfJs(){if(window.pdfjsLib)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=ok;s.onerror=()=>no(Error('No se pudo cargar PDF.js.'));document.head.appendChild(s)});window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}
async function loadOcr(){if(window.Tesseract)return;progress('Preparando OCR local...');await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(Error('No se pudo cargar el OCR local.'));document.head.appendChild(s)})}
async function textOf(page){const tc=await page.getTextContent({normalizeWhitespace:true});const a=(tc.items||[]).map(x=>({s:clean(x.str),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0)})).filter(x=>x.s);if(!a.length)return'';a.sort((p,q)=>q.y-p.y||p.x-q.x);const lines=[];for(const z of a){let l=lines.find(v=>Math.abs(v.y-z.y)<=2);if(!l){l={y:z.y,a:[]};lines.push(l)}l.a.push(z)}return lines.sort((p,q)=>q.y-p.y).map(l=>l.a.sort((p,q)=>p.x-q.x).map(z=>z.s).join(' ')).join('\n').replace(/[ \t]+/g,' ').trim()}
function codes(s){return(s.match(/\b[A-Z0-9]+(?:[-_/][A-Z0-9]+)+\b/gi)||[]).filter(x=>/[A-Za-z]/.test(x)&&/\d/.test(x)&&!/^\d+(?:CM|MM|GB|TB|MAH|V|W|HZ)$/i.test(x))}
function prices(s){const out=[],re=/(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))(?![A-Za-z0-9])/g;let m;while((m=re.exec(s)))out.push({v:num(m[1]),i:m.index});return out}
function cat(n){const s=clean(n).toUpperCase();if(/AUDIFONO|AURICULAR/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO|MICRÓFONO/.test(s))return'Micrófonos';if(/PARLANTE|ALTAVOZ/.test(s))return'Parlantes';if(/MEMORIA|USB/.test(s))return'Memorias';return'Accesorios'}
function makeItem(code,name,pr,tipo,pagina,pres='UND',qty=1){return{codigo:clean(code).toUpperCase(),nombre:clean(name),marca:'',modelo:'',categoria:cat(name),descripcion:'',precio_compra:tipo==='PROVEEDOR'?pr:0,precio_venta:tipo==='PROPIO'?pr:0,unidad:'UND',datos_extra:{fuente:'PDF',pagina,tipo,precio_fuente:pr,unidad_precio:pres,cantidad_paquete:qty,presentacion:pres}}}
function parseText(text,tipo,pagina){const ls=text.split('\n').map(clean).filter(Boolean),out=[];for(let i=0;i<ls.length;i++){const cs=codes(ls[i]),ps=prices(ls[i]);if(cs.length&&ps.length){const code=cs[cs.length-1],pr=ps[ps.length-1];let name=clean(ls[i].slice(0,pr.i).replace(code,'').replace(/\b(PRECIO|CAJA|DOCENA|UNIDAD|UND|PZA|PAQUETE)\b/gi,' '));if(name.length<3){for(let j=i-1;j>=Math.max(0,i-2);j--)if(ls[j]&&codes(ls[j]).length===0&&!prices(ls[j]).length){name=ls[j];break}}if(name.length>=3){const pres=(ls[i].match(/\b(CAJA|DOCENA|UNIDAD|UND|PZA|PAQUETE)\b/i)||[])[1]||'UND';const qm=ls[i].match(/\b(\d{1,4})\s*(?:UNIDADES|UND|PCS|PZAS|PZA)\b/i);out.push(makeItem(code,name,pr.v,tipo,pagina,pres,qm?Number(qm[1]):1))}}else if(cs.length&&i+1<ls.length&&prices(ls[i+1]).length){const pr=prices(ls[i+1])[0];let name=clean(ls[i].replace(cs[cs.length-1],''));if(name.length<3&&i>0)name=clean(ls[i-1]);if(name.length>=3)out.push(makeItem(cs[cs.length-1],name,pr.v,tipo,pagina))}else if(ps.length&&i>0&&codes(ls[i-1]).length){const code=codes(ls[i-1]).slice(-1)[0],name=clean(ls[i].replace(/\b(PRECIO|CAJA|DOCENA|UNIDAD|UND|PZA|PAQUETE)\b/gi,''));if(name.length>=3)out.push(makeItem(code,name,ps[0].v,tipo,pagina))}}const seen=new Set();return out.filter(x=>{const k=x.codigo||x.nombre;if(!k||seen.has(k))return false;seen.add(k);return true})}
async function image(page){const v0=page.getViewport({scale:1}),scale=Math.min(1.5,Math.max(1.05,1500/Math.max(v0.width,1))),v=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const d=c.toDataURL('image/jpeg',.72);c.width=1;c.height=1;return d}
function quotaError(e){const s=String(e?.message||e||'').toLowerCase();return /quota|allocation|429|4006|3036|limit exceeded|too many requests|no disponible por cuota/.test(s)}
async function vision(page,tipo,pagina){const img=await image(page);progress(`🧠 IA leyendo página ${pagina} · 1 intento`);const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),45000);try{const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:img,tipo,pagina}),signal:ac.signal}),j=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(j.items))return j.items;throw Error(j.detail||j.error||`HTTP ${r.status}`)}catch(e){throw Error(e.name==='AbortError'?'La IA tardó más de 45 segundos':String(e.message||e))}finally{clearTimeout(tm)}}
async function ocrPage(page,tipo,pagina){await loadOcr();const img=await image(page);progress(`🔎 OCR local leyendo página ${pagina} · puede tardar hasta 1 minuto`);const worker=await window.Tesseract.createWorker('spa');try{const r=await worker.recognize(img);const text=clean(r?.data?.text||'');return parseText(text,tipo,pagina)}finally{await worker.terminate()}}
function normalize(a,tipo,pagina){return(Array.isArray(a)?a:[]).map(x=>{const p=num(x.precio_fuente??x.precio_compra??x.precio_venta);return{codigo:clean(x.codigo),nombre:clean(x.nombre)||'Producto sin nombre',marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria)||cat(x.nombre),descripcion:clean(x.descripcion),precio_compra:tipo==='PROVEEDOR'?p:num(x.precio_compra),precio_venta:tipo==='PROPIO'?p:num(x.precio_venta),unidad:clean(x.unidad)||'UND',datos_extra:{...(x.datos_extra||{}),fuente:'PDF',pagina,tipo,precio_fuente:p}}}).filter(x=>x.codigo||x.nombre)}
async function save(items,id,uid){const rows=[],seen=new Set();for(const x of items){const k=(x.codigo||x.nombre).toLowerCase();if(!k||seen.has(k))continue;seen.add(k);rows.push({user_id:uid,catalogo_id:id,codigo:x.codigo||null,nombre:x.nombre,marca:x.marca,modelo:x.modelo,categoria:x.categoria,descripcion:x.descripcion,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:x.datos_extra})}if(!rows.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(rows);if(r.error)throw r.error;return rows.length}
async function process(file,id,tipo,start=0){if(running)return;running=true;try{await loadPdfJs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,q=await supabaseClient.from('catalogos_pdf').select('paginas_procesadas,productos_encontrados').eq('id',id).single();if(q.error)throw q.error;let last=Number(q.data.paginas_procesadas||start||0),total=Number(q.data.productos_encontrados||0);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,bloques_total:pdf.numPages,estado:'PROCESANDO',error_detalle:null}).eq('id',id);for(let n=last+1;n<=pdf.numPages;n++){try{const page=await pdf.getPage(n);progress(`📄 Leyendo página ${n}/${pdf.numPages} · ${total} productos`);const tx=await textOf(page);let items=tx.length>=25?parseText(tx,tipo,n):[];let method='texto';if(!items.length){try{method='IA';items=await vision(page,tipo,n)}catch(aiErr){if(quotaError(aiErr)){progress(`⚠ IA sin cuota en página ${n}. Continúo con OCR local...`);try{method='OCR';items=await ocrPage(page,tipo,n)}catch(ocrErr){progress(`⚠ OCR no disponible en página ${n}. Se marca como leída y continúo.`);items=[];method='sin IA/OCR'}}else{throw aiErr}}}items=normalize(items,tipo,n);if(items.length){const u=await getUser();total+=await save(items,id,u.id)}last=n;await supabaseClient.from('catalogos_pdf').update({bloque_actual:n,paginas_procesadas:n,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ Página ${n}/${pdf.numPages} · ${items.length} productos · ${method}`);await load()}catch(e){const msg=`Página ${n}: ${String(e.message||e)}`;await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',bloque_actual:n,paginas_procesadas:last,productos_encontrados:total,error_detalle:msg,updated_at:new Date().toISOString()}).eq('id',id);progress(`⛔ Página ${n} detenida. ${msg}`);await load();return}}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ Catálogo terminado · ${total} productos`);await load()}catch(e){progress('Error: '+e.message);await load()}finally{running=false}}
async function resume(id){try{const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,archivo_path,paginas_procesadas').eq('id',id).single();if(r.error)throw r.error;progress('Reanudando '+r.data.nombre+'...');const b=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(b.error)throw b.error;await process(new File([b.data],r.data.nombre,{type:'application/pdf'}),id,r.data.tipo,Number(r.data.paginas_procesadas||0))}catch(e){progress('Error al reanudar: '+e.message);await load()}}
async function removeCatalog(id){if(!confirm('¿Eliminar este catálogo y sus productos extraídos?'))return;try{const u=await getUser(),r=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).eq('user_id',u.id).single();if(r.error)throw r.error;await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',u.id);await supabaseClient.storage.from(BUCKET).remove([r.data.archivo_path]);const d=await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);if(d.error)throw d.error;await load()}catch(e){alert(e.message)}}
async function showItems(id){const b=document.querySelector('#catv2Items');if(!b)return;b.hidden=false;b.innerHTML='Cargando productos...';try{const u=await getUser(),r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,precio_compra,precio_venta,datos_extra').eq('catalogo_id',id).eq('user_id',u.id).order('created_at',{ascending:true});if(r.error)throw r.error;const rows=r.data||[];b.innerHTML=`<div class="panel"><div style="padding:14px;display:flex;justify-content:space-between"><h3>Productos extraídos: ${rows.length}</h3><button class="btn btn-secondary" id="catClose">Cerrar</button></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Código</th><th>Producto</th><th>Marca</th><th>Modelo</th><th>Precio</th><th>Página</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.codigo||'')}</td><td>${esc(x.nombre)}</td><td>${esc(x.marca||'')}</td><td>${esc(x.modelo||'')}</td><td>${num(x.precio_compra||x.precio_venta).toFixed(2)}</td><td>${esc(x.datos_extra?.pagina||'')}</td></tr>`).join('')}</tbody></table></div></div>`;b.querySelector('#catClose').onclick=()=>b.hidden=true}catch(e){b.innerHTML=`<div class="cat-empty">${esc(e.message)}</div>`}}
mount();
})();