/* M.A.R.C. — Catálogos V4
   Pipeline real: PDF.js -> detectar texto -> OCR local por página -> IA solo como respaldo.
   Diseñado para PDFs gráficos de catálogo, sin bloquear el documento completo.
*/
(()=>{
'use strict';
const BUCKET='catalog-pdfs';let busy=false,currentId=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const modelRe=/\b[A-Z0-9]{1,8}[-_/][A-Z0-9]{1,14}\b/gi;
const priceRe=/(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))/g;
function prices(s){const a=[];let m;while((m=priceRe.exec(s)))a.push({value:num(m[1]),index:m.index});return a}
function models(s){return s.match(modelRe)||[]}
function category(s){s=clean(s).toUpperCase();if(/AUDIFONO|AURICULAR|EARPHONE/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO|MICRÓFONO/.test(s))return'Micrófonos';if(/PARLANTE|ALTAVOZ|SPEAKER/.test(s))return'Parlantes';if(/MEMORIA|USB/.test(s))return'Memorias';if(/WATCH|RELOJ/.test(s))return'Smartwatch';if(/POWER BANK/.test(s))return'Power banks';return'Accesorios'}
function build(code,name,price,type,page,text,qty=1,variant=''){return{codigo:clean(code).toUpperCase(),nombre:clean(name)||'Producto sin nombre',marca:/ALDEEPO/i.test(text)?'Aldeepo':'',modelo:clean(code).toUpperCase(),categoria:category(name),descripcion:'',precio_compra:type==='PROVEEDOR'?price:0,precio_venta:type==='PROPIO'?price:0,unidad:'UND',datos_extra:{fuente:'PDF',pagina:page,tipo,precio_fuente:price,cantidad_paquete:qty,presentacion:qty>1?'CAJA':'UND',variante,confianza:code&&price?'alta':'media'}}}
function parseCatalogPage(text,type,page){
 const lines=text.split('\n').map(clean).filter(Boolean),up=lines.map(x=>x.toUpperCase()),out=[];
 let model='',mi=-1;for(let i=0;i<lines.length;i++){const m=models(lines[i]);if(m.length){model=m[m.length-1];mi=i;break}}
 const pl=lines.find(x=>/PRECIO\s*CAJA/i.test(x)&&prices(x).length);const price=pl?prices(pl)[0].value:0;const qm=(pl||'').match(/\b(\d{1,4})\s*(?:UNIDADES|UND|PCS|PZAS?)\b/i);const qty=qm?Number(qm[1]):1;
 let name='';const keys=['AUDIFONO BLUETOOTH','CARGADOR DE AUTO','CARGADOR','CABLE DEL DATOS','CABLE DE DATOS','SOPORTE DEL CELULAR','MOUSE CON CABLE','MOUSE INALAMBRICO','PARLANTE ACUATICO','SMART WATCH','POWER BANK','USB PRO 3.0','USB 3.0','MEMORIA'];
 for(const k of keys){const i=up.findIndex(x=>x.includes(k));if(i>=0){name=lines[i];break}}
 if(!name&&mi>=0){for(let i=Math.max(0,mi-2);i<Math.min(lines.length,mi+7);i++){if(i!==mi&&!/PRECIO|COLOR|UNIDADES|CAJA/i.test(lines[i])&&lines[i].length>4){name=lines[i];break}}}
 if(model&&(price||name))out.push(build(model,name,price,type,page,text,qty));
 // Filas simples de tablas: 4GB S/10, 8GB S/11.30, etc.
 for(const line of lines){const m=line.match(/^(\d{1,4})\s*(GB|TB)\s+(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))$/i);if(m)out.push(build(`${m[1]}${m[2].toUpperCase()}-${page}`,name||'Memoria USB',num(m[3]),type,page,text,1,`${m[1]}${m[2].toUpperCase()}`))}
 const seen=new Set();return out.filter(x=>{const k=(x.codigo||x.nombre).toLowerCase();if(seen.has(k))return false;seen.add(k);return true})
}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const p=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=p;return p}
async function ocrLib(){if(window.Tesseract)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar el OCR local.'));document.head.appendChild(s)})}
async function render(page){const b=page.getViewport({scale:1}),scale=Math.min(2,Math.max(1.3,1800/Math.max(b.width,1))),v=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const data=c.toDataURL('image/jpeg',.82);c.width=1;c.height=1;return data}
async function text(page){const tc=await page.getTextContent({normalizeWhitespace:true});const a=(tc.items||[]).map(x=>({s:clean(x.str),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0)})).filter(x=>x.s);if(!a.length)return'';a.sort((a,b)=>b.y-a.y||a.x-b.x);const ls=[];for(const z of a){let l=ls.find(v=>Math.abs(v.y-z.y)<=2);if(!l){l={y:z.y,a:[]};ls.push(l)}l.a.push(z)}return ls.sort((a,b)=>b.y-a.y).map(l=>l.a.sort((a,b)=>a.x-b.x).map(x=>x.s).join(' ')).join('\n')}
function progress(s,done=false){const e=document.querySelector('#cat4Progress');if(e)e.innerHTML=`<span class="cat4-dot ${done?'done':''}"></span>${esc(s)}`;}
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
async function save(items,id,uid){if(!items.length)return 0;const rows=items.map(x=>({user_id:uid,catalogo_id:id,codigo:x.codigo||null,nombre:x.nombre,marca:x.marca,modelo:x.modelo,categoria:x.categoria,descripcion:x.descripcion,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:x.datos_extra}));const r=await supabaseClient.from('catalogo_items').insert(rows);if(r.error)throw r.error;return rows.length}
async function checkpoint(id,page,count,total,status='PROCESANDO',err=null){const r=await supabaseClient.from('catalogos_pdf').update({paginas:total,paginas_procesadas:page,bloques_total:total,bloque_actual:page,productos_encontrados:count,estado:status,error_detalle:err}).eq('id',id);if(r.error)throw r.error}
async function ai(image,type,page){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,tipo:type,pagina:page})});const j=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(j.items))throw new Error(j.error||'IA no disponible');return j.items}
async function runOCR(pdf,type,start,count){await ocrLib();const worker=await window.Tesseract.createWorker('spa');try{for(let n=start+1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);progress(`OCR local · página ${n}/${pdf.numPages} · ${count} productos`);const image=await render(page);const r=await worker.recognize(image);const raw=String(r?.data?.text||'');let items=parseCatalogPage(raw,type,n);if(!items.length){try{items=await ai(image,type,n)}catch{items=[]}}if(items.length){const u=await user();count+=await save(items,currentId,u.id)}await checkpoint(currentId,n,count,pdf.numPages);page.cleanup?.()}return count}finally{await worker.terminate()}}
async function runNative(pdf,type,start,count){for(let n=start+1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);progress(`PDF.js · página ${n}/${pdf.numPages} · extrayendo texto`);const raw=await text(page);const items=parseCatalogPage(raw,type,n);if(items.length){const u=await user();count+=await save(items,currentId,u.id)}await checkpoint(currentId,n,count,pdf.numPages);page.cleanup?.()}return count}
async function process(file,id,type,start=0){if(busy)return;busy=true;currentId=id;try{const p=await pdfjs(),pdf=await p.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const q=await supabaseClient.from('catalogos_pdf').select('paginas_procesadas,productos_encontrados').eq('id',id).single();if(q.error)throw q.error;let last=Math.max(start,Number(q.data.paginas_procesadas||0)),count=Number(q.data.productos_encontrados||0);await checkpoint(id,last,count,pdf.numPages);
 // Solo inspeccionamos la primera página pendiente para decidir el motor. El catálogo gráfico no se recorre dos veces.
 const probe=await pdf.getPage(Math.min(last+1,pdf.numPages));const probeText=await text(probe);probe.cleanup?.();
 if(probeText.length>=30){progress('Documento con texto detectable · usando extracción PDF.js');count=await runNative(pdf,type,last,count)}
 else{progress('Catálogo gráfico detectado · activando OCR local por página');count=await runOCR(pdf,type,last,count)}
 await checkpoint(id,pdf.numPages,count,pdf.numPages,'PROCESADO');progress(`✓ Importación terminada · ${count} productos encontrados`,true);await list();
 }catch(e){console.error(e);await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e)}).eq('id',id);progress(`Error: ${e.message||e}`)}finally{busy=false}}
async function upload(file,type){if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){alert('Selecciona un PDF.');return}if(file.size>95*1024*1024){alert('El PDF supera 95 MB.');return}try{const u=await user();progress('Subiendo PDF a almacenamiento seguro...');const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await process(file,r.data.id,type,0)}catch(e){progress(`Error: ${e.message||e}`);await list()}}
async function resume(id){if(busy)return;try{const r=await supabaseClient.from('catalogos_pdf').select('archivo_path,tipo,paginas_procesadas').eq('id',id).single();if(r.error)throw r.error;progress('Recuperando el PDF guardado...');const d=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(d.error)throw d.error;const f=new File([d.data],`catalogo-${id}.pdf`,{type:'application/pdf'});await process(f,id,r.data.tipo,Number(r.data.paginas_procesadas||0))}catch(e){progress(`No se pudo continuar: ${e.message||e}`)}}
async function remove(id){if(!confirm('¿Eliminar este catálogo y los productos importados desde él?'))return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).single();if(r.data?.archivo_path)await supabaseClient.storage.from(BUCKET).remove([r.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',u.id);await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);await list()}catch(e){alert(e.message||'No se pudo eliminar')}}
async function list(){const w=document.querySelector('#cat4List');if(!w)return;try{const u=await user(),r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toUpperCase();return`<article class="cat4-row"><div class="cat4-file">PDF</div><div class="cat4-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor · precio compra':'Mi catálogo · precio venta'} · ${c.paginas||'?'} páginas</span><small>${s==='PROCESADO'?'✓ Procesado':s==='PROCESANDO'?`⏳ Página ${c.paginas_procesadas||0}/${c.paginas||'?'} `:`⚠ ${esc(c.error_detalle||'Error')}`} · ${c.productos_encontrados||0} productos</small></div>${s!=='PROCESADO'?`<button class="btn btn-secondary cat4-resume" data-id="${c.id}">${s==='ERROR'?'Reintentar':'Continuar'}</button>`:''}<button class="cat4-delete" data-id="${c.id}">×</button></article>`}).join('')||'<div class="cat4-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF para importar productos.</span></div>';w.querySelectorAll('.cat4-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.cat4-delete').forEach(b=>b.onclick=()=>remove(b.dataset.id))}catch(e){w.innerHTML=`<div class="cat4-empty">${esc(e.message)}</div>`}}
function mount(){if(document.querySelector('#cat4Panel')){list();return}const main=document.querySelector('.main');if(!main)return;const p=document.createElement('section');p.id='cat4Panel';p.className='panel cat4-panel';p.innerHTML=`<div class="cat4-head"><div><p class="eyebrow">M.A.R.C. / INVENTARIO</p><h2>Importador inteligente de catálogos</h2><p>Detecta primero si el PDF contiene texto. Si es un catálogo gráfico, convierte cada página en imagen y ejecuta OCR local sin esperar 45 segundos por página.</p></div><div class="cat4-engine"><b>Motor V4</b><span>PDF.js → OCR → IA opcional</span></div></div><div class="cat4-grid"><label class="cat4-upload"><input id="cat4Own" type="file" accept="application/pdf,.pdf"><span>📘</span><b>Mi catálogo</b><small>Precio detectado → precio de venta</small><strong>Seleccionar PDF</strong></label><label class="cat4-upload"><input id="cat4Supplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><b>Catálogo de proveedor</b><small>Precio detectado → precio de compra</small><strong>Seleccionar PDF</strong></label></div><div id="cat4Progress" class="cat4-progress">Listo para importar.</div><div id="cat4List" class="cat4-list"></div><div class="cat4-info"><b>Datos conservados</b><span>Modelo, código, nombre, categoría, precio de origen, cantidad por caja, presentación y página de origen.</span></div>`;main.appendChild(p);p.querySelector('#cat4Own').onchange=e=>upload(e.target.files?.[0],'PROPIO');p.querySelector('#cat4Supplier').onchange=e=>upload(e.target.files?.[0],'PROVEEDOR');list()}
const css=document.createElement('style');css.textContent=`.cat4-panel{margin-top:18px}.cat4-head{display:flex;justify-content:space-between;gap:20px}.cat4-head h2{margin:4px 0 8px}.cat4-head p:not(.eyebrow){color:#64748b;max-width:760px;margin:0}.cat4-engine{min-width:205px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:14px;padding:14px}.cat4-engine b,.cat4-engine span{display:block}.cat4-engine span{font-size:12px;color:#475569;margin-top:4px}.cat4-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:20px 0}.cat4-upload{border:2px dashed rgba(8,124,245,.28);border-radius:16px;padding:20px;display:grid;grid-template-columns:42px 1fr;gap:4px 12px;cursor:pointer;background:rgba(8,124,245,.025)}.cat4-upload input{display:none}.cat4-upload span{grid-row:1/4;font-size:30px}.cat4-upload b{font-size:16px}.cat4-upload small{color:#64748b}.cat4-upload strong{color:#087cf5}.cat4-progress{padding:13px 15px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;margin-bottom:14px}.cat4-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#087cf5;margin-right:8px;animation:cat4pulse 1s infinite}.cat4-dot.done{background:#16a34a;animation:none}.cat4-list{display:grid;gap:10px}.cat4-row{display:flex;align-items:center;gap:12px;border:1px solid #e2e8f0;border-radius:14px;padding:12px}.cat4-file{width:44px;height:44px;border-radius:10px;background:#eff6ff;color:#087cf5;display:grid;place-items:center;font-weight:800;font-size:11px}.cat4-main{flex:1;min-width:0}.cat4-main b,.cat4-main span,.cat4-main small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cat4-main span,.cat4-main small{font-size:12px;color:#64748b;margin-top:3px}.cat4-delete{border:0;background:none;font-size:24px;color:#94a3b8;cursor:pointer}.cat4-empty{text-align:center;padding:26px;border:1px dashed #cbd5e1;border-radius:14px;color:#64748b}.cat4-empty b,.cat4-empty span{display:block}.cat4-info{margin-top:14px;background:#f8fafc;padding:14px;border-radius:12px;font-size:13px;color:#475569}.cat4-info span{display:block;margin-top:4px}@keyframes cat4pulse{50%{opacity:.35}}@media(max-width:760px){.cat4-head{display:block}.cat4-engine{margin-top:14px}.cat4-grid{grid-template-columns:1fr}.cat4-row{align-items:flex-start}}`;document.head.appendChild(css);
const old=window.render;if(typeof old==='function')window.render=function(section){old.apply(this,arguments);if(section==='inventory')setTimeout(mount,80)};
window.MARC_CATALOG_V4={mount,upload,resume};
})();
