/* M.A.R.C. V9 — lector de catálogos basado en V2, optimizado
   PDF texto: parser determinista. PDF escaneado: /api/analyze-catalog-page.
   Una llamada por página; zonas 2x2 solo si la página completa no devuelve productos.
*/
(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const money=v=>{let s=String(v??'').replace(/S\.?\//gi,'').replace(/[^0-9,.-]/g,'');if(!s)return 0;if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const codeRe=/\b(?:AD|PRO|HIK|DS|IPC|DVR|NVR|CPE|TL|TP|UBNT)-[A-Z0-9][A-Z0-9._/-]*\b/gi;
const oldRender=window.render;
window.render=section=>{if(section!=='inventory')return oldRender(section);const c=document.querySelector('#content');if(!c)return;c.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>V9 · Lector preciso página por página. Texto directo + lector documental para PDF escaneado.</p></div></div><section class="panel"><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px"><label class="panel" style="cursor:pointer"><input id="v9own" type="file" accept="application/pdf,.pdf" hidden><strong>📘 Mi catálogo</strong><p>Catálogo propio</p><b>Seleccionar PDF</b></label><label class="panel" style="cursor:pointer"><input id="v9sup" type="file" accept="application/pdf,.pdf" hidden><strong>🏢 Catálogo de proveedor</strong><p>Se guarda separado</p><b>Seleccionar PDF</b></label></div><div id="v9p" style="margin:16px 0"></div><div id="v9list">Cargando...</div><div id="v9items"></div></section>`;v9('#v9own').onchange=e=>upload(e.target.files[0],'PROPIO');v9('#v9sup').onchange=e=>upload(e.target.files[0],'PROVEEDOR');load()};
const v9=s=>document.querySelector(s);
const msg=t=>{const e=v9('#v9p');if(e)e.textContent=t};
const user=async()=>{const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Sesión expirada.');return r.data.user};
async function pdfjs(){if(window.pdfjsLib)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=ok;s.onerror=()=>no(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
const rows=items=>{const a=[];for(const x of items||[]){const s=clean(x.str);if(!s)continue;const y=Number(x.transform?.[5]||0),last=a[a.length-1];if(last&&Math.abs(last.y-y)<=4)last.p.push(s);else a.push({y,p:[s]})}return a.sort((a,b)=>b.y-a.y).map(x=>clean(x.p.join(' ')))};
function parse(rows){const out=[];for(let i=0;i<rows.length;i++){const line=rows[i],m=line.match(codeRe);if(!m)continue;const code=m[0],idx=line.toUpperCase().indexOf(code.toUpperCase());let before=clean(line.slice(0,idx)),after=clean(line.slice(idx+code.length));const nums=[...after.matchAll(/\d+(?:[.,]\d{1,2})?/g)];let price=0;if(nums.length){const n=nums[nums.length-1];price=money(n[0]);after=clean(after.slice(0,n.index))}if(!before&&rows[i-1]&&!codeRe.test(rows[i-1]))before=clean(rows[i-1]);out.push({codigo:code,nombre:before||code,marca:'',modelo:code,categoria:'',descripcion:after,precio_compra:price,precio_venta:price,unidad:'UND'})}return dedupe(out)}
function dedupe(a){const seen=new Set(),o=[];for(const x of a||[]){const z={codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:money(x.precio_compra),precio_venta:money(x.precio_venta),unidad:clean(x.unidad)||'UND'};if(!z.codigo&&!z.nombre)continue;const k=(z.codigo+'|'+z.nombre).toUpperCase();if(seen.has(k))continue;seen.add(k);o.push(z)}return o}
async function catalogVision(image){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.error||'El lector documental rechazó la página.');return Array.isArray(j.items)?j.items:[]}
async function renderPage(page,scale=2.2){const b=page.getViewport({scale:1}),s=Math.min(scale,2200/Math.max(b.width,1)),v=page.getViewport({scale:s}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;return c}
async function scan(page,n){const full=await renderPage(page,2.2);msg(`🧠 Lector documental · página ${n} · analizando página completa...`);let all=[];try{all=await catalogVision(full.toDataURL('image/jpeg',.88))}catch(e){msg(`⚠️ Página ${n}: ${e.message}`)}if(all.length)return dedupe(all);const v=page.getViewport({scale:1.8}),zones=[];for(let i=0;i<4;i++){const c=document.createElement('canvas'),y=Math.floor(v.height*i/4),h=Math.ceil(v.height/4);c.width=Math.ceil(v.width);c.height=h;await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,transform:[1,0,0,1,0,-y]}).promise;zones.push(c.toDataURL('image/jpeg',.9));c.width=1;c.height=1}for(let i=0;i<zones.length;i++){msg(`🔎 Página ${n} · zona ${i+1}/4...`);try{all.push(...await catalogVision(zones[i]))}catch{}}return dedupe(all)}
async function save(items,id,u,pagina){const a=dedupe(items).map(x=>({user_id:u,catalogo_id:id,codigo:x.codigo,nombre:x.nombre,marca:x.marca,modelo:x.modelo,categoria:x.categoria,descripcion:x.descripcion,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:{pagina,origen:'V9'}}));if(!a.length)return 0;const q=await supabaseClient.from('catalogo_items').insert(a);if(q.error)throw q.error;return a.length}
async function process(file,id,tipo,start=0,reset=false){await pdfjs();const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,estado:'PROCESANDO',error_detalle:null}).eq('id',id);start=0}let q=await supabaseClient.from('catalogos_pdf').select('paginas_procesadas,productos_encontrados').eq('id',id).single(),total=Number(q.data?.productos_encontrados||0);for(let n=start+1;n<=pdf.numPages;n++){try{const page=await pdf.getPage(n),tc=await page.getTextContent({normalizeWhitespace:true}),r=rows(tc.items||[]);let items=parse(r),modo='TEXTO';if(!items.length){modo='LECTOR_DOCUMENTAL';items=await scan(page,n)}if(!items.length)throw Error('No se detectó ningún producto en la página.');const u=await user(),added=await save(items,id,u.id,n);total+=added;await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,estado:'PROCESANDO',error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);msg(`✅ Página ${n}/${pdf.numPages} · ${added} productos · total ${total} · ${modo}`)}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',paginas_procesadas:n-1,productos_encontrados:total,error_detalle:`Página ${n}: ${e.message}`}).eq('id',id);msg(`❌ Página ${n}: ${e.message}`);return}}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null}).eq('id',id);msg(`🎉 Catálogo terminado · ${total} productos`);await load()}
async function upload(file,tipo){if(!file)return;if(file.size>50*1024*1024)return alert('El PDF supera 50 MB.');try{const u=await user(),path=`${u.id}/${crypto.randomUUID()}.pdf`;msg('⬆️ Subiendo PDF...');let q=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf'});if(q.error)throw q.error;q=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0}).select('id').single();if(q.error)throw q.error;await process(file,q.data.id,tipo,0,true);await load()}catch(e){msg('❌ '+e.message);await load()}}
async function load(){const w=v9('#v9list');if(!w)return;const u=await user(),q=await supabaseClient.from('catalogos_pdf').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(q.error){w.textContent=q.error.message;return}w.innerHTML=(q.data||[]).map(c=>`<article class="panel" style="margin-top:12px"><strong>📄 ${esc(c.nombre)}</strong><p>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${(Number(c.tamano_bytes||0)/1048576).toFixed(1)} MB · ${c.paginas||0} páginas</p><b>${esc(String(c.estado||''))} · ${c.productos_encontrados||0} productos</b><p>${esc(c.error_detalle||'')}</p><button class="btn btn-primary v9cont" data-id="${c.id}">${String(c.estado).toUpperCase()==='PROCESADO'?'🔄 Releer V9':'▶ Continuar'}</button></article>`).join('')||'<p>No hay catálogos.</p>';w.querySelectorAll('.v9cont').forEach(b=>b.onclick=()=>reprocess(b.dataset.id))}
async function reprocess(id){const u=await user(),q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;const c=q.data;if(String(c.estado).toUpperCase()==='PROCESADO'&&!confirm('Volver a leer este catálogo desde la página 1?'))return;const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF.');await process(new File([await r.blob()],c.nombre,{type:'application/pdf'}),id,c.tipo,0,String(c.estado).toUpperCase()==='PROCESADO');await load()}
})();