/* M.A.R.C. V6 — lector de catálogos página por página, preciso y reanudable */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=v=>{const s=String(v??'').replace(/\s+/g,' ').trim();return s||''};
  const num=v=>{let s=String(v??'').replace(/S\/?\s*/gi,'').replace(/[^0-9,.-]/g,'').trim();if(!s)return 0;if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='inventory')return oldRender(section);
    const c=document.querySelector('#content');if(!c)return;
    c.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>V6 · Lectura página por página. Prioriza exactitud, guarda cada página y puede continuar si se interrumpe.</p></div></div><section class="panel pv6"><div class="pv6-grid"><label class="pv6-upload"><input id="pv6Own" type="file" accept="application/pdf,.pdf"><span>📘</span><strong>Mi catálogo</strong><small>Catálogo propio</small><b>Seleccionar PDF</b></label><label class="pv6-upload"><input id="pv6Supplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><strong>Catálogo de proveedor</strong><small>Se guarda separado</small><b>Seleccionar PDF</b></label></div><div id="pv6Progress" class="pv6-progress" hidden></div><div id="pv6List">Cargando...</div><div id="pv6Items" hidden></div></section>`;
    document.querySelector('#pv6Own').onchange=e=>upload(e.target.files[0],'PROPIO');
    document.querySelector('#pv6Supplier').onchange=e=>upload(e.target.files[0],'PROVEEDOR');
    load();
  };
  const progress=t=>{const e=document.querySelector('#pv6Progress');if(e){e.hidden=false;e.textContent=t}};
  async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
  async function pdfjs(){if(window.pdfjsLib)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=res;s.onerror=()=>rej(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
  const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
  const state=c=>{const e=String(c.estado||'').toUpperCase(),p=Number(c.paginas||0),d=Number(c.paginas_procesadas||0),n=Number(c.productos_encontrados||0);if(e==='PROCESANDO')return `Leyendo página ${d}/${p}${n?' · '+n+' productos':''}`;if(e==='PROCESADO')return `✓ Terminado · ${n} productos`;return `⚠ ${c.error_detalle||'requiere continuar'}`};
  async function load(){const w=document.querySelector('#pv6List');if(!w)return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,tamano_bytes,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle,archivo_path').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const e=String(c.estado||'').toUpperCase();return `<article class="pv6-row"><div class="pv6-icon">PDF</div><div class="pv6-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${size(c.tamano_bytes)} · ${c.paginas||0} páginas</span><small>${esc(state(c))}</small></div>${e==='PROCESADO'?'<button class="pv6-read" data-id="'+c.id+'">🔄 Releer preciso</button>':'<button class="pv6-read" data-id="'+c.id+'">▶ Continuar lectura</button>'}<button class="pv6-view" data-id="${c.id}">📦 Productos</button></article>`}).join('')||'<div>No hay catálogos.</div>';w.querySelectorAll('.pv6-read').forEach(b=>b.onclick=()=>reprocess(b.dataset.id));w.querySelectorAll('.pv6-view').forEach(b=>b.onclick=()=>view(b.dataset.id))}catch(e){w.innerHTML=esc(e.message)}}
  async function upload(file,tipo){if(!file)return;if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await user();progress(`⬆️ Subiendo ${file.name}...`);const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error)throw r.error;await process(file,r.data.id,tipo,0,true);await load()}catch(e){progress('❌ '+e.message);await load()}}
  async function stored(c){const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF');return new File([await r.blob()],c.nombre,{type:'application/pdf'})}
  function renderPage(page,scale){const base=page.getViewport({scale:1});const s=Math.min(scale,2100/Math.max(base.width,1));const v=page.getViewport({scale:s});const canvas=document.createElement('canvas');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);return page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:v}).promise.then(()=>({canvas,image:canvas.toDataURL('image/jpeg',0.88)}))}
  async function analyze(image,modo='pagina'){const r=await fetch('/api/analyze-catalog-vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,modo})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.error||'La IA no pudo leer la página');return Array.isArray(j.items)?j.items:[]}
  function dedupe(items){const out=[],seen=new Set();for(const x of items||[]){const v={codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:num(x.precio_compra),precio_venta:num(x.precio_venta),unidad:clean(x.unidad)||'UND'};if(!v.codigo&&!v.nombre&&!v.modelo)continue;const k=(v.codigo+'|'+v.modelo+'|'+v.nombre).toUpperCase();if(seen.has(k))continue;seen.add(k);out.push(v)}return out}
  function critical(items){return items.some(x=>x.codigo||x.modelo||x.nombre)&&items.some(x=>x.precio_venta||x.precio_compra)}
  async function focusedValidation(page,items){
    /* Solo se activa cuando la primera lectura carece de campos críticos. Así evitamos 2-3 llamadas en las páginas normales. */
    if(critical(items))return items;
    progress('🔎 Validación ampliada de la página...');
    const base=page.getViewport({scale:1}), zones=[[0,0,1,.48],[0,.48,1,1]], out=[];
    for(const z of zones){const [x1,y1,x2,y2]=z;const scale=Math.min(2.8,1900/Math.max(base.width*(x2-x1),1));const v=page.getViewport({scale});const sx=Math.floor(v.width*x1),sy=Math.floor(v.height*y1),sw=Math.floor(v.width*(x2-x1)),sh=Math.floor(v.height*(y2-y1));const c=document.createElement('canvas');c.width=sw;c.height=sh;await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,transform:[1,0,0,1,-sx,-sy]}).promise;try{out.push(...await analyze(c.toDataURL('image/jpeg',0.9),'validacion'))}catch{}c.width=1;c.height=1}return dedupe([...items,...out])}
  async function tableBands(page){
    /* En PDFs con texto interno y muchas filas, dividir en 4 bandas reduce omisiones de tablas largas. */
    const base=page.getViewport({scale:1}),out=[];for(let i=0;i<4;i++){const y1=i/4,y2=(i+1)/4,scale=Math.min(2.6,1850/base.width),v=page.getViewport({scale}),sx=0,sy=Math.floor(v.height*y1),sw=Math.floor(v.width),sh=Math.floor(v.height*(y2-y1));const c=document.createElement('canvas');c.width=sw;c.height=sh;await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,transform:[1,0,0,1,-sx,-sy]}).promise;try{out.push(...await analyze(c.toDataURL('image/jpeg',0.88),'tabla'))}catch{}c.width=1;c.height=1}return dedupe(out)}
  async function process(file,id,tipo,start=0,reset=false){
    await pdfjs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;
    if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,error_detalle:null}).eq('id',id)}
    const q=await supabaseClient.from('catalogos_pdf').select('productos_encontrados').eq('id',id).single();let total=Number(q.data?.productos_encontrados||0);
    for(let n=start+1;n<=pdf.numPages;n++){
      let canvas=null;try{
        progress(`⏳ Página ${n}/${pdf.numPages} · lectura precisa...`);const page=await pdf.getPage(n);const tc=await page.getTextContent({normalizeWhitespace:true,disableCombineTextItems:false});const text=(tc.items||[]).map(x=>clean(x.str)).filter(Boolean).join(' ');let p=await renderPage(page,2.35);canvas=p.canvas;let items=dedupe(await analyze(p.image,'pagina'));p.image='';
        if(!critical(items))items=await focusedValidation(page,items);
        /* Si el PDF tiene una capa de texto y parece una tabla, usamos bandas visuales solo en esa página. */
        if(text.length>180 && (tc.items||[]).length>25){progress(`📋 Página ${n}/${pdf.numPages} · verificando tabla...`);const band=await tableBands(page);if(band.length>items.length)items=band}
        items=dedupe(items);const u=await user();const added=await save(items,id,u.id,tipo,n);total+=added;
        await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,estado:'PROCESANDO',error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);
        if(canvas){canvas.width=1;canvas.height=1}await new Promise(r=>setTimeout(r,250));
      }catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',paginas_procesadas:Math.max(0,n-1),productos_encontrados:total,error_detalle:`Página ${n}: ${e.message}`,updated_at:new Date().toISOString()}).eq('id',id);progress(`❌ Página ${n}: ${e.message}`);throw e}
    }
    await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ Catálogo terminado: ${total} productos. La lectura fue página por página.`)
  }
  async function save(items,id,userId,tipo,pagina){const vals=dedupe(items).map(v=>({user_id:userId,catalogo_id:id,codigo:v.codigo,nombre:v.nombre,marca:v.marca,modelo:v.modelo,categoria:v.categoria,descripcion:v.descripcion,precio_compra:v.precio_compra,precio_venta:v.precio_venta,unidad:v.unidad,datos_extra:{origen:'GEMMA4_PAGINA_V6',pagina,tipo_fuente:tipo}}));if(!vals.length)return 0;const codes=vals.map(x=>x.codigo).filter(Boolean);let existing=new Set();if(codes.length){const q=await supabaseClient.from('catalogo_items').select('codigo').eq('catalogo_id',id).in('codigo',codes);if(!q.error)(q.data||[]).forEach(x=>existing.add(String(x.codigo)))}const unique=vals.filter(x=>!x.codigo||!existing.has(String(x.codigo)));if(!unique.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(unique);if(r.error)throw r.error;return unique.length}
  async function reprocess(id){const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;if(String(q.data.estado).toUpperCase()==='PROCESADO'&&!confirm('Se volverá a leer todo el PDF página por página. Puede tardar varios minutos, pero prioriza precisión. ¿Continuar?'))return;await process(await stored(q.data),id,q.data.tipo,0,true);await load()}
  async function view(id){const b=document.querySelector('#pv6Items');if(!b)return;b.hidden=false;const r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,categoria,precio_compra,precio_venta,unidad').eq('catalogo_id',id).order('created_at',{ascending:true});const a=r.data||[];b.innerHTML=`<div class="pv6-items"><button id="pv6Close">×</button><h3>${a.length} productos detectados</h3><div class="pv6-scroll"><table><thead><tr><th>Página</th><th>Código</th><th>Producto</th><th>Marca</th><th>Modelo</th><th>Precio</th></tr></thead><tbody>${a.map(x=>`<tr><td>—</td><td>${esc(x.codigo||'')}</td><td>${esc(x.nombre||'')}</td><td>${esc(x.marca||'')}</td><td>${esc(x.modelo||'')}</td><td>${x.precio_venta||x.precio_compra?esc(String(x.precio_venta||x.precio_compra)):'—'}</td></tr>`).join('')}</tbody></table></div></div>`;b.querySelector('#pv6Close').onclick=()=>b.hidden=true}
  const st=document.createElement('style');st.textContent='.pv6{margin-top:16px}.pv6-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pv6-upload{position:relative;min-height:145px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;justify-content:center;cursor:pointer}.pv6-upload input{position:absolute;inset:0;opacity:0}.pv6-upload span{font-size:28px}.pv6-upload strong{font-size:15px;color:#234b73}.pv6-upload small{font-size:10px;color:#7891ad}.pv6-upload b{font-size:10px;color:#087cf5;margin-top:10px}.pv6-progress{margin-top:12px;padding:14px;border-radius:10px;background:#edf7ff;color:#326080;font-size:11px;font-weight:700}.pv6-row{display:flex;align-items:center;gap:10px;border:1px solid #e0eaf3;border-radius:12px;padding:10px;background:#fff;margin-top:8px;flex-wrap:wrap}.pv6-icon{width:42px;height:42px;border-radius:10px;background:#edf5fc;color:#087cf5;display:grid;place-items:center;font-size:10px;font-weight:800}.pv6-main{flex:1;min-width:180px;display:grid;gap:3px}.pv6-main strong{font-size:12px;color:#234b73}.pv6-main span,.pv6-main small{font-size:10px;color:#7891ad}.pv6-main small{color:#087cf5}.pv6-row button{border:0;border-radius:9px;padding:8px 10px;background:#edf7ff;color:#087cf5;font-weight:700;font-size:10px}.pv6-items{margin-top:14px;padding:16px;border:1px solid #dbe8f2;border-radius:14px;background:#fff}.pv6-items>button{float:right;border:0;background:#eef5fb;border-radius:8px;padding:6px 10px}.pv6-scroll{overflow:auto}.pv6-items table{width:100%;border-collapse:collapse;font-size:10px}.pv6-items th,.pv6-items td{padding:7px;border-bottom:1px solid #edf2f6;text-align:left;white-space:nowrap}@media(max-width:650px){.pv6-grid{grid-template-columns:1fr}.pv6-row{align-items:flex-start}}';document.head.appendChild(st);
})();