/* M.A.R.C. — Información general del catálogo */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rubros=['Eléctrico','Mecánica','CCTV','Pintura','Computación','Redes','Ferretería','Construcción','Seguridad electrónica','Audio / Video','Automatización','Otro'];
let bypass=false;
function css(){if(document.getElementById('marc-cat-general-css'))return;const s=document.createElement('style');s.id='marc-cat-general-css';s.textContent='.marc-cat-general{border:1px solid #cfe2f3;background:linear-gradient(135deg,#f5fbff,#fff);border-radius:16px;padding:15px;margin:0 0 15px}.marc-cat-general h3{margin:0 0 4px;color:#153c63;font-size:15px}.marc-cat-general p{margin:0 0 12px;color:#6d86a0;font-size:11px}.marc-cat-general-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:10px}.marc-cat-general label{display:grid;gap:5px;font-size:10px;font-weight:700;color:#52708e}.marc-cat-general input,.marc-cat-general select{border:1px solid #d2e1ed;border-radius:9px;padding:10px;background:#fff;color:#183b60;font-size:12px}.marc-cat-general-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.marc-cat-general-badge{display:inline-flex;gap:6px;align-items:center;background:#eaf5ff;color:#146cae;border-radius:999px;padding:5px 9px;font-size:9px;font-weight:800;margin-top:7px}.marc-cat-general-banner{border:1px solid #dbe8f2;background:#f8fbfe;border-radius:12px;padding:10px;margin-bottom:12px;font-size:11px;color:#385977}.marc-cat-general-banner b{color:#163e64}@media(max-width:650px){.marc-cat-general-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function modal(type,input){css();document.querySelector('#marcCatGeneralModal')?.remove();const m=document.createElement('div');m.id='marcCatGeneralModal';m.className='inventory-modal-backdrop';m.innerHTML=`<div class="inventory-modal"><div class="inventory-modal-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGO</p><h2>Información general del catálogo</h2></div><button type="button" class="inventory-close" data-x>×</button></div><div class="marc-cat-general" style="margin:0"><h3>Esta información se aplicará a todos los productos de este PDF</h3><p>No tendrás que escribir el proveedor producto por producto. Podrás corregir cualquier producto individualmente durante la revisión.</p><div class="marc-cat-general-grid"><label>Proveedor ${type==='PROVEEDOR'?'*':''}<input id="mgiProvider" placeholder="Ej. Hikvision Perú" ${type==='PROVEEDOR'?'required':''}></label><label>Rubro *<select id="mgiRubro" required><option value="">Seleccionar…</option>${rubros.map(r=>`<option>${esc(r)}</option>`).join('')}</select></label><label>Tipo de catálogo<select id="mgiType"><option value="PROVEEDOR">Proveedor</option><option value="PROPIO">Propio</option></select></label></div><label style="display:grid;gap:5px;margin-top:10px;font-size:10px;font-weight:700;color:#52708e">Descripción general<input id="mgiNotes" placeholder="Ej. Accesorios y equipos para instalaciones CCTV"></label><div class="marc-cat-general-actions"><button type="button" class="btn btn-secondary" data-cancel>Cancelar</button><button type="button" class="btn btn-primary" data-ok>Continuar con el escaneo</button></div></div></div>`;document.body.appendChild(m);m.querySelector('#mgiType').value=type;m.querySelector('[data-x]').onclick=m.querySelector('[data-cancel]').onclick=()=>m.remove();m.querySelector('[data-ok]').onclick=()=>{const provider=m.querySelector('#mgiProvider').value.trim(),rubro=m.querySelector('#mgiRubro').value,notes=m.querySelector('#mgiNotes').value.trim();if(type==='PROVEEDOR'&&!provider){alert('Indica el nombre del proveedor.');return}if(!rubro){alert('Selecciona el rubro del catálogo.');return}const info={proveedor:provider,rubro,tipo:type,descripcion:notes};window.__MARC_CATALOG_GENERAL=info;m.remove();bypass=true;input.dataset.marcGeneralReady='1';input.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>{bypass=false},1000);watchForCatalog(input.files?.[0],info)} }
async function me(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
async function watchForCatalog(file,info){if(!file)return;const u=await me().catch(()=>null);if(!u)return;const started=Date.now();let id=null;const find=async()=>{const r=await supabaseClient.from('catalogos_pdf').select('id,estado,paginas,productos_encontrados').eq('user_id',u.id).eq('nombre',file.name).order('created_at',{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data)return null;return r.data};const tick=async()=>{try{const c=await find();if(c){id=c.id;const upd=await supabaseClient.from('catalogos_pdf').update({informacion_general:info}).eq('id',id).eq('user_id',u.id);if(upd.error)console.warn('MARC general',upd.error);await supabaseClient.rpc('aplicar_informacion_general_catalogo',{p_catalogo_id:id});if(String(c.estado||'').toUpperCase()==='PROCESADO'){await supabaseClient.rpc('aplicar_informacion_general_catalogo',{p_catalogo_id:id});enhanceList();return}}if(Date.now()-started<30*60*1000)setTimeout(tick,1500)}catch(e){if(Date.now()-started<30*60*1000)setTimeout(tick,2500)}};tick()}
function intercept(){const bind=input=>{if(!input||input.dataset.marcGeneralBound)return;input.dataset.marcGeneralBound='1';input.addEventListener('change',e=>{if(input.dataset.marcGeneralReady==='1'){delete input.dataset.marcGeneralReady;return}if(bypass)return;e.stopImmediatePropagation();e.preventDefault();const type=input.id==='cat4Prov'?'PROVEEDOR':'PROPIO';modal(type,input)},true)};bind(document.querySelector('#cat4Own'));bind(document.querySelector('#cat4Prov'))}
async function enhanceList(){const w=document.querySelector('#cat4List');if(!w||w.dataset.marcGeneralEnhanced)return;const u=await me().catch(()=>null);if(!u)return;const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,informacion_general').eq('user_id',u.id);if(r.error)return;const map=new Map((r.data||[]).map(x=>[String(x.id),x.informacion_general||{}]));w.querySelectorAll('.cat4-row').forEach(row=>{const b=row.querySelector('.cat4-v7,.cat4-resume,.cat4-delete');const id=b?.dataset.id;const info=map.get(String(id));if(!info?.rubro&&!info?.proveedor)return;const main=row.querySelector('.cat4-main');if(!main||main.querySelector('.marc-cat-general-badge'))return;const badge=document.createElement('div');badge.className='marc-cat-general-badge';badge.textContent=`${info.proveedor||'Catálogo propio'} · ${info.rubro||'Sin rubro'}`;main.appendChild(badge)});w.dataset.marcGeneralEnhanced='1'}
function enhanceEditor(){const modal=document.querySelector('#catEditorModal'),rows=document.querySelector('#catEditorRows');if(!modal||!rows||modal.querySelector('.marc-cat-general-banner'))return;const first=rows.querySelector('.cat-editor-row');if(!first)return;const id=first.dataset.id;supabaseClient.from('catalogo_items').select('datos_extra').eq('id',id).maybeSingle().then(r=>{const info=r.data?.datos_extra?.informacion_general;if(!info)return;const b=document.createElement('div');b.className='marc-cat-general-banner';b.innerHTML=`<b>Información general aplicada a este PDF:</b> ${esc(info.proveedor||'Catálogo propio')} · <b>Rubro:</b> ${esc(info.rubro||'—')}${info.descripcion?` · ${esc(info.descripcion)}`:''}`;const tools=modal.querySelector('.cat-editor-tools');tools?.after(b);if(info.proveedor){rows.querySelectorAll('[data-k="proveedor"]').forEach(i=>{if(!i.value.trim())i.value=info.proveedor})}})}
function start(){css();intercept();new MutationObserver(()=>{intercept();enhanceEditor()}).observe(document.body,{childList:true,subtree:true});setInterval(()=>{enhanceList()},2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else setTimeout(start,200);window.MARC_CATALOG_GENERAL={rubros};
})();
