/* M.A.R.C. — Catálogos V5
   Pipeline exhaustivo para catálogos gráficos:
   PDF.js + OCR auxiliar + IA visual por página.
   La IA ya no es un simple fallback. Cada página es inspeccionada visualmente
   y los resultados se combinan sin descartar productos por falta de precio.
*/
(()=>{
'use strict';
const BUCKET='catalog-pdfs';let busy=false,currentId=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const modelRe=/\b[A-Z0-9]{1,8}[-_/][A-Z0-9]{1,14}\b/gi;
const codeRe=/\b(?:AD|PRO)-[A-Z0-9]+(?:-[A-Z0-9]+)*\b/gi;
const priceRe=/(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))/g;
function prices(s){const a=[];let m;while((m=priceRe.exec(s)))a.push({value:num(m[1]),index:m.index});return a}
function models(s){return s.match(modelRe)||[]}
function codes(s){return (String(s||'').match(codeRe)||[]).map(x=>x.toUpperCase())}
function category(s){s=clean(s).toUpperCase();if(/AUDIFONO|AURICULAR|EARPHONE/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO|MICRÓFONO/.test(s))return'Micrófonos';if(/PARLANTE|ALTAVOZ|SPEAKER/.test(s))return'Parlantes';if(/MEMORIA|USB|MICROSD|SD/.test(s))return'Memorias';if(/WATCH|RELOJ/.test(s))return'Smartwatch';if(/POWER BANK/.test(s))return'Power banks';return'Accesorios'}
function build(code,name,price,type,page,text,qty=1,variant='',extra={}){const v=clean(variant);const p=num(price);return{codigo:clean(code).toUpperCase(),nombre:clean(name)||'Producto sin nombre',marca:/ALDEEPO/i.test(text)?'Aldeepo':'',modelo:clean(code).toUpperCase(),categoria:category(name),descripcion:'',precio_compra:type==='PROVEEDOR'?p:0,precio_venta:type==='PROPIO'?p:0,unidad:'UND',datos_extra:{fuente:'PDF',pagina:page,tipo:type,precio_fuente:p,cantidad_paquete:qty,presentacion:qty>1?'CAJA':'UND',variante:v,confianza:extra.confianza||((code&&p)?'alta':'media'),origen:extra.origen||'OCR/IA'}}}
function parseCatalogPage(text,type,page){
 const lines=String(text||'').split('\n').map(clean).filter(Boolean),up=lines.map(x=>x.toUpperCase()),out=[];
 const foundCodes=[];for(const line of lines)for(const c of codes(line))if(!foundCodes.includes(c))foundCodes.push(c);for(const line of lines)for(const c of models(line))if(!foundCodes.includes(c.toUpperCase()))foundCodes.push(c.toUpperCase());
 const allPrices=lines.flatMap(x=>prices(x));
 let name='';const keys=['AUDIFONO BLUETOOTH','CARGADOR DE AUTO','CARGADOR','CABLE DEL DATOS','CABLE DE DATOS','SOPORTE DEL CELULAR','MOUSE CON CABLE','MOUSE INALAMBRICO','PARLANTE ACUATICO','SMART WATCH','POWER BANK','USB PRO 3.0','USB 3.0','MICROSD','MEMORIA'];
 for(const k of keys){const i=up.findIndex(x=>x.includes(k));if(i>=0){name=lines[i];break}}
 if(!name){const i=up.findIndex(x=>/PRECIO|CAJA|UNIDADES|COLOR/.test(x));if(i>0)name=lines[Math.max(0,i-1)]}
 const pl=lines.find(x=>/PRECIO\s*(?:DE\s*COMPRA|CAJA)?/i.test(x)&&prices(x).length);const price=pl?prices(pl)[0].value:(allPrices[0]?.value||0);const qm=(pl||'').match(/\b(\d{1,4})\s*(?:UNIDADES|UND|PCS|PZAS?)\b/i);const qty=qm?Number(qm[1]):1;
 foundCodes.forEach((code,idx)=>{let localName=name;const pos=up.findIndex(x=>x.includes(code));if(pos>=0){for(let j=Math.max(0,pos-3);j<=Math.min(lines.length-1,pos+4);j++){if(j!==pos&&lines[j].length>4&&!/PRECIO|UNIDADES|CAJA|COLOR/i.test(lines[j])){if(!/^[0-9., S/]+$/.test(lines[j])){localName=lines[j];break}}}}const lp=pos>=0?prices(lines[pos]).find(x=>x.value>0)?.value:0;out.push(build(code,localName,lp||price,type,page,text,qty,'',{confianza:(lp||price)?'media':'baja',origen:'OCR'}));});
 for(const line of lines){const m=line.match(/^(\d{1,4})\s*(GB|TB)\s+(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))$/i);if(m)out.push(build(`${m[1]}${m[2].toUpperCase()}-${page}-${out.length+1}`,name||'Memoria',num(m[3]),type,page,text,1,`${m[1]}${m[2].toUpperCase()}`,{confianza:'media',origen:'OCR'}))}
 const seen=new Set();return out.filter(x=>{const k=`${x.codigo}|${x.nombre}|${x.datos_extra?.variante||''}`.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})
}
function mergeItems(a,b,type,page){const out=[...(a||[])];const key=x=>`${clean(x.codigo).toUpperCase()}|${clean(x.nombre).toUpperCase()}|${clean(x.datos_extra?.variante||'').toUpperCase()}`;const by=new Map(out.map(x=>[key(x),x]));for(const x of (b||[])){const k=key(x);if(!k.startsWith('|')&&!by.has(k)){out.push(x);by.set(k,x)}else if(by.has(k)){const old=by.get(k);if(!old.nombre||old.nombre==='Producto sin nombre')old.nombre=x.nombre;if(!old.precio_compra&&!old.precio_venta&&(x.precio_compra||x.precio_venta)){old.precio_compra=x.precio_compra;old.precio_venta=x.precio_venta}if(old.datos_extra?.confianza==='baja'&&x.datos_extra?.confianza==='alta')old.datos_extra=x.datos_extra}}return out}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const p=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=p;return p}
async function ocrLib(){if(window.Tesseract)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar el OCR local.'));document.head.appendChild(s)})}
async function render(page){const b=page.getViewport({scale:1}),scale=Math.min(2,Math.max(1.6,2200/Math.max(b.width,1))),v=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const data=c.toDataURL('image/jpeg',.86);c.width=1;c.height=1;return data}
async function text(page){const tc=await page.getTextContent({normalizeWhitespace:true});const a=(tc.items||[]).map(x=>({s:clean(x.str),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0)})).filter(x=>x.s);if(!a.length)return'';a.sort((a,b)=>b.y-a.y||a.x-b.x);const ls=[];for(const z of a){let l=ls.find(v=>Math.abs(v.y-z.y)<=2);if(!l){l={y:z.y,a:[]};ls.push(l)}l.a.push(z)}return ls.sort((a,b)=>b.y-a.y).map(l=>l.a.sort((a,b)=>a.x-b.x).map(x=>x.s).join(' ')).join('\n')}
function progress(s,done=false){const e=document.querySelector('#cat4Progress');if(e)e.innerHTML=`<span class="cat4-dot ${done?'done':''}"></span>${esc(s)}`}
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
async function save(items,id,uid){if(!items.length)return 0;const rows=items.map(x=>({user_id:uid,catalogo_id:id,codigo:x.codigo||null,nombre:x.nombre,marca:x.marca,modelo:x.modelo,categoria:x.categoria,descripcion:x.descripcion,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:x.datos_extra}));const r=await supabaseClient.from('catalogo_items').insert(rows);if(r.error)throw r.error;return rows.length}
async function checkpoint(id,page,count,total,status='PROCESANDO',err=null){const r=await supabaseClient.from('catalogos_pdf').update({paginas:total,paginas_procesadas:page,bloques_total:total,bloque_actual:page,productos_encontrados:count,estado:status,error_detalle:err}).eq('id',id);if(r.error)throw r.error}
async function ai(image,type,page,ocrText=''){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,tipo:type,pagina:page,ocr_text:ocrText})});const j=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(j.items))throw new Error(j.error||'IA no disponible');return j.items}
async function processPage(page,type,n,ocrWorker){const image=await render(page);let raw='';if(ocrWorker){const r=await ocrWorker.recognize(image);raw=String(r?.data?.text||'')}let native='';try{native=await text(page)}catch{}progress(`IA visual + OCR · página ${n} · procesando todo el contenido`);let visual=[];try{visual=await ai(image,type,n,raw||native)}catch(e){console.warn('IA visual página',n,e)}let parsed=parseCatalogPage(raw||native,type,n);let merged=mergeItems(parsed,visual,type,n);
 // Todo código recuperado por OCR debe llegar a revisión aunque la IA no lo haya estructurado.
 const detected=[...new Set([...codes(raw),...codes(native)])];for(const c of detected){if(!merged.some(x=>clean(x.codigo).toUpperCase()===c)){merged.push(build(c,'Producto pendiente de revisión',0,type,n,raw||native,1,'',{confianza:'baja',origen:'OCR_CODE_FALLBACK'}))}}
 return merged
}
async function runVisual(pdf,type,start,count){await ocrLib();const worker=await window.Tesseract.createWorker('spa');try{for(let n=start+1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);try{const items=await processPage(page,type,n,worker);if(items.length){const u=await user();count+=await save(items,currentId,u.id)}await checkpoint(currentId,n,count,pdf.numPages);progress(`Página ${n}/${pdf.numPages} completada · ${count} productos candidatos`)}finally{page.cleanup?.()}}return count}finally{await worker.terminate()}}
async function process(file,id,type,start=0){if(busy)return;busy=true;currentId=id;try{const p=await pdfjs(),pdf=await p.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const q=await supabaseClient.from('catalogos_pdf').select('paginas_procesadas,productos_encontrados').eq('id',id).single();if(q.error)throw q.error;const last=Math.max(start,Number(q.data.paginas_procesadas||0));let count=Number(q.data.productos_encontrados||0);await checkpoint(id,last,count,pdf.numPages);progress(`Catálogo grande detectado · IA visual obligatoria · ${pdf.numPages} páginas`);count=await runVisual(pdf,type,last,count);await checkpoint(id,pdf.numPages,count,pdf.numPages,'PROCESADO');progress(`✓ Análisis exhaustivo terminado · ${count} candidatos para revisión`,true);await list()}catch(e){console.error(e);await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e)}).eq('id',id);progress(`Error: ${e.message||e}`)}finally{busy=false}}
async function upload(file,type){if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){alert('Selecciona un PDF.');return}if(file.size>95*1024*1024){alert('El PDF supera 95 MB.');return}try{const u=await user();progress('Subiendo PDF a almacenamiento seguro...');const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await process(file,r.data.id,type,0)}catch(e){progress(`Error: ${e.message||e}`);await list()}}
async function resume(id){if(busy)return;try{const r=await supabaseClient.from('catalogos_pdf').select('archivo_path,tipo,paginas_procesadas').eq('id',id).single();if(r.error)throw r.error;progress('Recuperando el PDF guardado...');const d=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(d.error)throw d.error;const f=new File([d.data],`catalogo-${id}.pdf`,{type:'application/pdf'});await process(f,id,r.data.tipo,Number(r.data.paginas_procesadas||0))}catch(e){progress(`No se pudo continuar: ${e.message||e}`)}}
async function remove(id){if(!confirm('¿Eliminar este catálogo y los productos importados desde él?'))return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).single();if(r.data?.archivo_path)await supabaseClient.storage.from(BUCKET).remove([r.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',u.id);await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);await list()}catch(e){alert(e.message||'No se pudo eliminar')}}
async function list(){const w=document.querySelector('#cat4List');if(!w)return;try{const u=await user(),r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toUpperCase();return`<article class="cat4-row"><div class="cat4-file">PDF</div><div class="cat4-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor · precio compra':'Mi catálogo · precio venta'} · ${c.paginas||'?'} páginas</span><small>${s==='PROCESADO'?'✓ Procesado':s==='PROCESANDO'?`⏳ Página ${c.paginas_procesadas||0}/${c.paginas||'?'} `:`⚠ ${esc(c.error_detalle||'Error')}`} · ${c.productos_encontrados||0} candidatos</small></div>${s!=='PROCESADO'?`<button class="btn btn-secondary cat4-resume" data-id="${c.id}">${s==='ERROR'?'Reintentar':'Continuar'}</button>`:''}<button class="cat4-delete" data-id="${c.id}">×</button></article>`}).join('')||'<div class="cat4-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF para importar productos.</span></div>';w.querySelectorAll('.cat4-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.cat4-delete').forEach(b=>b.onclick=()=>remove(b.dataset.id))}catch(e){w.innerHTML=`<div class="cat4-empty">${esc(e.message)}</div>`}}
function mount(){if(document.querySelector('#cat4Panel')){list();return}const main=document.querySelector('.main');if(!main)return;const p=document.createElement('section');p.id='cat4Panel';p.className='panel cat4-panel';p.innerHTML=`<div class="cat4-head"><div><p class="eyebrow">M.A.R.C. / INVENTARIO</p><h2>Importador inteligente de catálogos</h2><p>Analiza cada página con IA visual y usa OCR/PDF.js como fuentes auxiliares. Todo producto detectado pasa por revisión antes del inventario.</p></div><div class="cat4-engine"><b>Motor V5</b><span>PDF.js + OCR + IA visual por página</span></div></div><div class="cat4-grid"><label class="cat4-upload"><input id="cat4Own" type="file" accept="application/pdf,.pdf"><span>📘</span><b>Mi catálogo</b><small>Precio detectado → precio de venta</small><strong>Seleccionar PDF</strong></label><label class="cat4-upload"><input id="cat4Prov" type="file" accept="application/pdf,.pdf"><span>🏢</span><b>Catálogo de proveedor</b><small>Precio detectado → precio de compra</small><strong>Seleccionar PDF</strong></label></div><div id="cat4Progress" class="cat4-progress"><span class="cat4-dot"></span>Listo para analizar.</div><div id="cat4List" class="cat4-list"></div>`;main.appendChild(p);p.querySelector('#cat4Own').onchange=e=>upload(e.target.files?.[0],'PROPIO');p.querySelector('#cat4Prov').onchange=e=>upload(e.target.files?.[0],'PROVEEDOR');list()}
window.MARC_CATALOGS_V4={mount,upload,process,resume,list};if(typeof window.render==='function'){const old=window.render;window.render=function(section){const r=old.apply(this,arguments);if(section==='inventory')setTimeout(mount,0);return r}}else{window.addEventListener('load',mount)}
})();
