/* M.A.R.C. — Catálogos V4: extracción con doble ruta + rescate visual */
(function(){
  const oldRender=window.render;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clean=v=>String(v??'').trim();
  const num=v=>{const n=Number(String(v??'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
  const uniq=items=>{const seen=new Set(),out=[];for(const x of items||[]){const v={codigo:clean(x.codigo||x.código||x.sku),nombre:clean(x.nombre||x.producto),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria||x.categoría),descripcion:clean(x.descripcion||x.descripción),precio_compra:num(x.precio_compra||x.precioCompra),precio_venta:num(x.precio_venta||x.precioVenta||x.precio),unidad:clean(x.unidad)||'UND'};if(!v.codigo&&!v.modelo&&!v.nombre)continue;const k=(v.codigo||'').toLowerCase()||((v.modelo||'')+'|'+v.nombre+'|'+v.marca).toLowerCase();if(seen.has(k))continue;seen.add(k);out.push(v)}return out};
  const parse=v=>{let s=String(v||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();for(const raw of [s,(s.match(/\{[\s\S]*\}/)||[])[0],(s.match(/\[[\s\S]*\]/)||[])[0]])if(raw){try{const d=JSON.parse(raw);if(Array.isArray(d))return d;if(Array.isArray(d.items))return d.items}catch{}}return []};
  window.render=function(section='dashboard'){if(section!=='inventory')return oldRender(section);const c=document.querySelector('#content');if(!c)return;c.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>Extractor V4: texto + OCR visual + rescate automático.</p></div></div><section class="panel"><div class="v4-grid"><label class="v4-up"><input id="v4own" type="file" accept="application/pdf,.pdf"><b>📘 Mi catálogo</b><small>Catálogo propio</small><strong>Seleccionar PDF</strong></label><label class="v4-up"><input id="v4sup" type="file" accept="application/pdf,.pdf"><b>🏢 Catálogo de proveedor</b><small>Se guarda separado</small><strong>Seleccionar PDF</strong></label></div><div id="v4prog" class="v4prog" hidden></div><div id="v4list">Cargando...</div></section>`;v4load();document.querySelector('#v4own').onchange=e=>v4handle(e.target.files[0],'PROPIO');document.querySelector('#v4sup').onchange=e=>v4handle(e.target.files[0],'PROVEEDOR')};
  const prog=t=>{const e=document.querySelector('#v4prog');if(e){e.hidden=false;e.textContent=t}};
  async function me(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Sesión expirada.');return r.data.user}
  const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
  async function v4load(){const w=document.querySelector('#v4list');if(!w)return;const u=await me();const r=await supabaseClient.from('catalogos_pdf').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error){w.textContent=r.error.message;return}w.innerHTML=(r.data||[]).map(c=>{const st=String(c.estado||'').toLowerCase();return `<article class="v4row"><div class="v4icon">PDF</div><div><b>${esc(c.nombre)}</b><small>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${size(Number(c.tamano_bytes||0))} · ${c.paginas||0} páginas</small><span>${st==='procesado'?`Procesado · ${c.productos_encontrados||0} productos`:st==='procesando'?`Procesando · ${c.paginas_procesadas||0}/${c.paginas||0}`:`${esc(c.error_detalle||'Requiere análisis')}`}</span></div><mark>${esc(c.estado||'')}</mark>${st==='procesado'?`<button data-re="${c.id}">🔄 Reanalizar</button>`:''}${st==='error'||st==='procesando'?`<button data-go="${c.id}">▶ Continuar</button>`:''}<button data-x="${c.id}">×</button></article>`}).join('');w.querySelectorAll('[data-re]').forEach(b=>b.onclick=()=>v4processStored(b.dataset.re,true));w.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>v4processStored(b.dataset.go,false));w.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>v4del(b.dataset.x))}
  async function v4handle(file,tipo){if(!file)return;if(!/\.pdf$/i.test(file.name)){alert('Selecciona un PDF.');return}if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await me();const path=`${u.id}/${crypto.randomUUID()}.pdf`;prog(`⬆️ Subiendo ${file.name}...`);let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf'});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,productos_encontrados:0}).select('id').single();if(r.error)throw r.error;await v4process(file,r.data.id,tipo,0,true)}catch(e){prog('❌ '+e.message);await v4load()}}
  async function v4processStored(id,reset){try{const u=await me();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;const c=q.data;if(reset&&!confirm('Reanalizar todo el catálogo con el extractor V4?'))return;const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const rr=await fetch(s.data.signedUrl);if(!rr.ok)throw Error('No se pudo recuperar el PDF.');const file=new File([await rr.blob()],c.nombre,{type:'application/pdf'});const start=reset?0:(String(c.estado).toUpperCase()==='ERROR'?Math.max(0,Number(c.paginas_procesadas||0)-1):Number(c.paginas_procesadas||0));await v4process(file,id,c.tipo,start,reset)}catch(e){prog('❌ '+e.message);await v4load()}}
  async function v4process(file,id,tipo,start,reset){try{if(!window.pdfjsLib)await pdfjs();const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,productos_encontrados:0,error_detalle:null}).eq('id',id)}let total=reset?0:Number((await supabaseClient.from('catalogos_pdf').select('productos_encontrados').eq('id',id).single()).data?.productos_encontrados||0);for(let p=start+1;p<=pdf.numPages;p++){prog(`🧠 Analizando página ${p}/${pdf.numPages}...`);const items=await pageAI(pdf,p);const u=await me();const added=await save(items,id,u.id,tipo,p);total+=added;await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:p,bloque_actual:p,bloques_total:pdf.numPages,productos_encontrados:total,estado:'PROCESANDO',updated_at:new Date().toISOString()}).eq('id',id)}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);prog(`✓ Catálogo procesado: ${total} productos encontrados.`);await v4load()}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e)}).eq('id',id);prog('❌ '+(e.message||e));await v4load()}}
  async function pageAI(pdf,n){const page=await pdf.getPage(n);const text=(await page.getTextContent()).items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();let out=[];if(text.length>40){for(let i=0;i<text.length;i+=3000){const chunk=text.slice(i,i+3000);prog(`🧠 Página ${n}: bloque ${Math.floor(i/3000)+1}`);try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Eres extractor de inventario. Encuentra TODOS los productos del bloque. No inventes. Conserva código/SKU, nombre, marca y modelo exactamente. Devuelve SOLO JSON {"items":[{"codigo":"","nombre":"","marca":"","modelo":"","categoria":"","descripcion":"","precio_compra":0,"precio_venta":0,"unidad":"UND"}]}. Ignora títulos generales y especificaciones que no sean productos. BLOQUE:\n${chunk}`})});const j=await r.json().catch(()=>({}));if(r.ok)out.push(...parse(j.text))}catch{}}}if(!out.length){prog(`👁️ Página ${n}: OCR visual...`);out=await visualRescue(page)}return uniq(out)}
  async function visualRescue(page){try{const v=page.getViewport({scale:1});const scale=Math.min(1.35,1500/Math.max(v.width,1));const full=page.getViewport({scale});const can=document.createElement('canvas');can.width=Math.ceil(full.width);can.height=Math.ceil(full.height);await page.render({canvasContext:can.getContext('2d',{alpha:false}),viewport:full}).promise;const results=[];for(let ry=0;ry<2;ry++)for(let cx=0;cx<2;cx++){const x=Math.floor(cx*can.width/2),y=Math.floor(ry*can.height/2),w=Math.min(can.width-x,Math.ceil(can.width/2*1.08)),h=Math.min(can.height-y,Math.ceil(can.height/2*1.08));const crop=document.createElement('canvas');crop.width=w;crop.height=h;crop.getContext('2d',{alpha:false}).drawImage(can,x,y,w,h,0,0,w,h);const image=crop.toDataURL('image/jpeg',0.7);try{const r=await fetch('/api/analyze-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const j=await r.json().catch(()=>({}));if(r.ok&&j.text)results.push(...parse(j.text))}catch{}}can.width=1;can.height=1;return uniq(results)}catch{return []}}
  async function save(items,id,userId,tipo,pagina){const valid=uniq(items).map(x=>({user_id:userId,catalogo_id:id,codigo:x.codigo||null,nombre:x.nombre||null,marca:x.marca||null,modelo:x.modelo||null,categoria:x.categoria||null,descripcion:x.descripcion||null,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:{origen:'PDF',tipo_fuente:tipo,pagina}})).filter(x=>x.codigo||x.modelo||x.nombre);if(!valid.length)return 0;const q=await supabaseClient.from('catalogo_items').insert(valid);if(q.error)throw q.error;return valid.length}
  async function v4del(id){if(!confirm('¿Eliminar catálogo?'))return;const u=await me();const q=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await supabaseClient.storage.from('catalog-pdfs').remove([q.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').delete().eq('id',id);v4load()}
  function pdfjs(){return new Promise((ok,no)=>{if(window.pdfjsLib)return ok();const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=ok;s.onerror=()=>no(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
  const st=document.createElement('style');st.textContent='.v4-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v4-up{border:1.5px dashed #b9d1e5;border-radius:16px;padding:22px;display:grid;gap:7px;cursor:pointer;background:#f7fbff}.v4-up input{display:none}.v4-up b{font-size:16px;color:#234b73}.v4-up small{color:#7891ad}.v4-up strong{color:#087cf5}.v4prog{margin-top:12px;padding:12px;border-radius:10px;background:#edf7ff;color:#326080}.v4row{display:flex;align-items:center;gap:10px;margin-top:10px;padding:11px;border:1px solid #e0eaf3;border-radius:12px}.v4icon{width:42px;height:42px;display:grid;place-items:center;background:#edf5fc;color:#087cf5;border-radius:10px;font-weight:800}.v4row>div:nth-child(2){flex:1;display:grid;gap:3px;min-width:0}.v4row b{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v4row small,.v4row span{font-size:9px;color:#7891ad}.v4row span{color:#087cf5}.v4row mark{font-size:9px;border-radius:8px;padding:4px 7px;background:#e9f8ef}.v4row button{border:0;border-radius:9px;padding:8px 10px;background:#edf7ff;color:#087cf5;font-weight:700}.v4row button:last-child{background:#f3f7fa;color:#567}.v4-up strong{font-size:11px}@media(max-width:650px){.v4-grid{grid-template-columns:1fr}.v4row{flex-wrap:wrap}.v4row mark{order:2}.v4row button{order:3}.v4row>div:nth-child(2){min-width:55%}}';document.head.appendChild(st);
})();
