/* M.A.R.C. — Importador de catálogos V3
 * Flujo: PDF.js -> texto nativo -> render -> OCR local -> IA opcional -> validación -> Supabase
 * Diseñado para catálogos gráficos como CATALOGO CAJA ACCESORIOS.pdf.
 */
(()=>{
'use strict';
const BUCKET='catalog-pdfs';
let busy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const codeRe=/\b[A-Z]{1,6}[-_/][A-Z0-9]{1,12}\b/i;
function category(s){s=clean(s).toUpperCase();if(/AUDIFONO|AURICULAR|EARPHONE/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO|MICRÓFONO/.test(s))return'Micrófonos';if(/PARLANTE|ALTAVOZ|SPEAKER/.test(s))return'Parlantes';if(/MEMORIA|USB/.test(s))return'Memorias';if(/RELOJ|WATCH/.test(s))return'Smartwatch';if(/POWER BANK|BATERIA/.test(s))return'Power banks';return'Accesorios'}
function priceMatches(s){const out=[];const re=/(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))/g;let m;while((m=re.exec(s)))out.push({v:num(m[1]),i:m.index});return out}
function modelMatches(s){return s.match(/\b[A-Z0-9]{1,8}[-_/][A-Z0-9]{1,12}\b/gi)||[]}
function pageToItem(text,tipo,page){
 const lines=text.split('\n').map(clean).filter(Boolean); const upper=lines.map(x=>x.toUpperCase());
 const items=[];
 const priceLine=lines.find(x=>/PRECIO\s*CAJA/i.test(x)&&priceMatches(x).length);
 const price=priceLine?priceMatches(priceLine)[0].v:0;
 const qtym=(priceLine||'').match(/\b(\d{1,4})\s*(?:UNIDADES|UND|PCS|PZAS?)\b/i); const qty=qtym?Number(qtym[1]):1;
 let model='',mi=-1; for(let i=0;i<lines.length;i++){const m=modelMatches(lines[i]);if(m.length){model=m[m.length-1].toUpperCase();mi=i;break}}
 let name='';
 const preferred=['AUDIFONO BLUETOOTH','CARGADOR','CARGADOR DE AUTO','CABLE DEL DATOS','CABLE DE DATOS','SOPORTE DEL CELULAR','MOUSE CON CABLE','MOUSE INALAMBRICO','PARLANTE ACUATICO','SMART WATCH','POWER BANK','USB 3.0','USB PRO 3.0','MEMORIA'];
 for(const p of preferred){const idx=upper.findIndex(x=>x.includes(p));if(idx>=0){name=lines[idx];break}}
 if(!name){for(let i=Math.max(0,mi-2);i<Math.min(lines.length,mi+6);i++){if(lines[i].length>4&&!/PRECIO|COLOR|UNIDADES|CAJA|S\/?\s*\d/i.test(lines[i])&&lines[i]!==model){name=lines[i];break}}}
 if(model && (price||name)) items.push(make(model,name||'Producto sin nombre',price,tipo,page,qty,text));
 // Tablas de memorias/USB: modelo/capacidad + precio en la misma zona.
 for(let i=0;i<lines.length;i++){
   const m=lines[i].match(/^(\d{1,4})\s*(GB|TB)\s*(?:S\.?\/\.?\s*)?(\d{1,6}(?:[.,]\d{1,2}))$/i);
   if(m) items.push(make(`${m[1]}${m[2].toUpperCase()}-${page}`,name||'Memoria USB',num(m[3]),tipo,page,1,text,`${m[1]}${m[2].toUpperCase()}`));
   else if(/^\d{1,4}\s*(GB|TB)$/i.test(lines[i])&&priceMatches(lines[i+1]||'').length) items.push(make(`${clean(lines[i]).toUpperCase()}-${page}`,name||'Memoria',priceMatches(lines[i+1])[0].v,tipo,page,1,text,clean(lines[i]).toUpperCase()));
 }
 const seen=new Set();return items.filter(x=>{const k=(x.codigo||x.nombre).toLowerCase();if(seen.has(k))return false;seen.add(k);return true});
}
function make(code,name,price,tipo,page,qty,text,variant=''){return{codigo:clean(code).toUpperCase(),nombre:clean(name),marca:/ALDEEPO/i.test(text)?'Aldeepo':'',modelo:clean(code).toUpperCase(),categoria:category(name),descripcion:'',precio_compra:tipo==='PROVEEDOR'?price:0,precio_venta:tipo==='PROPIO'?price:0,unidad:'UND',datos_extra:{fuente:'PDF',pagina:page,tipo,precio_fuente:price,cantidad_paquete:qty,presentacion:qty>1?'CAJA':'UND',variante:variant,ocr:false,confianza:price&&code?'alta':'media'}}}
async function loadPdfJs(){if(window.pdfjsLib)return window.pdfjsLib;const u='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';const pdfjs=await import(u);pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=pdfjs;return pdfjs}
async function loadTesseract(){if(window.Tesseract)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar OCR local.'));document.head.appendChild(s)})}
async function renderPage(page){const base=page.getViewport({scale:1});const scale=Math.min(2,Math.max(1.25,1800/Math.max(base.width,1)));const vp=page.getViewport({scale});const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:vp}).promise;const data=c.toDataURL('image/jpeg',.82);c.width=1;c.height=1;return data}
async function nativeText(page){const tc=await page.getTextContent({normalizeWhitespace:true});const a=(tc.items||[]).map(x=>({s:clean(x.str),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0)})).filter(x=>x.s);if(!a.length)return'';a.sort((p,q)=>q.y-p.y||p.x-q.x);const lines=[];for(const z of a){let l=lines.find(v=>Math.abs(v.y-z.y)<=2);if(!l){l={y:z.y,a:[]};lines.push(l)}l.a.push(z)}return lines.sort((p,q)=>q.y-p.y).map(l=>l.a.sort((p,q)=>p.x-q.x).map(z=>z.s).join(' ')).join('\n')}
function setProgress(s,kind=''){const e=document.querySelector('#cat3Progress');if(e){e.hidden=false;e.innerHTML=`<span class="cat3-spinner ${kind==='done'?'done':''}"></span>${esc(s)}`}}
async function ocrAll(pdf,tipo,start,totalRef){await loadTesseract();const worker=await window.Tesseract.createWorker('spa');let total=totalRef||0;try{for(let n=start+1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);setProgress(`OCR local · página ${n}/${pdf.numPages} · ${total} productos`);const img=await renderPage(page);const r=await worker.recognize(img);const text=String(r?.data?.text||'');let items=pageToItem(text,tipo,n);if(!items.length){items=await aiPage(img,tipo,n).catch(()=>[])}items=normalize(items,tipo,n);if(items.length){const u=await getUser();total+=await saveItems(items,currentCatalogId,u.id)}await checkpoint(currentCatalogId,n,total,pdf.numPages);page.cleanup?.()}return total}finally{await worker.terminate()}}
async function aiPage(image,tipo,pagina){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,tipo,pagina})});const j=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(j.items))throw new Error(j.error||'IA no disponible');return j.items}
function normalize(items,tipo,pagina){return(Array.isArray(items)?items:[]).map(x=>{const p=num(x.precio_fuente??x.precio_compra??x.precio_venta);return{codigo:clean(x.codigo),nombre:clean(x.nombre)||'Producto sin nombre',marca:clean(x.marca),modelo:clean(x.modelo)||clean(x.codigo),categoria:clean(x.categoria)||category(x.nombre),descripcion:clean(x.descripcion),precio_compra:tipo==='PROVEEDOR'?p:0,precio_venta:tipo==='PROPIO'?p:0,unidad:clean(x.unidad)||'UND',datos_extra:{...(x.datos_extra||{}),fuente:'PDF',pagina,tipo,precio_fuente:p}}}).filter(x=>x.codigo||x.nombre)}
async function getUser(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
let currentCatalogId=null;
async function saveItems(items,id,uid){if(!items.length)return 0;const rows=[];for(const x of items)rows.push({user_id:uid,catalogo_id:id,codigo:x.codigo||null,nombre:x.nombre,marca:x.marca,modelo:x.modelo,categoria:x.categoria,descripcion:x.descripcion,precio_compra:x.precio_compra,precio_venta:x.precio_venta,unidad:x.unidad,datos_extra:x.datos_extra});const r=await supabaseClient.from('catalogo_items').insert(rows);if(r.error)throw r.error;return rows.length}
async function checkpoint(id,page,count,total){await supabaseClient.from('catalogos_pdf').update({paginas:total,paginas_procesadas:page,bloques_total:total,bloque_actual:page,productos_encontrados:count,estado:page>=total?'PROCESADO':'PROCESANDO',error_detalle:null}).eq('id',id)}
async function processFile(file,id,tipo,start=0){if(busy)return;busy=true;currentCatalogId=id;try{const pdfjs=await loadPdfJs();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let q=await supabaseClient.from('catalogos_pdf').select('paginas_procesadas,productos_encontrados').eq('id',id).single();if(q.error)throw q.error;let last=Number(q.data.paginas_procesadas||start),count=Number(q.data.productos_encontrados||0);await checkpoint(id,last,count,pdf.numPages);let nativePages=0;for(let n=last+1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);setProgress(`Analizando página ${n}/${pdf.numPages} · buscando texto nativo...`);const tx=await nativeText(page);if(tx.length>=30){nativePages++;let items=normalize(pageToItem(tx,tipo,n),tipo,n);if(items.length){const u=await getUser();count+=await saveItems(items,id,u.id)}}page.cleanup?.();await checkpoint(id,n,count,pdf.numPages)}if(nativePages===0){setProgress(`Catálogo gráfico detectado · iniciando OCR local página por página...`);q=await supabaseClient.from('catalogos_pdf').select('productos_encontrados,paginas_procesadas').eq('id',id).single();count=Number(q.data?.productos_encontrados||count);last=Number(q.data?.paginas_procesadas||0);count=await ocrAll(pdf,tipo,last,count)}else{setProgress(`Texto nativo procesado · ${count} productos encontrados`, 'done')}await loadList()}catch(e){console.error(e);await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e)}).eq('id',id);setProgress(`Error: ${e.message||e}`)}finally{busy=false}}
async function upload(file,tipo){if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){alert('Selecciona un PDF.');return}if(file.size>95*1024*1024){alert('El PDF supera 95 MB.');return}try{const u=await getUser();setProgress('Subiendo catálogo...');const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await processFile(file,r.data.id,tipo,0)}catch(e){setProgress(`Error: ${e.message||e}`);await loadList()}}
async function resume(id){if(busy)return;try{const u=await getUser();const r=await supabaseClient.from('catalogos_pdf').select('archivo_path,tipo,paginas_procesadas').eq('id',id).single();if(r.error)throw r.error;setProgress('Descargando catálogo guardado para continuar...');const d=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(d.error)throw d.error;const file=new File([d.data],r.data.archivo_path.split('/').pop()+'.pdf',{type:'application/pdf'});await processFile(file,id,r.data.tipo,Number(r.data.paginas_procesadas||0))}catch(e){setProgress(`No se pudo continuar: ${e.message||e}`)}}
async function removeCatalog(id){if(!confirm('¿Eliminar este catálogo y sus productos importados?'))return;try{const u=await getUser();const r=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).single();if(r.data?.archivo_path)await supabaseClient.storage.from(BUCKET).remove([r.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',u.id);await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);await loadList()}catch(e){alert(e.message||'No se pudo eliminar')}}
async function loadList(){const w=document.querySelector('#cat3List');if(!w)return;try{const u=await getUser();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toUpperCase();return`<article class="cat3-row"><div class="cat3-file">PDF</div><div class="cat3-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor · precio compra':'Mi catálogo · precio venta'} · ${c.paginas||'?'} páginas</span><small>${s==='PROCESADO'?'✓ Procesado · ':s==='PROCESANDO'?'⏳ Página '+(c.paginas_procesadas||0)+'/'+(c.paginas||'?')+' · ':'⚠ '+esc(c.error_detalle||'Requiere continuar')} ${c.productos_encontrados||0} productos</small></div>${s!=='PROCESADO'?`<button class="btn btn-secondary cat3-resume" data-id="${c.id}">${s==='ERROR'?'Reintentar':'Continuar'}</button>`:''}<button class="cat3-delete" data-id="${c.id}" aria-label="Eliminar">×</button></article>`}).join('')||'<div class="cat3-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF para comenzar.</span></div>';w.querySelectorAll('.cat3-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.cat3-delete').forEach(b=>b.onclick=()=>removeCatalog(b.dataset.id))}catch(e){w.innerHTML=`<div class="cat3-empty">${esc(e.message)}</div>`}}
function mount(){if(document.querySelector('#cat3Panel')){loadList();return}const main=document.querySelector('.main');if(!main)return;const p=document.createElement('section');p.id='cat3Panel';p.className='panel cat3-panel';p.innerHTML=`<div class="cat3-head"><div><p class="eyebrow">M.A.R.C. / INVENTARIO</p><h2>Importador inteligente de catálogos</h2><p>Detecta si el PDF tiene texto o es un catálogo gráfico. En documentos como el catálogo Aldeepo, procesa las páginas como imágenes y aplica OCR local sin bloquear todo el documento.</p></div><div class="cat3-engine"><b>Motor V3</b><span>PDF.js → OCR → IA opcional</span></div></div><div class="cat3-upload-grid"><label class="cat3-upload"><input id="cat3Own" type="file" accept="application/pdf,.pdf"><span>📘</span><b>Mi catálogo</b><small>El precio detectado se guarda como precio de venta</small><strong>Seleccionar PDF</strong></label><label class="cat3-upload"><input id="cat3Supplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><b>Catálogo de proveedor</b><small>El precio detectado se guarda como precio de compra</small><strong>Seleccionar PDF</strong></label></div><div id="cat3Progress" class="cat3-progress" hidden></div><div id="cat3List" class="cat3-list"></div><div class="cat3-info"><b>Qué guarda M.A.R.C.</b><span>Modelo · código · nombre · categoría · precio original · cantidad por caja · página de origen · presentación y datos extraídos.</span></div>`;main.appendChild(p);p.querySelector('#cat3Own').onchange=e=>upload(e.target.files?.[0],'PROPIO');p.querySelector('#cat3Supplier').onchange=e=>upload(e.target.files?.[0],'PROVEEDOR');loadList()}
const style=document.createElement('style');style.textContent=`.cat3-panel{margin-top:18px}.cat3-head{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}.cat3-head h2{margin:4px 0 8px}.cat3-head p:not(.eyebrow){max-width:780px;color:#64748b;margin:0}.cat3-engine{min-width:210px;padding:14px 16px;border:1px solid #dbeafe;border-radius:14px;background:#eff6ff}.cat3-engine b,.cat3-engine span{display:block}.cat3-engine span{font-size:12px;color:#475569;margin-top:4px}.cat3-upload-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:20px 0}.cat3-upload{border:2px dashed rgba(8,124,245,.28);border-radius:16px;padding:20px;display:grid;grid-template-columns:44px 1fr;gap:3px 12px;cursor:pointer;background:rgba(8,124,245,.025)}.cat3-upload:hover{background:rgba(8,124,245,.06)}.cat3-upload input{display:none}.cat3-upload span{grid-row:1/4;font-size:32px}.cat3-upload b{font-size:16px}.cat3-upload small{color:#64748b}.cat3-upload strong{color:#087cf5;margin-top:5px}.cat3-progress{padding:13px 15px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0;margin-bottom:14px}.cat3-spinner{display:inline-block;width:10px;height:10px;border:2px solid #cbd5e1;border-top-color:#087cf5;border-radius:50%;margin-right:8px;animation:cat3spin .8s linear infinite}.cat3-spinner.done{border-color:#22c55e}.cat3-list{display:grid;gap:10px}.cat3-row{display:flex;align-items:center;gap:12px;padding:12px;border:1px solid #e2e8f0;border-radius:14px}.cat3-file{width:44px;height:44px;border-radius:10px;background:#eff6ff;color:#087cf5;display:grid;place-items:center;font-size:11px;font-weight:800}.cat3-main{flex:1;min-width:0}.cat3-main b,.cat3-main span,.cat3-main small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cat3-main span,.cat3-main small{font-size:12px;color:#64748b;margin-top:3px}.cat3-delete{border:0;background:transparent;font-size:25px;color:#94a3b8;cursor:pointer}.cat3-empty{text-align:center;padding:28px;color:#64748b;border:1px dashed #cbd5e1;border-radius:14px}.cat3-empty b,.cat3-empty span{display:block}.cat3-info{margin-top:14px;padding:14px;border-radius:12px;background:#f8fafc;color:#475569;font-size:13px}.cat3-info span{display:block;margin-top:4px}@keyframes cat3spin{to{transform:rotate(360deg)}}@media(max-width:760px){.cat3-head{display:block}.cat3-engine{margin-top:14px}.cat3-upload-grid{grid-template-columns:1fr}.cat3-row{align-items:flex-start}.cat3-row .btn{font-size:12px;padding:8px}.cat3-main{min-width:0}}`;document.head.appendChild(style);
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(section){oldRender.apply(this,arguments);if(section==='inventory')setTimeout(mount,90)};
window.MARC_CATALOG_V3={mount,upload,resume};
})();
