/* M.A.R.C. — V5.8: reconstrucción de filas por coordenadas */
(()=>{
'use strict';
const BUCKET='catalog-pdfs';let running=false;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const codeRe=/\b(?:AD|PRO)-[A-Z0-9]+(?:-[A-Z0-9]+)*\b/ig;
const codeOk=s=>/^(?:AD|PRO)-[A-Z0-9]+(?:-[A-Z0-9]+)*$/i.test(clean(s));
const codes=s=>[...new Set((String(s||'').match(codeRe)||[]).map(x=>x.toUpperCase()))];
function category(s){s=clean(s).toUpperCase();if(/AUDIFONO|AURICULAR|EARPHONE/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/SOPORTE/.test(s))return'Soportes';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO/.test(s))return'Micrófonos';if(/PARLANTE|SPEAKER/.test(s))return'Parlantes';if(/MEMORIA|USB/.test(s))return'Memorias';if(/WATCH|RELOJ/.test(s))return'Smartwatch';if(/POWER BANK/.test(s))return'Power banks';return'Accesorios'}
function validName(s,code=''){let n=clean(s).replace(/[|:]+/g,' ');if(code)n=n.replace(new RegExp(code,'ig'),' ');n=clean(n);if(n.length<3||!/[A-Za-zÁÉÍÓÚÑáéíóúñ]/.test(n))return false;if(/^(PRECIO|CÓDIGO|CODIGO|FOTO|NOMBRE|UNIDAD|DESCRIPCIÓN|DESCRIPCION|DOCENA)$/i.test(n))return false;if(/^S\.?\/?\s*\d/i.test(n))return false;return true}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const p=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=p;return p}
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
async function render(page){const b=page.getViewport({scale:1}),scale=Math.min(3,Math.max(2.2,3000/Math.max(b.width,1))),v=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const d=c.toDataURL('image/jpeg',.95);c.width=1;c.height=1;return d}
async function textItems(page){const tc=await page.getTextContent({normalizeWhitespace:false,disableCombineTextItems:false});return(tc.items||[]).map(it=>{const t=clean(it.str),tr=it.transform||[];return t?{t,x:Number(tr[4]||0),y:Number(tr[5]||0),w:Number(it.width||0)}:null}).filter(Boolean)}
function priceItem(it){const m=String(it.t).match(/(?:S\.?\/\.?\s*)?(\d{1,5}(?:[.,]\d{1,2}))(?!\d)/);return m?num(m[1]):0}
function buildRows(items){
 const result=[];const codeItems=items.filter(it=>codeOk(it.t));
 for(const ci of codeItems){
  const code=clean(ci.t).toUpperCase();
  const nearby=items.filter(it=>Math.abs(it.y-ci.y)<=34);
  const prices=nearby.map(it=>({it,p:priceItem(it)})).filter(z=>z.p>0&&z.p<100000);
  if(!prices.length)continue;
  prices.sort((a,b)=>Math.abs(a.it.y-ci.y)-Math.abs(b.it.y-ci.y)||b.it.x-a.it.x);
  const right=prices.filter(z=>z.it.x>=ci.x-30).sort((a,b)=>Math.abs(a.it.y-ci.y)-Math.abs(b.it.y-ci.y)||b.it.x-a.it.x);
  const pr=(right[0]||prices[0]).p;
  const nameParts=nearby.filter(it=>it.x<ci.x-4&&!priceItem(it)&&!codeOk(it.t)&&!/^(NOMBRE|CÓDIGO|CODIGO|FOTO|PRECIO|DOCENA)$/i.test(it.t)).sort((a,b)=>Math.abs(a.y-ci.y)-Math.abs(b.y-ci.y)||a.x-b.x);
  let name=clean(nameParts.slice(0,3).map(x=>x.t).join(' '));
  if(!validName(name,code)){
   const all=items.filter(it=>Math.abs(it.y-ci.y)<=55&&!priceItem(it)&&!codeOk(it.t)).sort((a,b)=>Math.abs(a.y-ci.y)-Math.abs(b.y-ci.y)||a.x-b.x);
   name=clean(all.slice(0,4).map(x=>x.t).join(' '));
  }
  if(validName(name,code))result.push({codigo:code,nombre:name,precio:pr,y:ci.y});
 }
 return result;
}
function mergeRows(rows){const map=new Map();for(const r of rows){const k=r.codigo+'|'+clean(r.nombre).toUpperCase();if(!map.has(k))map.set(k,r)}return [...map.values()]}
function makeCandidates(rows,type,page){return mergeRows(rows).map(r=>({codigo:r.codigo,nombre:r.nombre,marca:'',modelo:r.codigo,categoria:category(r.nombre),descripcion:r.nombre,precio_compra:type==='PROVEEDOR'?r.precio:0,precio_venta:type==='PROPIO'?r.precio:0,unidad:'UND',datos_extra:{fuente:'PDF texto + coordenadas',pagina:page,tipo:type,precio_fuente:r.precio,cantidad_paquete:1,presentacion:'UND',variante:'',confianza:'Fila reconstruida del PDF'}}))}
async function ocr(image){if(!window.Tesseract)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar OCR'));document.head.appendChild(s)});const w=await window.Tesseract.createWorker('spa');try{return String((await w.recognize(image))?.data?.text||'')}finally{await w.terminate()}}
async function enrich(image,type,page,raw,candidates){if(!candidates.length)return candidates;try{const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,tipo:type,pagina:page,ocr_text:raw.slice(0,12000),filas_tabla:candidates.map(x=>({codigo:x.codigo,nombre:x.nombre,precio:x.datos_extra.precio_fuente}))})});const j=await r.json();if(!r.ok||!Array.isArray(j.items))return candidates;const by=new Map(candidates.map(x=>[x.codigo,x]));for(const z of j.items){const c=by.get(clean(z.codigo).toUpperCase());if(!c)continue;if(validName(z.nombre,c.codigo))c.nombre=clean(z.nombre);if(clean(z.marca))c.marca=clean(z.marca);if(clean(z.modelo))c.modelo=clean(z.modelo);if(clean(z.categoria))c.categoria=clean(z.categoria);if(clean(z.descripcion))c.descripcion=clean(z.descripcion);if(clean(z.variante))c.datos_extra.variante=clean(z.variante);if(Number(z.cantidad_paquete)>0)c.datos_extra.cantidad_paquete=Number(z.cantidad_paquete);if(clean(z.presentacion))c.datos_extra.presentacion=clean(z.presentacion);if(clean(z.unidad))c.unidad=clean(z.unidad)}return candidates}catch(e){console.warn('IA enriquecimiento',page,e);return candidates}}
async function save(items,id,uid,seen){const fresh=items.filter(x=>{const k=x.codigo+'|'+clean(x.nombre).toUpperCase();if(seen.has(k))return false;seen.add(k);return true});if(!fresh.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(fresh.map(x=>({user_id:uid,catalogo_id:id,codigo:x.codigo,nombre:x.nombre,marca:x.marca||null,modelo:x.modelo||null,categoria:x.categoria||'Accesorios',descripcion:x.descripcion||null,precio_compra:Number(x.precio_compra||0),precio_venta:Number(x.precio_venta||0),unidad:x.unidad||'UND',datos_extra:x.datos_extra||{}})));if(r.error)throw r.error;return fresh.length}
async function checkpoint(id,page,count,total,state='PROCESANDO',err=null){const r=await supabaseClient.from('catalogos_pdf').update({paginas:total,paginas_procesadas:page,bloques_total:total,bloque_actual:page,productos_encontrados:count,estado:state,error_detalle:err}).eq('id',id);if(r.error)throw r.error}
function status(t){const e=document.querySelector('#cat4Progress');if(e)e.textContent=t}
async function processFile(file,id,type){const uid=(await user()).id,P=await pdfjs(),pdf=await P.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let total=0;const seen=new Set();await checkpoint(id,0,0,pdf.numPages);for(let n=1;n<=pdf.numPages;n++){status(`V5.8 · página ${n}/${pdf.numPages} · reconstruyendo filas · ${total}`);const page=await pdf.getPage(n);let items=[];try{items=await textItems(page)}catch(e){console.warn(e)}let rows=buildRows(items);let candidates=makeCandidates(rows,type,n);let image='',raw='';try{image=await render(page);raw=await ocr(image)}catch(e){console.warn('OCR',n,e)}if(!candidates.length&&raw){const ocrCodes=codes(raw);candidates=ocrCodes.map(code=>({codigo:code,nombre:'Producto para revisar',marca:'',modelo:code,categoria:'Accesorios',descripcion:'',precio_compra:0,precio_venta:0,unidad:'UND',datos_extra:{fuente:'OCR',pagina:n,tipo:type,precio_fuente:0,cantidad_paquete:1,presentacion:'UND',variante:'',confianza:'Revisión manual necesaria'}}))}if(candidates.length&&image)candidates=await enrich(image,type,n,raw,candidates);if(candidates.length)total+=await save(candidates,id,uid,seen);await checkpoint(id,n,total,pdf.numPages,'PROCESANDO');page.cleanup?.()}await checkpoint(id,pdf.numPages,total,pdf.numPages,'PROCESADO',total?'':'No se encontraron filas válidas');status(`✓ V5.8 terminado · ${total} productos/variantes. Revisa antes de inventario.`);await list()}
async function upload(file,type){if(running)return;running=true;try{if(!file||(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'))throw new Error('Selecciona un PDF.');if(file.size>95*1024*1024)throw new Error('El PDF supera 95 MB.');const u=await user();status('V5.8 · subiendo PDF…');const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await processFile(file,r.data.id,type)}catch(e){console.error(e);status(`Error V5.8: ${e.message||e}`);alert(`No se pudo procesar el catálogo.\n\n${e.message||e}`)}finally{running=false}}
async function reprocess(id,button){if(running)return;running=true;if(button){button.disabled=true;button.textContent='Procesando…'}try{const u=await user(),r=await supabaseClient.from('catalogos_pdf').select('tipo,archivo_path').eq('id',id).eq('user_id',u.id).single();if(r.error)throw r.error;const d=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(d.error)throw d.error;const del=await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',u.id);if(del.error)throw del.error;await processFile(new File([d.data],`catalogo-${id}.pdf`,{type:'application/pdf'}),id,r.data.tipo)}catch(e){console.error(e);status(`Error V5.8: ${e.message||e}`);alert(`No se pudo reprocesar el catálogo.\n\n${e.message||e}`)}finally{running=false;if(button){button.disabled=false;button.textContent='Releer catálogo'}}}
async function list(){const w=document.querySelector('#cat4List');if(!w)return;try{const u=await user(),r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toUpperCase();return`<article class="cat4-row"><div class="cat4-file">PDF</div><div class="cat4-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor · precio compra':'Mi catálogo · precio venta'} · ${c.paginas||'?'} páginas</span><small>${s==='PROCESADO'?'✓ Procesado':s==='PROCESANDO'?`⏳ Página ${c.paginas_procesadas||0}/${c.paginas||'?'} `:`⚠ ${esc(c.error_detalle||'Error')}`} · ${c.productos_encontrados||0} productos/variantes</small></div>${s==='PROCESADO'?`<button class="btn btn-secondary cat4-v5" data-id="${c.id}">Releer catálogo</button>`:`<button class="btn btn-secondary cat4-resume" data-id="${c.id}">${s==='ERROR'?'Reintentar':'Continuar'}</button>`}<button class="cat4-delete" data-id="${c.id}">×</button></article>`}).join('')||'<div class="cat4-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF para importar productos.</span></div>';w.querySelectorAll('.cat4-v5,.cat4-resume').forEach(b=>b.onclick=()=>reprocess(b.dataset.id,b));w.querySelectorAll('.cat4-delete').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este catálogo y sus productos detectados?'))return;const u=await user(),x=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',b.dataset.id).single();if(x.data?.archivo_path)await supabaseClient.storage.from(BUCKET).remove([x.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',b.dataset.id).eq('user_id',u.id);await supabaseClient.from('catalogos_pdf').delete().eq('id',b.dataset.id).eq('user_id',u.id);await list()})}catch(e){w.innerHTML=`<div class="cat4-empty">${esc(e.message)}</div>`}}
function hookInputs(){const own=document.querySelector('#cat4Own'),prov=document.querySelector('#cat4Prov');const bind=(el,type)=>{if(!el||el.dataset.v58)return;el.dataset.v58='1';el.addEventListener('change',e=>{e.stopImmediatePropagation();const f=e.target.files?.[0];if(f){window.__MARC_CATALOG_TYPE=type;upload(f,type)}},true)};bind(own,'PROPIO');bind(prov,'PROVEEDOR')}
const start=()=>{hookInputs();new MutationObserver(()=>hookInputs()).observe(document.body,{childList:true,subtree:true});setTimeout(list,600)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else setTimeout(start,250);window.MARC_REPROCESS_CATALOG=reprocess;window.MARC_V58_UPLOAD=upload;
})();
