/* M.A.R.C. — Catálogos PDF: propios y proveedores, procesamiento reanudable */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='inventory') return oldRender(section);
    const content=document.querySelector('#content'); if(!content)return;
    oldRender(section); setTimeout(injectCatalogPanel,0);
  };
  function injectCatalogPanel(){
    const page=document.querySelector('#content'); if(!page||document.querySelector('#catalogPanel'))return;
    const panel=document.createElement('section'); panel.id='catalogPanel'; panel.className='panel catalog-panel';
    panel.innerHTML=`<div class="catalog-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h2>Catálogos PDF</h2><p>Sube catálogos completos de tu empresa y de tus proveedores. M.A.R.C. los guarda por separado y extrae productos, códigos, marcas, modelos y precios.</p></div></div><div class="catalog-upload-grid"><label class="catalog-upload own"><input id="ownCatalogFile" type="file" accept="application/pdf,.pdf"><span class="catalog-upload-icon">📘</span><strong>Mi catálogo</strong><small>Catálogo propio de Tecnovigilancia Marc</small><b>Seleccionar PDF</b></label><label class="catalog-upload supplier"><input id="supplierCatalogFile" type="file" accept="application/pdf,.pdf"><span class="catalog-upload-icon">🏢</span><strong>Catálogo de proveedor</strong><small>Se almacena separado para comparar productos y precios</small><b>Seleccionar PDF</b></label></div><div id="catalogProgress" class="catalog-progress" hidden></div><div id="catalogList" class="catalog-list"><div class="catalog-loading">Cargando catálogos...</div></div>`;
    page.appendChild(panel); loadCatalogs();
    panel.querySelector('#ownCatalogFile').onchange=e=>handlePdf(e.target.files[0],'PROPIO');
    panel.querySelector('#supplierCatalogFile').onchange=e=>handlePdf(e.target.files[0],'PROVEEDOR');
  }
  async function getUser(){const {data:{user},error}=await supabaseClient.auth.getUser();if(error||!user)throw new Error('Tu sesión expiró.');return user;}
  function formatSize(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB';}
  function statusText(c){const estado=String(c.estado||'').toUpperCase();if(estado==='PROCESANDO'){const p=Number(c.paginas||0),done=Number(c.paginas_procesadas||0),b=Number(c.bloque_actual||0),bt=Number(c.bloques_total||0),n=Number(c.productos_encontrados||0);return `${p?`Página ${done}/${p}`:'Procesando'}${bt?` · bloque ${b}/${bt}`:''}${n?` · ${n} productos`:''}`;}if(estado==='PROCESADO')return `Procesado · ${Number(c.productos_encontrados||0)} productos`;if(estado==='ERROR')return `Error · ${c.error_detalle||'requiere reintento'}`;return estado;}
  async function loadCatalogs(){
    const wrap=document.querySelector('#catalogList'); if(!wrap)return;
    try{const user=await getUser();const {data,error}=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,proveedor,tamano_bytes,paginas,estado,created_at,paginas_procesadas,bloques_total,bloque_actual,productos_encontrados,error_detalle').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;const rows=data||[];
      if(!rows.length){wrap.innerHTML='<div class="catalog-empty"><div>📚</div><strong>Aún no tienes catálogos</strong><span>Sube un PDF arriba para crear tu biblioteca.</span></div>';return;}
      wrap.innerHTML=rows.map(c=>{const e=String(c.estado||'').toLowerCase();const resume=['procesando','error'].includes(e);return `<article class="catalog-row"><div class="catalog-file-icon">PDF</div><div class="catalog-row-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Catálogo propio'}${c.proveedor?' · '+esc(c.proveedor):''} · ${formatSize(c.tamano_bytes)}${c.paginas?' · '+c.paginas+' páginas':''}</span><small class="catalog-progress-text">${esc(statusText(c))}</small></div><mark class="catalog-status ${e}">${esc(c.estado)}</mark>${resume?`<button type="button" class="catalog-resume" data-id="${c.id}">▶ Continuar</button>`:''}<button type="button" class="table-action catalog-delete" data-id="${c.id}" title="Eliminar">×</button></article>`;}).join('');
      wrap.querySelectorAll('.catalog-delete').forEach(b=>b.onclick=()=>deleteCatalog(b.dataset.id));wrap.querySelectorAll('.catalog-resume').forEach(b=>b.onclick=()=>resumeCatalog(b.dataset.id));
    }catch(e){wrap.innerHTML=`<div class="catalog-empty">${esc(e.message)}</div>`;}
  }
  function setProgress(text){const el=document.querySelector('#catalogProgress');if(el){el.hidden=false;el.textContent=text;}}
  async function handlePdf(file,tipo){
    if(!file)return;if(file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name)){alert('Selecciona un archivo PDF.');return;}if(file.size>50*1024*1024){alert('El PDF supera el límite de 50 MB.');return;}
    try{const user=await getUser();setProgress(`Subiendo ${file.name} (${formatSize(file.size)})...`);const path=`${user.id}/${crypto.randomUUID()}.pdf`;const up=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const insert=await supabaseClient.from('catalogos_pdf').insert({user_id:user.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(insert.error){await supabaseClient.storage.from('catalog-pdfs').remove([path]);throw insert.error;}await processPdf(file,insert.data.id,tipo);await loadCatalogs();}
    catch(e){setProgress('Error: '+e.message);await loadCatalogs();}
  }
  async function readPdf(file,progress){
    if(!window.pdfjsLib)await loadPdfJs();const bytes=new Uint8Array(await file.arrayBuffer());const pdf=await window.pdfjsLib.getDocument({data:bytes}).promise;const chunks=[];let buffer='',startPage=1;
    for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const tc=await page.getTextContent();const text=tc.items.map(i=>i.str).join(' ').replace(/\s+/g,' ').trim();if(text){if(!buffer)startPage=p;buffer+=`\n[PÁGINA ${p}]\n${text}`;if(buffer.length>=7000){chunks.push({text:buffer,startPage,endPage:p});buffer='';}}if(progress)progress(`Leyendo PDF... página ${p} de ${pdf.numPages}`);}
    if(buffer.trim())chunks.push({text:buffer,startPage,endPage:pdf.numPages});return {pdf,chunks};
  }
  async function processPdf(file,catalogId,tipo){
    const progress=t=>setProgress(t);try{const {pdf,chunks}=await readPdf(file,progress);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,bloques_total:chunks.length,paginas_procesadas:0,bloque_actual:0,productos_encontrados:0,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',catalogId);if(!chunks.length)throw new Error('El PDF es escaneado o no contiene texto seleccionable. El análisis visual de PDFs escaneados será el siguiente bloque.');await processChunks(chunks,catalogId,tipo,0);}
    catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e),updated_at:new Date().toISOString()}).eq('id',catalogId);throw e;}
  }
  async function processChunks(chunks,catalogId,tipo,startIndex){
    const user=await getUser();let total=0;const existing=await supabaseClient.from('catalogos_pdf').select('productos_encontrados').eq('id',catalogId).eq('user_id',user.id).single();total=Number(existing.data?.productos_encontrados||0);
    for(let i=startIndex;i<chunks.length;i++){const ch=chunks[i];setProgress(`M.A.R.C. analizando bloque ${i+1} de ${chunks.length} · páginas ${ch.startPage}-${ch.endPage}`);await supabaseClient.from('catalogos_pdf').update({bloque_actual:i+1,paginas_procesadas:ch.endPage,updated_at:new Date().toISOString()}).eq('id',catalogId).eq('user_id',user.id);
      const r=await fetch('/api/analyze-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:ch.text,tipo})});let j={};try{j=await r.json();}catch{}if(!r.ok)throw new Error(j.error||j.detail||'No se pudo analizar el catálogo.');const items=Array.isArray(j.items)?j.items:[];
      if(items.length){const payload=items.map(x=>({user_id:user.id,catalogo_id:catalogId,codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:num(x.precio_compra),precio_venta:num(x.precio_venta),unidad:clean(x.unidad)||'UND',datos_extra:{origen:'PDF',tipo_fuente:tipo}}));const {error}=await supabaseClient.from('catalogo_items').insert(payload);if(error)throw error;total+=items.length;}
      await supabaseClient.from('catalogos_pdf').update({paginas_procesadas:ch.endPage,bloque_actual:i+1,productos_encontrados:total,updated_at:new Date().toISOString()}).eq('id',catalogId).eq('user_id',user.id);await loadCatalogs();
    }
    await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:chunks.length?chunks[chunks.length-1].endPage:0,bloque_actual:chunks.length,bloques_total:chunks.length,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',catalogId).eq('user_id',user.id);setProgress(`✓ Catálogo procesado: ${total} productos encontrados.`);
  }
  async function resumeCatalog(id){
    const progress=t=>setProgress(t);try{const user=await getUser();const {data:c,error}=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,archivo_path,estado,bloques_total,bloque_actual').eq('id',id).eq('user_id',user.id).single();if(error)throw error;setProgress(`Reanudando ${c.nombre}...`);const signed=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(signed.error)throw signed.error;const res=await fetch(signed.data.signedUrl);if(!res.ok)throw new Error('No se pudo recuperar el PDF almacenado.');const blob=await res.blob();const file=new File([blob],c.nombre,{type:'application/pdf'});const {pdf,chunks}=await readPdf(file,progress);if(!chunks.length)throw new Error('El PDF es escaneado o no contiene texto seleccionable.');const start=Math.max(0,Number(c.bloque_actual||0));await supabaseClient.from('catalogos_pdf').update({estado:'PROCESANDO',error_detalle:null,paginas:pdf.numPages,bloques_total:chunks.length,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);await processChunks(chunks,id,c.tipo,start);await loadCatalogs();}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',error_detalle:String(e.message||e),updated_at:new Date().toISOString()}).eq('id',id);setProgress('Error: '+e.message);await loadCatalogs();}
  }
  const clean=v=>{const s=String(v??'').trim();return s||null};const num=v=>{const n=Number(String(v??'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
  function loadPdfJs(){return new Promise((resolve,reject)=>{if(window.pdfjsLib)return resolve();const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=()=>window.pdfjsLib?resolve():reject(new Error('No se pudo cargar el lector PDF.'));s.onerror=()=>reject(new Error('No se pudo cargar el lector PDF.'));document.head.appendChild(s);});}
  async function deleteCatalog(id){if(!confirm('¿Eliminar este catálogo y los datos extraídos?'))return;try{const user=await getUser();const {data,error}=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).eq('user_id',user.id).single();if(error)throw error;await supabaseClient.storage.from('catalog-pdfs').remove([data.archivo_path]);const r=await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',user.id);if(r.error)throw r.error;loadCatalogs();}catch(e){alert(e.message);}}
  const style=document.createElement('style');style.textContent='.catalog-panel{margin-top:16px}.catalog-head h2{margin:0;color:#173b62;font-size:20px}.catalog-head p:last-child{margin:5px 0 15px;color:#7891ad;font-size:11px;max-width:760px}.catalog-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.catalog-upload{position:relative;min-height:145px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;cursor:pointer;transition:.2s}.catalog-upload:hover{border-color:#087cf5;transform:translateY(-1px)}.catalog-upload input{position:absolute;inset:0;opacity:0;cursor:pointer}.catalog-upload-icon{font-size:28px;margin-bottom:7px}.catalog-upload strong{font-size:15px;color:#234b73}.catalog-upload small{font-size:10px;color:#7891ad;margin:4px 0 12px}.catalog-upload b{font-size:10px;color:#087cf5}.catalog-progress{margin-top:12px;padding:12px;border-radius:10px;background:#edf7ff;color:#326080;font-size:11px}.catalog-list{margin-top:15px;display:grid;gap:8px}.catalog-row{display:flex;align-items:center;gap:11px;border:1px solid #e0eaf3;border-radius:12px;padding:10px;background:#fff}.catalog-file-icon{width:42px;height:42px;border-radius:10px;background:#edf5fc;color:#087cf5;display:grid;place-items:center;font-size:10px;font-weight:800}.catalog-row-main{flex:1;min-width:0;display:grid;gap:3px}.catalog-row-main strong{font-size:12px;color:#234b73;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.catalog-row-main span,.catalog-progress-text{font-size:9px;color:#7891ad}.catalog-progress-text{color:#087cf5}.catalog-status{font-size:9px;padding:4px 7px;border-radius:8px;background:#e9f8ef;color:#237445}.catalog-status.procesando{background:#fff4df;color:#9a6500}.catalog-status.error{background:#ffecef;color:#b33b4c}.catalog-empty{padding:30px;text-align:center;color:#7891ad;font-size:11px;display:grid;gap:5px}.catalog-empty div{font-size:30px}.catalog-empty strong{color:#365a7e;font-size:14px}.catalog-loading{text-align:center;padding:20px;color:#7891ad;font-size:10px}.catalog-resume{border:0;border-radius:8px;background:#eaf5ff;color:#087cf5;padding:7px 9px;font-size:9px;font-weight:700;white-space:nowrap}@media(max-width:650px){.catalog-upload-grid{grid-template-columns:1fr}.catalog-row{align-items:flex-start;flex-wrap:wrap}.catalog-status{margin-left:auto}.catalog-resume{margin-left:auto}}';document.head.appendChild(style);
})();