/* M.A.R.C. V8 — lector de catálogos corregido y optimizado
   PDF texto: parser determinista.
   PDF escaneado: /api/analyze-catalog-page (endpoint de catálogo, NO /api/analyze-product).
   Una llamada por página; rescate por 4 zonas solo si la página devuelve 0.
*/
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const money=v=>{let s=String(v??'').replace(/S\.?\/?/gi,'').replace(/[^0-9,.-]/g,'').trim();if(!s)return 0;if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const codeRe=/\b(?:AD|PRO|HIK|DS|IPC|DVR|NVR|CPE|TL|TP|UBNT|Ubiquiti)[-_][A-Z0-9][A-Z0-9._/-]*\b/gi;
const oldRender=window.render;
window.render=function(section='dashboard'){if(section!=='inventory')return oldRender(section);const c=document.querySelector('#content');if(!c)return;c.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>V8 · Lector documental optimizado. Texto sin IA; escaneados página por página con el lector de catálogos.</p></div></div><section class="panel pv8"><div class="pv8-grid"><label class="pv8-upload"><input id="pv8Own" type="file" accept="application/pdf,.pdf"><span>📘</span><strong>Mi catálogo</strong><small>Catálogo propio</small><b>Seleccionar PDF</b></label><label class="pv8-upload"><input id="pv8Supplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><strong>Catálogo de proveedor</strong><small>Se guarda separado</small><b>Seleccionar PDF</b></label></div><div id="pv8Progress" class="pv8-progress" hidden></div><div id="pv8List">Cargando...</div><div id="pv8Items" hidden></div></section>`;document.querySelector('#pv8Own').onchange=e=>upload(e.target.files[0],'PROPIO');document.querySelector('#pv8Supplier').onchange=e=>upload(e.target.files[0],'PROVEEDOR');load()};
function progress(t){const e=document.querySelector('#pv8Progress');if(e){e.hidden=false;e.textContent=t}}
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
async function pdfjs(){if(window.pdfjsLib)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=res;s.onerror=()=>rej(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
const size=n=>Number(n||0)<1048576?(Number(n||0)/1024).toFixed(1)+' KB':(Number(n||0)/1048576).toFixed(1)+' MB';
function status(c){const e=String(c.estado||'').toUpperCase(),p=Number(c.paginas||0),d=Number(c.paginas_procesadas||0),n=Number(c.productos_encontrados||0);if(e==='PROCESANDO')return `Leyendo ${d}/${p} · ${n} productos`;if(e==='PROCESADO')return `✓ Terminado · ${n} productos`;return `⚠ ${c.error_detalle||'requiere continuar'}`}
async function load(){const w=document.querySelector('#pv8List');if(!w)return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,tamano_bytes,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle,archivo_path').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>`<article class="pv8-row"><div class="pv8-icon">PDF</div><div class="pv8-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${size(c.tamano_bytes)} · ${c.paginas||0} páginas</span><small>${esc(status(c))}</small></div><button class="pv8-read" data-id="${c.id}">${String(c.estado).toUpperCase()==='PROCESADO'?'🔄 Releer V8':'▶ Continuar'}</button><button class="pv8-view" data-id="${c.id}">📦 Productos</button></article>`).join('')||'<div>No hay catálogos.</div>';w.querySelectorAll('.pv8-read').forEach(b=>b.onclick=()=>reprocess(b.dataset.id));w.querySelectorAll('.pv8-view').forEach(b=>b.onclick=()=>view(b.dataset.id))}catch(e){w.innerHTML=esc(e.message)}}
async function upload(file,tipo){if(!file)return;if(!/\.pdf$/i.test(file.name)){alert('Selecciona un PDF.');return}if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await user();progress(`⬆️ Subiendo ${file.name}...`);const path=`${u.id}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from('catalog-pdfs').remove([path]);throw r.error}await process(file,r.data.id,tipo,0,true);await load()}catch(e){progress('❌ '+e.message);await load()}}
async function stored(c){const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF');return new File([await r.blob()],c.nombre,{type:'application/pdf'})}
function rowsFromText(items){const rows=[];for(const it of items||[]){const s=clean(it.str);if(!s)continue;const y=Number(it.transform?.[5]||0);let row=rows.find(r=>Math.abs(r.y-y)<=4);if(!row){row={y,parts:[]};rows.push(row)}row.parts.push(s)}return rows.sort((a,b)=>b.y-a.y).map(r=>clean(r.parts.join(' '))).filter(Boolean)}
function parseRows(rows,pagina){const out=[];for(let i=0;i<rows.length;i++){const line=rows[i];codeRe.lastIndex=0;const cm=line.match(codeRe);if(!cm)continue;const code=cm[0];const idx=line.toUpperCase().indexOf(code.toUpperCase());let before=clean(line.slice(0,idx));let after=clean(line.slice(idx+code.length));const ms=[...after.matchAll(/(?:S\.?\/)?\s*\d+(?:[.,]\d{1,2})?(?!\d)/g)];let price=0;if(ms.length){const m=ms[ms.length-1];price=money(m[0]);after=clean(after.slice(0,m.index))}if(!price){const m=before.match(/(?:S\.?\/)?\s*\d+(?:[.,]\d{1,2})?\s*$/);if(m){price=money(m[0]);before=clean(before.slice(0,m.index))}}let name=before;if(!name){const prev=rows[i-1]||'';codeRe.lastIndex=0;if(prev&&!codeRe.test(prev))name=prev}if(!name)name=code;out.push({codigo:code,nombre:name,marca:'',modelo:code,categoria:'',descripcion:after,precio_compra:price,precio_venta:price,unidad:'UND',datos_extra:{pagina,origen:'PDF_TEXT'}})}return dedupe(out)}
function norm(x){return {codigo:clean(x?.codigo),nombre:clean(x?.nombre),marca:clean(x?.marca),modelo:clean(x?.modelo),categoria:clean(x?.categoria),descripcion:clean(x?.descripcion),precio_compra:money(x?.precio_compra),precio_venta:money(x?.precio_venta),unidad:clean(x?.unidad)||'UND',datos_extra:x?.datos_extra||{}}}
function dedupe(a){const out=[],seen=new Set();for(const raw of a||[]){const x=norm(raw);if(!x.codigo&&!x.nombre&&!x.modelo)continue;const k=(x.codigo+'|'+x.nombre).toUpperCase();if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
async function catalogVision(image,modo){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,modo})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.error||'El lector documental no pudo analizar la página');return Array.isArray(j.items)?j.items:[]}
async function renderImage(page,scale=1.5,crop=null){const base=page.getViewport({scale:1});const s=Math.min(scale,1800/Math.max(base.width,1));const v=page.getViewport({scale:s});const canvas=document.createElement('canvas');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:v}).promise;if(!crop)return canvas.toDataURL('image/jpeg',0.78);const y1=crop[0],y2=crop[1];const c=document.createElement('canvas');c.width=canvas.width;c.height=Math.max(1,Math.floor(canvas.height*(y2-y1)));c.getContext('2d').drawImage(canvas,0,Math.floor(canvas.height*y1),canvas.width,c.height,0,0,canvas.width,c.height);canvas.width=1;canvas.height=1;return c.toDataURL('image/jpeg',0.82)}
async function scanned(page,n){progress(`🧠 Página ${n} · lector documental...`);let all=[];try{all=await catalogVision(await renderImage(page,1.5),'pagina')}catch(e){progress(`⚠️ Página ${n} · reintentando...`)}all=dedupe(all);if(all.length)return all;for(let i=0;i<4;i++){progress(`🔎 Página ${n} · rescate ${i+1}/4...`);try{all.push(...await catalogVision(await renderImage(page,1.7,[i/4,(i+1)/4]),'zona'))}catch{}}return dedupe(all)}
async function process(file,id,tipo,start=0,reset=false){await pdfjs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,error_detalle:null}).eq('id',id);start=0}const q=await supabaseClient.from('catalogos_pdf').select('productos_encontrados,paginas_procesadas').eq('id',id).single();let total=Number(q.data?.productos_encontrados||0);if(!reset)start=Math.max(start,Number(q.data?.paginas_procesadas||0));for(let n=start+1;n<=pdf.numPages;n++){try{const page=await pdf.getPage(n);const tc=await page.getTextContent({normalizeWhitespace:true,disableCombineTextItems:false});const rows=rowsFromText(tc.items||[]);let items=parseRows(rows,n);let mode='PDF_TEXT';if(items.length===0){mode='OCR_CATALOG_PAGE';items=await scanned(page,n)}if(!items.length)throw Error('No se detectó ningún producto en la página.');const u=await user();items=dedupe(items).map(x=>({...x,datos_extra:{...(x.datos_extra||{}),pagina:n,tipo_fuente:tipo,lector:'V8'}}));const added=await save(items,id,u.id);total+=added;await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,estado:'PROCESANDO',error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✅ Página ${n}/${pdf.numPages} · +${added} · total ${total} · ${mode==='PDF_TEXT'?'texto':'OCR'}`)}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',paginas_procesadas:Math.max(0,n-1),productos_encontrados:total,error_detalle:`Página ${n}: ${e.message}`,updated_at:new Date().toISOString()}).eq('id',id);progress(`❌ Página ${n}: ${e.message}`);throw e}}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`🎉 Catálogo terminado · ${total} productos`)}
async function save(items,id,userId){const vals=dedupe(items).map(v=>({user_id:userId,catalogo_id:id,codigo:v.codigo,nombre:v.nombre,marca:v.marca,modelo:v.modelo,categoria:v.categoria,descripcion:v.descripcion,precio_compra:v.precio_compra,precio_venta:v.precio_venta,unidad:v.unidad,datos_extra:v.datos_extra||{}}));if(!vals.length)return 0;const codes=vals.map(x=>x.codigo).filter(Boolean);let existing=new Set();if(codes.length){const q=await supabaseClient.from('catalogo_items').select('codigo').eq('catalogo_id',id).in('codigo',codes);if(!q.error)(q.data||[]).forEach(x=>existing.add(String(x.codigo)))}const unique=vals.filter(x=>!x.codigo||!existing.has(String(x.codigo)));if(!unique.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(unique);if(r.error)throw r.error;return unique.length}
async function reprocess(id){const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;if(String(q.data.estado).toUpperCase()==='PROCESADO'&&!confirm('Se volverá a leer todo el PDF. ¿Continuar?'))return;await process(await stored(q.data),id,q.data.tipo,0,true);await load()}
async function view(id){const b=document.querySelector('#pv8Items');if(!b)return;b.hidden=false;const r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,categoria,precio_compra,precio_venta,unidad,datos_extra').eq('catalogo_id',id).order('created_at',{ascending:true});if(r.error){b.textContent=r.error.message;return}const a=r.data||[];b.innerHTML=`<div class="pv8-items"><button id="pv8Close">×</button><h3>${a.length} productos detectados</h3><div class="pv8-scroll"><table><thead><tr><th>Pág.</th><th>Código</th><th>Producto</th><th>Marca</th><th>Modelo</th><th>Precio</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.datos_extra?.pagina||'—')}</td><td>${esc(x.codigo||'')}</td><td>${esc(x.nombre||'')}</td><td>${esc(x.marca||'')}</td><td>${esc(x.modelo||'')}</td><td>S/ ${Number(x.precio_venta||x.precio_compra||0).toFixed(2)}</td></tr>`).join('')}</tbody></table></div></div>`;b.querySelector('#pv8Close').onclick=()=>b.hidden=true}
const st=document.createElement('style');st.textContent='.pv8{margin-top:16px}.pv8-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pv8-upload{position:relative;min-height:145px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;justify-content:center;cursor:pointer}.pv8-upload input{position:absolute;inset:0;opacity:0}.pv8-upload span{font-size:28px}.pv8-upload strong{font-size:16px;color:#234b73}.pv8-upload small{color:#71869b;margin:5px 0}.pv8-upload b{color:#087cf5}.pv8-progress{margin:14px 0;padding:14px;border-radius:14px;background:#edf7ff;color:#214d72}.pv8-row{display:flex;align-items:center;gap:12px;padding:15px;margin:10px 0;border:1px solid #dce8f2;border-radius:16px;background:#fff}.pv8-icon{width:58px;height:58px;border-radius:14px;background:#edf6ff;color:#087cf5;font-weight:800;display:grid;place-items:center}.pv8-main{flex:1;min-width:0}.pv8-main strong,.pv8-main span,.pv8-main small{display:block}.pv8-main strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pv8-main span,.pv8-main small{color:#71869b;margin-top:4px}.pv8-read,.pv8-view{border:0;border-radius:12px;padding:10px 12px;background:#edf6ff;color:#087cf5;font-weight:700}.pv8-items{margin-top:14px;position:relative}.pv8-items>button{float:right;border:0;background:#eee;border-radius:10px;font-size:22px}.pv8-scroll{overflow:auto}.pv8-scroll table{width:100%;border-collapse:collapse}.pv8-scroll th,.pv8-scroll td{padding:9px;border-bottom:1px solid #e5edf4;text-align:left;white-space:nowrap}@media(max-width:700px){.pv8-grid{grid-template-columns:1fr}.pv8-row{align-items:flex-start;flex-wrap:wrap}.pv8-main{width:calc(100% - 70px)}.pv8-read,.pv8-view{flex:1}.pv8-upload{min-height:125px}}';document.head.appendChild(st);
})();
