/* M.A.R.C. — Lector de catálogos por texto real del PDF */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=v=>{const s=String(v??'').trim();return s||null};
  const num=v=>{let s=String(v??'').replace(/[^0-9,.-]/g,'');if((s.match(/\./g)||[]).length>1)s=s.replace(/\.(?=.*\.)/g,'');s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='inventory')return oldRender(section);
    const content=document.querySelector('#content');if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>Lector de texto original: primero lee exactamente lo que contiene el PDF y después organiza los datos. Es el método recomendado para catálogos digitales con texto seleccionable.</p></div></div><section class="panel marc-text-reader"><div class="text-upload-grid"><label class="text-upload"><input id="textOwn" type="file" accept="application/pdf,.pdf"><span>📘</span><strong>Mi catálogo</strong><small>Catálogo propio</small><b>Seleccionar PDF</b></label><label class="text-upload"><input id="textSupplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><strong>Catálogo de proveedor</strong><small>Se guarda separado</small><b>Seleccionar PDF</b></label></div><div id="textProgress" class="text-progress" hidden></div><div id="textList">Cargando...</div><div id="textItems" hidden></div></section>`;
    document.querySelector('#textOwn').onchange=e=>upload(e.target.files[0],'PROPIO');
    document.querySelector('#textSupplier').onchange=e=>upload(e.target.files[0],'PROVEEDOR');
    load();
  };
  async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
  const progress=t=>{const e=document.querySelector('#textProgress');if(e){e.hidden=false;e.textContent=t}};
  const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
  function status(c){const e=String(c.estado||'').toUpperCase(),p=Number(c.paginas||0),d=Number(c.paginas_procesadas||0),n=Number(c.productos_encontrados||0);if(e==='PROCESANDO')return `Página ${d}/${p}${n?' · '+n+' productos':''}`;if(e==='PROCESADO')return `Procesado · ${n} productos`;return `Error · ${c.error_detalle||'requiere reintento'}`}
  async function load(){const w=document.querySelector('#textList');if(!w)return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,tamano_bytes,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle,archivo_path').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;const rows=r.data||[];w.innerHTML=rows.length?rows.map(c=>{const e=String(c.estado||'').toLowerCase();return `<article class="text-row"><div class="text-icon">PDF</div><div class="text-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${size(c.tamano_bytes)} · ${c.paginas||0} páginas</span><small>${esc(status(c))}</small></div><mark>${esc(c.estado||'')}</mark>${e==='procesado'?`<button class="text-reprocess" data-id="${c.id}">📖 Leer PDF de nuevo</button><button class="text-view" data-id="${c.id}">📦 Ver productos</button>`:''}${e==='error'||e==='procesando'?`<button class="text-resume" data-id="${c.id}">▶ Continuar</button>`:''}<button class="text-delete" data-id="${c.id}">×</button></article>`}).join(''):'<div class="text-empty">📚 No hay catálogos.</div>';w.querySelectorAll('.text-reprocess').forEach(b=>b.onclick=()=>reprocess(b.dataset.id));w.querySelectorAll('.text-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.text-view').forEach(b=>b.onclick=()=>showItems(b.dataset.id));w.querySelectorAll('.text-delete').forEach(b=>b.onclick=()=>del(b.dataset.id));}catch(e){w.innerHTML=esc(e.message)}}
  async function pdfjs(){if(window.pdfjsLib)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=res;s.onerror=()=>rej(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
  async function upload(file,tipo){if(!file)return;if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await user();const path=`${u.id}/${crypto.randomUUID()}.pdf`;progress(`⬆️ Subiendo ${file.name}...`);let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error)throw r.error;await process(file,r.data.id,tipo,0,true);await load()}catch(e){progress('❌ '+e.message);await load()}}
  async function stored(c){const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF');return new File([await r.blob()],c.nombre,{type:'application/pdf'})}
  function pageText(items){const a=(items||[]).filter(x=>String(x.str||'').trim());a.sort((x,y)=>{const ay=Number(y.transform?.[5]||0),by=Number(x.transform?.[5]||0);if(Math.abs(ay-by)>3)return ay-by;return Number(x.transform?.[4]||0)-Number(y.transform?.[4]||0)});const lines=[];let line=[],lastY=null;for(const x of a){const y=Number(x.transform?.[5]||0);if(lastY!==null&&Math.abs(y-lastY)>3){if(line.length)lines.push(line.join(' ').replace(/\s+/g,' ').trim());line=[]}line.push(String(x.str));lastY=y}if(line.length)lines.push(line.join(' ').replace(/\s+/g,' ').trim());return lines.filter(Boolean).join('\n')}
  function chunks(text,max=7000){const lines=String(text||'').split('\n'),out=[];let cur='';for(const line of lines){if(cur&&cur.length+line.length+1>max){out.push(cur);cur=''}cur+=(cur?'\n':'')+line}if(cur)out.push(cur);return out}
  async function analyze(text,pagina){const parts=chunks(text),all=[];for(let i=0;i<parts.length;i++){progress(`🧠 Página ${pagina}: organizando bloque ${i+1}/${parts.length}...`);const r=await fetch('/api/analyze-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:parts[i],pagina,tipo:'TEXTO_PDF'})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.error||'La IA no pudo organizar el texto');if(Array.isArray(j.items))all.push(...j.items)}return all}
  async function process(file,id,tipo,start=0,reset=false){await pdfjs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,error_detalle:null}).eq('id',id)}let q=await supabaseClient.from('catalogos_pdf').select('productos_encontrados').eq('id',id).single();let total=Number(q.data?.productos_encontrados||0);for(let n=start+1;n<=pdf.numPages;n++){try{progress(`📖 Leyendo exactamente el texto · página ${n}/${pdf.numPages}...`);const page=await pdf.getPage(n);const tc=await page.getTextContent({normalizeWhitespace:false,disableCombineTextItems:false});const text=pageText(tc.items);if(text.length<10)throw Error(`La página ${n} no tiene texto seleccionable. Este PDF es probablemente escaneado.`);const items=await analyze(text,n);const u=await user();const added=await save(items,id,u.id,tipo,n);total+=added;await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,estado:'PROCESANDO',updated_at:new Date().toISOString(),error_detalle:null}).eq('id',id)}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',paginas_procesadas:Math.max(0,n-1),productos_encontrados:total,error_detalle:`Página ${n}: ${e.message}`,updated_at:new Date().toISOString()}).eq('id',id);progress(`❌ Página ${n}: ${e.message}`);throw e}}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ Lectura del PDF terminada: ${total} productos encontrados.`)}
  async function save(items,id,userId,tipo,pagina){const vals=[],seen=new Set();for(const x of items||[]){const v={codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:num(x.precio_compra),precio_venta:num(x.precio_venta),unidad:clean(x.unidad)||'UND'};if(!v.codigo&&!v.modelo&&!v.nombre)continue;const key=(v.codigo||'')+'|'+(v.modelo||'')+'|'+(v.nombre||'');if(seen.has(key))continue;seen.add(key);vals.push({user_id:userId,catalogo_id:id,codigo:v.codigo,nombre:v.nombre,marca:v.marca,modelo:v.modelo,categoria:v.categoria,descripcion:v.descripcion,precio_compra:v.precio_compra,precio_venta:v.precio_venta,unidad:v.unidad,datos_extra:{origen:'TEXTO_PDF',pagina,tipo_fuente:tipo}})}if(!vals.length)return 0;const codes=vals.map(x=>x.codigo).filter(Boolean);let existing=new Set();if(codes.length){const q=await supabaseClient.from('catalogo_items').select('codigo').eq('catalogo_id',id).in('codigo',codes);if(!q.error)(q.data||[]).forEach(x=>existing.add(String(x.codigo)))}const unique=vals.filter(x=>!x.codigo||!existing.has(String(x.codigo)));if(!unique.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(unique);if(r.error)throw r.error;return unique.length}
  async function reprocess(id){if(!confirm('Se borrarán los productos extraídos y se volverá a leer el texto original del PDF página por página. Este método prioriza exactitud. ¿Continuar?'))return;const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await process(await stored(q.data),id,q.data.tipo,0,true);await load()}
  async function resume(id){const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await process(await stored(q.data),id,q.data.tipo,Number(q.data.paginas_procesadas||0),false);await load()}
  async function showItems(id){const box=document.querySelector('#textItems');if(!box)return;box.hidden=false;const r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,categoria,precio_compra,precio_venta').eq('catalogo_id',id);const a=r.data||[];box.innerHTML=`<div class="text-items"><button id="textClose">×</button><h3>${a.length} productos detectados</h3>${a.map(x=>`<div><b>${esc(x.codigo||'—')}</b> ${esc(x.nombre||'Sin nombre')} · ${esc(x.marca||'')} ${esc(x.modelo||'')}</div>`).join('')}</div>`;box.querySelector('#textClose').onclick=()=>box.hidden=true}
  async function del(id){if(!confirm('¿Eliminar este catálogo?'))return;const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await supabaseClient.storage.from('catalog-pdfs').remove([q.data.archivo_path]);await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);await load()}
  const st=document.createElement('style');st.textContent='.marc-text-reader{margin-top:16px}.text-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.text-upload{position:relative;min-height:140px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;justify-content:center;cursor:pointer}.text-upload input{position:absolute;inset:0;opacity:0}.text-upload span{font-size:28px}.text-upload strong{font-size:15px;color:#234b73}.text-upload small,.text-row span,.text-row small{font-size:10px;color:#7891ad}.text-upload b{font-size:10px;color:#087cf5;margin-top:10px}.text-progress{margin-top:12px;padding:12px;border-radius:10px;background:#edf7ff;color:#326080;font-size:11px}.text-row{display:flex;align-items:center;gap:10px;border:1px solid #e0eaf3;border-radius:12px;padding:10px;background:#fff;margin-top:8px;flex-wrap:wrap}.text-icon{width:42px;height:42px;border-radius:10px;background:#edf5fc;color:#087cf5;display:grid;place-items:center;font-size:10px;font-weight:800}.text-main{flex:1;min-width:180px;display:grid;gap:3px}.text-main strong{font-size:12px;color:#234b73}.text-main small{color:#087cf5}.text-row mark{font-size:9px;padding:4px 7px;border-radius:8px;background:#e9f8ef;color:#237445}.text-row button{border:0;border-radius:9px;padding:8px 10px;background:#edf7ff;color:#087cf5;font-weight:700;font-size:10px}.text-row .text-reprocess{background:#fff1df;color:#956000}.text-row .text-delete{background:#f3f7fa}.text-items{margin-top:14px;padding:16px;border:1px solid #dbe8f2;border-radius:14px;background:#fff;max-height:500px;overflow:auto}.text-items>div{padding:7px;border-bottom:1px solid #edf2f6;font-size:10px}.text-items button{float:right;border:0;background:#eef5fb;border-radius:8px;padding:6px 10px}@media(max-width:650px){.text-upload-grid{grid-template-columns:1fr}.text-row{align-items:flex-start}}';document.head.appendChild(st);
})();