/* M.A.R.C. — OCR local avanzado para catálogos escaneados */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=v=>{const s=String(v??'').trim();return s||null};
  const num=v=>{const n=Number(String(v??'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='inventory')return oldRender(section);
    const content=document.querySelector('#content');if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>Analizador OCR avanzado para catálogos completos, incluidos PDFs escaneados.</p></div></div><section class="panel marc-ocr-panel"><div class="ocr-upload-grid"><label class="ocr-upload"><input id="ocrOwn" type="file" accept="application/pdf,.pdf"><span>📘</span><strong>Mi catálogo</strong><small>Catálogo propio</small><b>Seleccionar PDF</b></label><label class="ocr-upload"><input id="ocrSupplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><strong>Catálogo de proveedor</strong><small>Se guarda separado</small><b>Seleccionar PDF</b></label></div><div id="ocrProgress" class="ocr-progress" hidden></div><div id="ocrList">Cargando...</div><div id="ocrItems" hidden></div></section>`;
    document.querySelector('#ocrOwn').onchange=e=>upload(e.target.files[0],'PROPIO');
    document.querySelector('#ocrSupplier').onchange=e=>upload(e.target.files[0],'PROVEEDOR');
    load();
  };
  async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
  const progress=t=>{const e=document.querySelector('#ocrProgress');if(e){e.hidden=false;e.textContent=t}};
  const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
  function status(c){const e=String(c.estado||'').toUpperCase();const p=Number(c.paginas||0),d=Number(c.paginas_procesadas||0),n=Number(c.productos_encontrados||0);if(e==='PROCESANDO')return `Página ${d}/${p}${n?' · '+n+' productos':''}`;if(e==='PROCESADO')return `Procesado · ${n} productos`;return `Error · ${c.error_detalle||'requiere reintento'}`}
  async function load(){const w=document.querySelector('#ocrList');if(!w)return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,tamano_bytes,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle,archivo_path').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;const rows=r.data||[];w.innerHTML=rows.length?rows.map(c=>{const e=String(c.estado||'').toLowerCase();return `<article class="ocr-row"><div class="ocr-icon">PDF</div><div class="ocr-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${size(c.tamano_bytes)} · ${c.paginas||0} páginas</span><small>${esc(status(c))}</small></div><mark>${esc(c.estado||'')}</mark>${e==='procesado'?`<button class="ocr-reprocess" data-id="${c.id}">🔬 OCR avanzado</button><button class="ocr-view" data-id="${c.id}">📦 Ver productos</button>`:''}${e==='error'||e==='procesando'?`<button class="ocr-resume" data-id="${c.id}">▶ Continuar</button>`:''}<button class="ocr-delete" data-id="${c.id}">×</button></article>`}).join(''):'<div class="ocr-empty">📚 No hay catálogos.</div>';
      w.querySelectorAll('.ocr-reprocess').forEach(b=>b.onclick=()=>reprocess(b.dataset.id));w.querySelectorAll('.ocr-resume').forEach(b=>b.onclick=()=>resume(b.dataset.id));w.querySelectorAll('.ocr-view').forEach(b=>b.onclick=()=>showItems(b.dataset.id));w.querySelectorAll('.ocr-delete').forEach(b=>b.onclick=()=>del(b.dataset.id));
    }catch(e){w.innerHTML=esc(e.message)}}
  async function pdfjs(){if(window.pdfjsLib)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=()=>res();s.onerror=()=>rej(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
  async function tesseract(){if(window.Tesseract)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=()=>window.Tesseract?res():rej(Error('No se pudo cargar OCR'));s.onerror=()=>rej(Error('No se pudo cargar OCR'));document.head.appendChild(s)})}
  async function upload(file,tipo){if(!file)return;if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await user();const path=`${u.id}/${crypto.randomUUID()}.pdf`;progress(`⬆️ Subiendo ${file.name}...`);let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error)throw r.error;await process(file,r.data.id,tipo,0,true);await load()}catch(e){progress('❌ '+e.message);await load()}}
  async function stored(c){const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF');return new File([await r.blob()],c.nombre,{type:'application/pdf'})}
  async function process(file,id,tipo,start=0,reset=false){await pdfjs();await tesseract();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,error_detalle:null}).eq('id',id)}let q=await supabaseClient.from('catalogos_pdf').select('productos_encontrados').eq('id',id).single();let total=Number(q.data?.productos_encontrados||0);const worker=await window.Tesseract.createWorker('spa');try{for(let n=start+1;n<=pdf.numPages;n++){progress(`🔬 OCR página ${n}/${pdf.numPages}...`);const page=await pdf.getPage(n);const base=page.getViewport({scale:1});const scale=Math.min(2,1800/Math.max(base.width,1));const v=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:v}).promise;const ocr=await worker.recognize(canvas);const text=String(ocr?.data?.text||'').trim();if(text.length>15){progress(`🧠 Página ${n}/${pdf.numPages}: IA analiza OCR...`);const r=await fetch('/api/analyze-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,tipo})});const j=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(j.items)){const u=await user();const added=await save(j.items,id,u.id,tipo,n);total+=added;}}await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,estado:'PROCESANDO',updated_at:new Date().toISOString()}).eq('id',id);canvas.width=1;canvas.height=1;}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ OCR terminado: ${total} productos encontrados.`)}finally{await worker.terminate()}}
  async function save(items,id,userId,tipo,pagina){const vals=[];const seen=new Set();for(const x of items||[]){const v={codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:num(x.precio_compra),precio_venta:num(x.precio_venta),unidad:clean(x.unidad)||'UND'};if(!v.codigo&&!v.modelo&&!v.nombre)continue;const key=(v.codigo||'')+'|'+(v.modelo||'')+'|'+(v.nombre||'');if(seen.has(key))continue;seen.add(key);vals.push({user_id:userId,catalogo_id:id,codigo:v.codigo,nombre:v.nombre,marca:v.marca,modelo:v.modelo,categoria:v.categoria,descripcion:v.descripcion,precio_compra:v.precio_compra,precio_venta:v.precio_venta,unidad:v.unidad,datos_extra:{origen:'OCR',pagina,tipo_fuente:tipo}})}if(!vals.length)return 0;const codes=vals.map(x=>x.codigo).filter(Boolean);let existing=new Set();if(codes.length){const q=await supabaseClient.from('catalogo_items').select('codigo').eq('catalogo_id',id).in('codigo',codes);if(!q.error)(q.data||[]).forEach(x=>existing.add(String(x.codigo)))}const unique=vals.filter(x=>!x.codigo||!existing.has(String(x.codigo)));if(!unique.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(unique);if(r.error)throw r.error;return unique.length}
  async function reprocess(id){if(!confirm('Se borrarán los productos extraídos de este catálogo y se ejecutará OCR avanzado página por página. ¿Continuar?'))return;const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await process(await stored(q.data),id,q.data.tipo,0,true);await load()}
  async function resume(id){const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await process(await stored(q.data),id,q.data.tipo,Math.max(0,Number(q.data.paginas_procesadas||0)-1),false);await load()}
  async function showItems(id){const box=document.querySelector('#ocrItems');if(!box)return;box.hidden=false;const r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,categoria,precio_compra,precio_venta').eq('catalogo_id',id);const a=r.data||[];box.innerHTML=`<div class="ocr-items"><button id="ocrClose">×</button><h3>${a.length} productos detectados</h3>${a.map(x=>`<div><b>${esc(x.codigo||'—')}</b> ${esc(x.nombre||'Sin nombre')} · ${esc(x.marca||'')} ${esc(x.modelo||'')}</div>`).join('')}</div>`;box.querySelector('#ocrClose').onclick=()=>box.hidden=true}
  async function del(id){if(!confirm('¿Eliminar este catálogo?'))return;const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await supabaseClient.storage.from('catalog-pdfs').remove([q.data.archivo_path]);await supabaseClient.from('catalogos_pdf').delete().eq('id',id).eq('user_id',u.id);await load()}
  const st=document.createElement('style');st.textContent='.marc-ocr-panel{margin-top:16px}.ocr-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ocr-upload{position:relative;min-height:140px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;justify-content:center;cursor:pointer}.ocr-upload input{position:absolute;inset:0;opacity:0}.ocr-upload span{font-size:28px}.ocr-upload strong{font-size:15px;color:#234b73}.ocr-upload small,.ocr-row span,.ocr-row small{font-size:10px;color:#7891ad}.ocr-upload b{font-size:10px;color:#087cf5;margin-top:10px}.ocr-progress{margin-top:12px;padding:12px;border-radius:10px;background:#edf7ff;color:#326080;font-size:11px}.ocr-row{display:flex;align-items:center;gap:10px;border:1px solid #e0eaf3;border-radius:12px;padding:10px;background:#fff;margin-top:8px;flex-wrap:wrap}.ocr-icon{width:42px;height:42px;border-radius:10px;background:#edf5fc;color:#087cf5;display:grid;place-items:center;font-size:10px;font-weight:800}.ocr-main{flex:1;min-width:180px;display:grid;gap:3px}.ocr-main strong{font-size:12px;color:#234b73}.ocr-main small{color:#087cf5}.ocr-row mark{font-size:9px;padding:4px 7px;border-radius:8px;background:#e9f8ef;color:#237445}.ocr-row button{border:0;border-radius:9px;padding:8px 10px;background:#edf7ff;color:#087cf5;font-weight:700;font-size:10px}.ocr-row .ocr-reprocess{background:#fff1df;color:#956000}.ocr-row .ocr-delete{background:#f3f7fa}.ocr-items{margin-top:14px;padding:16px;border:1px solid #dbe8f2;border-radius:14px;background:#fff;max-height:500px;overflow:auto}.ocr-items>div{padding:7px;border-bottom:1px solid #edf2f6;font-size:10px}.ocr-items button{float:right;border:0;background:#eef5fb;border-radius:8px;padding:6px 10px}@media(max-width:650px){.ocr-upload-grid{grid-template-columns:1fr}.ocr-row{align-items:flex-start}}';document.head.appendChild(st);
})();