/* M.A.R.C. V5 — extractor de tablas PDF por texto + coordenadas */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=v=>{const s=String(v??'').replace(/\s+/g,' ').trim();return s||null};
  const num=v=>{let s=String(v??'').replace(/S\/?\s*/gi,'').replace(/[^0-9,.-]/g,'').trim();if(!s)return 0;if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='inventory')return oldRender(section);
    const content=document.querySelector('#content');if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / CATÁLOGOS</p><h1>Catálogos PDF</h1><p>V5 · Extractor de tablas. Lee texto y posiciones del PDF, reconstruye filas y columnas y usa IA solo para normalizar.</p></div></div><section class="panel marc-table-panel"><div class="table-upload-grid"><label class="table-upload"><input id="tableOwn" type="file" accept="application/pdf,.pdf"><span>📘</span><strong>Mi catálogo</strong><small>Catálogo propio</small><b>Seleccionar PDF</b></label><label class="table-upload"><input id="tableSupplier" type="file" accept="application/pdf,.pdf"><span>🏢</span><strong>Catálogo de proveedor</strong><small>Se guarda separado</small><b>Seleccionar PDF</b></label></div><div id="tableProgress" class="table-progress" hidden></div><div id="tableList">Cargando...</div><div id="tablePreview" hidden></div></section>`;
    document.querySelector('#tableOwn').onchange=e=>upload(e.target.files[0],'PROPIO');
    document.querySelector('#tableSupplier').onchange=e=>upload(e.target.files[0],'PROVEEDOR');
    load();
  };
  const progress=t=>{const e=document.querySelector('#tableProgress');if(e){e.hidden=false;e.textContent=t}};
  async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw Error('Tu sesión expiró.');return r.data.user}
  async function pdfjs(){if(window.pdfjsLib)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=res;s.onerror=()=>rej(Error('No se pudo cargar PDF.js'));document.head.appendChild(s)})}
  async function upload(file,tipo){if(!file)return;if(file.size>50*1024*1024){alert('El PDF supera 50 MB.');return}try{const u=await user();const path=`${u.id}/${crypto.randomUUID()}.pdf`;progress(`⬆️ Subiendo ${file.name}...`);let r=await supabaseClient.storage.from('catalog-pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:u.id,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error)throw r.error;await process(file,r.data.id,tipo,true);await load()}catch(e){progress('❌ '+e.message);await load()}}
  async function stored(c){const s=await supabaseClient.storage.from('catalog-pdfs').createSignedUrl(c.archivo_path,3600);if(s.error)throw s.error;const r=await fetch(s.data.signedUrl);if(!r.ok)throw Error('No se pudo recuperar el PDF');return new File([await r.blob()],c.nombre,{type:'application/pdf'})}
  async function load(){const w=document.querySelector('#tableList');if(!w)return;try{const u=await user();const r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,tamano_bytes,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle,archivo_path').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>`<article class="table-row"><div class="table-icon">PDF</div><div class="table-main"><strong>${esc(c.nombre)}</strong><span>${c.tipo==='PROVEEDOR'?'Proveedor':'Propio'} · ${((c.tamano_bytes||0)/1048576).toFixed(1)} MB · ${c.paginas||0} páginas</span><small>${esc(String(c.estado||''))} · ${c.productos_encontrados||0} productos · página ${c.paginas_procesadas||0}/${c.paginas||0}</small></div><button data-id="${c.id}" class="table-read">${String(c.estado).toUpperCase()==='PROCESADO'?'🔄 Releer V5':'▶ Continuar V5'}</button><button data-id="${c.id}" class="table-view">📦 Productos</button></article>`).join('')||'<div>No hay catálogos.</div>';w.querySelectorAll('.table-read').forEach(b=>b.onclick=()=>reprocess(b.dataset.id));w.querySelectorAll('.table-view').forEach(b=>b.onclick=()=>view(b.dataset.id))}catch(e){w.innerHTML=esc(e.message)}}
  function normalizeWords(items){return (items||[]).map(x=>({str:String(x.str||'').trim(),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0),w:Number(x.width||0),h:Number(x.height||0)})).filter(x=>x.str)}
  function makeRows(words){const rows=[];const tol=4;for(const w of words.sort((a,b)=>b.y-a.y||a.x-b.x)){let row=rows.find(r=>Math.abs(r.y-w.y)<=tol);if(!row){row={y:w.y,words:[]};rows.push(row)}row.words.push(w)}return rows.sort((a,b)=>b.y-a.y).map(r=>r.words.sort((a,b)=>a.x-b.x).map(w=>w.str).join(' ')).filter(s=>s.length>1)}
  function looksLikeProduct(s){const t=s.toLowerCase();if(/^(p[aá]gina|contenido|índice|indice|www\.|tel[eé]fono|email|correo|descripci[oó]n|producto|c[oó]digo|modelo|marca|precio)$/i.test(t))return false;return /\b[A-Z0-9][A-Z0-9._\/-]{2,}\b/.test(s)||/\b\d{2,}[.,]\d{2}\b/.test(s)||s.length>12}
  function candidateText(rows){return rows.filter(looksLikeProduct).join('\n')}
  async function aiNormalize(text){if(!text)return [];try{const r=await fetch('/api/analyze-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,18000)})});const j=await r.json();if(!r.ok)throw Error(j.detail||j.error||'Error IA');return Array.isArray(j.items)?j.items:[]}catch{return []}}
  async function process(file,id,tipo,reset){await pdfjs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reset){await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id);await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:pdf.numPages,bloque_actual:0,productos_encontrados:0,error_detalle:null}).eq('id',id)}let total=0;for(let n=1;n<=pdf.numPages;n++){try{progress(`📊 Extrayendo tabla · página ${n}/${pdf.numPages}...`);const page=await pdf.getPage(n);const tc=await page.getTextContent({normalizeWhitespace:false,disableCombineTextItems:false});const words=normalizeWords(tc.items);const rows=makeRows(words);let text=candidateText(rows);if(text.length<20)text=rows.join('\n');const items=await aiNormalize(text);const u=await user();const added=await save(items,id,u.id,tipo,n);total+=added;await supabaseClient.from('catalogos_pdf').update({paginas:pdf.numPages,estado:'PROCESANDO',paginas_procesadas:n,bloque_actual:n,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id)}catch(e){await supabaseClient.from('catalogos_pdf').update({estado:'ERROR',paginas_procesadas:n-1,productos_encontrados:total,error_detalle:`Página ${n}: ${e.message}`}).eq('id',id);throw e}}await supabaseClient.from('catalogos_pdf').update({estado:'PROCESADO',paginas_procesadas:pdf.numPages,bloque_actual:pdf.numPages,bloques_total:pdf.numPages,productos_encontrados:total,error_detalle:null,updated_at:new Date().toISOString()}).eq('id',id);progress(`✓ V5 terminada: ${total} productos.`)}
  async function save(items,id,userId,tipo,pagina){const vals=[],seen=new Set();for(const x of items||[]){const v={codigo:clean(x.codigo),nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo),categoria:clean(x.categoria),descripcion:clean(x.descripcion),precio_compra:num(x.precio_compra),precio_venta:num(x.precio_venta),unidad:clean(x.unidad)||'UND'};if(!v.codigo&&!v.nombre&&!v.modelo)continue;const key=(v.codigo||'')+'|'+(v.modelo||'')+'|'+(v.nombre||'');if(seen.has(key))continue;seen.add(key);vals.push({user_id:userId,catalogo_id:id,codigo:v.codigo,nombre:v.nombre,marca:v.marca,modelo:v.modelo,categoria:v.categoria,descripcion:v.descripcion,precio_compra:v.precio_compra,precio_venta:v.precio_venta,unidad:v.unidad,datos_extra:{origen:'PDF_TABLE_V5',pagina,tipo_fuente:tipo}})}if(!vals.length)return 0;const r=await supabaseClient.from('catalogo_items').insert(vals);if(r.error)throw r.error;return vals.length}
  async function reprocess(id){const u=await user();const q=await supabaseClient.from('catalogos_pdf').select('*').eq('id',id).eq('user_id',u.id).single();if(q.error)throw q.error;await process(await stored(q.data),id,q.data.tipo,true);await load()}
  async function view(id){const box=document.querySelector('#tablePreview');if(!box)return;box.hidden=false;const r=await supabaseClient.from('catalogo_items').select('codigo,nombre,marca,modelo,categoria,precio_compra,precio_venta,unidad').eq('catalogo_id',id).order('created_at',{ascending:true});const a=r.data||[];box.innerHTML=`<div class="table-items"><button id="closeV5">×</button><h3>${a.length} productos</h3><div class="table-scroll"><table><thead><tr><th>Código</th><th>Producto</th><th>Marca</th><th>Modelo</th><th>Precio</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.codigo||'')}</td><td>${esc(x.nombre||'')}</td><td>${esc(x.marca||'')}</td><td>${esc(x.modelo||'')}</td><td>${x.precio_venta||x.precio_compra?esc(String(x.precio_venta||x.precio_compra)):'—'}</td></tr>`).join('')}</tbody></table></div></div>`;box.querySelector('#closeV5').onclick=()=>box.hidden=true}
  const st=document.createElement('style');st.textContent='.marc-table-panel{margin-top:16px}.table-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.table-upload{position:relative;min-height:140px;border:1.5px dashed #b9d1e5;border-radius:16px;background:#f7fbff;padding:20px;display:flex;flex-direction:column;justify-content:center;cursor:pointer}.table-upload input{position:absolute;inset:0;opacity:0}.table-upload span{font-size:28px}.table-upload strong{font-size:15px;color:#234b73}.table-upload small{font-size:10px;color:#7891ad}.table-upload b{font-size:10px;color:#087cf5;margin-top:10px}.table-progress{margin-top:12px;padding:12px;border-radius:10px;background:#edf7ff;color:#326080;font-size:11px}.table-row{display:flex;align-items:center;gap:10px;border:1px solid #e0eaf3;border-radius:12px;padding:10px;background:#fff;margin-top:8px;flex-wrap:wrap}.table-icon{width:42px;height:42px;border-radius:10px;background:#edf5fc;color:#087cf5;display:grid;place-items:center;font-size:10px;font-weight:800}.table-main{flex:1;min-width:180px;display:grid;gap:3px}.table-main strong{font-size:12px;color:#234b73}.table-main span,.table-main small{font-size:10px;color:#7891ad}.table-row button{border:0;border-radius:9px;padding:8px 10px;background:#edf7ff;color:#087cf5;font-weight:700;font-size:10px}.table-items{margin-top:14px;padding:16px;border:1px solid #dbe8f2;border-radius:14px;background:#fff}.table-items button{float:right;border:0;background:#eef5fb;border-radius:8px;padding:6px 10px}.table-scroll{overflow:auto}.table-items table{width:100%;border-collapse:collapse;font-size:10px}.table-items th,.table-items td{padding:7px;border-bottom:1px solid #edf2f6;text-align:left;white-space:nowrap}@media(max-width:650px){.table-upload-grid{grid-template-columns:1fr}.table-row{align-items:flex-start}}';document.head.appendChild(st);
})();