/* M.A.R.C. — Motor V5.5: extracción controlada, sin duplicados ni invenciones */
(()=>{
'use strict';
const BUCKET='catalog-pdfs';let running=false;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const num=v=>{let s=String(v??'').replace(/[^0-9.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const cat=s=>{s=clean(s).toUpperCase();if(/AUDIFONO|AURICULAR|EARPHONE/.test(s))return'Audífonos';if(/CARGADOR/.test(s))return'Cargadores';if(/CABLE/.test(s))return'Cables';if(/MOUSE|TECLADO/.test(s))return'Periféricos';if(/SOPORTE/.test(s))return'Soportes';if(/ADAPTADOR|ADAPTER/.test(s))return'Adaptadores';if(/MICROFONO|MICRÓFONO/.test(s))return'Micrófonos';if(/PARLANTE|SPEAKER/.test(s))return'Parlantes';if(/MEMORIA|USB/.test(s))return'Memorias';if(/WATCH|RELOJ/.test(s))return'Smartwatch';if(/POWER BANK/.test(s))return'Power banks';return'Accesorios'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const codeRe=/\b(?:AD|PRO)(?:-[A-Z0-9]+)+\b/ig;
function codesIn(raw){const s=new Set();String(raw||'').replace(codeRe,m=>{s.add(m.toUpperCase());return m});return s}
function validName(name,code){const n=clean(name);if(n.length<3||/^producto\s+/i.test(n))return false;if(!/[A-Za-zÁÉÍÓÚÑáéíóúñ]/.test(n))return false;if(/^S\.?\/?\s*[0-9]/i.test(n)||/^(PRECIO|CÓDIGO|CODIGO|FOTO|NOMBRE|UNIDAD)$/i.test(n))return false;if(n.replace(new RegExp(code,'ig'),'').trim().length<2)return false;return true}
function validItem(x,allowed){const code=clean(x.codigo).toUpperCase();const price=num(x.precio_fuente);return /^(AD|PRO)-[A-Z0-9-]+$/.test(code)&&allowed.has(code)&&validName(x.nombre,code)&&price>0}
function heuristic(raw,type,page,allowed){const lines=String(raw||'').split(/\r?\n/).map(clean).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){codeRe.lastIndex=0;const m=codeRe.exec(lines[i]);if(!m)continue;const code=m[0].toUpperCase();if(!allowed.has(code))continue;const block=lines.slice(i,Math.min(lines.length,i+10));let price=0;for(const z of block){const ms=z.match(/(?:S\.?\/\.?\s*)?(\d{1,5}(?:[.,]\d{1,2}))(?!\d)/g)||[];for(const q of ms){const p=num(q);if(p>0&&p<100000)price=p}}if(!price)continue;let name=clean(lines[i].replace(code,''));if(!validName(name,code)){for(const z of block.slice(1,4)){if(validName(z,code)){name=z;break}}}if(!validName(name,code))continue;out.push({codigo:code,nombre:name,marca:/ALDEEPO/i.test(raw)?'Aldeepo':'',modelo:code,categoria:cat(name),descripcion:clean(block.slice(1,3).join(' ')),precio_compra:type==='PROVEEDOR'?price:0,precio_venta:type==='PROPIO'?price:0,unidad:'UND',datos_extra:{fuente:'OCR',pagina:page,tipo:type,precio_fuente:price,cantidad_paquete:1,presentacion:'UND',confianza:'OCR de respaldo'}})}return out}
async function ai(image,type,page,ocrText,allowed){const r=await fetch('/api/analyze-catalog-page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,tipo:type,pagina:page,ocr_text:String(ocrText||'').slice(0,16000),codigos_permitidos:[...allowed]})});const j=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(j.items))throw new Error(j.error||'IA no disponible');const out=[];const seen=new Set();for(const x of j.items){const code=clean(x.codigo).toUpperCase(),p=num(x.precio_fuente),q=Math.max(1,Number(x.cantidad_paquete||1)),pr=clean(x.presentacion)||(q>1?'CAJA':'UND');const item={codigo:code,nombre:clean(x.nombre),marca:clean(x.marca),modelo:clean(x.modelo)||code,categoria:clean(x.categoria)||cat(x.nombre),descripcion:clean(x.descripcion),precio_compra:type==='PROVEEDOR'?p:0,precio_venta:type==='PROPIO'?p:0,unidad:pr.toUpperCase()==='CAJA'||q>1?'CJ':clean(x.unidad)||'UND',datos_extra:{fuente:'IA visual + OCR',pagina:page,tipo:type,precio_fuente:p,cantidad_paquete:q,presentacion:pr,variante:clean(x.variante||''),unidad_precio:clean(x.unidad_precio||''),confianza:'IA visual + OCR'}};if(validItem(item,allowed)&&!seen.has(code)){seen.add(code);out.push(item)}}return out}
async function save(items,id,uid,seen){const fresh=items.filter(x=>{const k=x.codigo.toUpperCase();if(seen.has(k))return false;seen.add(k);return true});if(!fresh.length)return 0;const rows=fresh.map(x=>({user_id:uid,catalogo_id:id,codigo:x.codigo,nombre:x.nombre,marca:x.marca||null,modelo:x.modelo||null,categoria:x.categoria||'Accesorios',descripcion:x.descripcion||null,precio_compra:Number(x.precio_compra||0),precio_venta:Number(x.precio_venta||0),unidad:x.unidad||'UND',datos_extra:x.datos_extra||{}}));const r=await supabaseClient.from('catalogo_items').insert(rows);if(r.error)throw r.error;return rows.length}
function status(t){const e=document.querySelector('#cat4Progress');if(e)e.textContent=t}
async function checkpoint(id,page,count,total,state='PROCESANDO',err=null){const r=await supabaseClient.from('catalogos_pdf').update({paginas:total,paginas_procesadas:page,bloques_total:total,bloque_actual:page,productos_encontrados:count,estado:state,error_detalle:err}).eq('id',id);if(r.error)throw r.error}
async function processFile(file,id,type){const uid=(await user()).id,p=await pdfjs(),pdf=await p.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let total=0;const seen=new Set();await checkpoint(id,0,0,pdf.numPages);for(let n=1;n<=pdf.numPages;n++){status(`V5.5 · página ${n}/${pdf.numPages} · detectando códigos y productos · ${total}`);const page=await pdf.getPage(n);let raw='';try{raw=await nativeText(page)}catch{}let image='';try{image=await render(page);const o=await ocr(image);raw=(raw+'\n'+o).trim()}catch(e){console.warn('OCR página',n,e)}const allowed=codesIn(raw);let items=[];try{if(image&&allowed.size)items=await ai(image,type,n,raw,allowed)}catch(e){console.warn('IA página',n,e)}if(!items.length)items=heuristic(raw,type,n,allowed);if(items.length)total+=await save(items,id,uid,seen);await checkpoint(id,n,total,pdf.numPages,'PROCESANDO');page.cleanup?.()}await checkpoint(id,pdf.numPages,total,pdf.numPages,'PROCESADO',total?'':'No se encontraron productos válidos');status(`✓ V5.5 terminado · ${total} productos únicos. Revisa antes de inventario.`);await list()}
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const p=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=p;return p}
async function render(page){const b=page.getViewport({scale:1}),scale=Math.min(2.4,Math.max(1.6,2400/Math.max(b.width,1))),v=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const d=c.toDataURL('image/jpeg',.92);c.width=1;c.height=1;return d}
async function nativeText(page){const tc=await page.getTextContent({normalizeWhitespace:true});return(tc.items||[]).map(x=>String(x.str||'').trim()).filter(Boolean).join('\n')}
async function ocr(image){if(!window.Tesseract)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar el OCR local.'));document.head.appendChild(s)});const w=await window.Tesseract.createWorker('spa');try{const r=await w.recognize(image);return String(r?.data?.text||'')}finally{await w.terminate()}}
async function upload(file,type){if(running)return;running=true;try{if(!file||(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'))throw new Error('Selecciona un PDF.');if(file.size>95*1024*1024)throw new Error('El PDF supera 95 MB.');const uid=(await user()).id;status('V5.5 · subiendo PDF…');const path=`${uid}/${crypto.randomUUID()}.pdf`;let r=await supabaseClient.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;r=await supabaseClient.from('catalogos_pdf').insert({user_id:uid,nombre:file.name,tipo,archivo_path:path,tamano_bytes:file.size,estado:'PROCESANDO',paginas_procesadas:0,bloques_total:0,bloque_actual:0,productos_encontrados:0,error_detalle:null}).select('id').single();if(r.error){await supabaseClient.storage.from(BUCKET).remove([path]);throw r.error}await processFile(file,r.data.id,type)}catch(e){console.error(e);status(`Error V5.5: ${e.message||e}`);alert(`No se pudo procesar el catálogo.\n\n${e.message||e}`)}finally{running=false}}
async function reprocess(id,button){if(running)return;running=true;if(button){button.disabled=true;button.textContent='Procesando…'}try{const uid=(await user()).id,r=await supabaseClient.from('catalogos_pdf').select('tipo,archivo_path').eq('id',id).eq('user_id',uid).single();if(r.error)throw r.error;const d=await supabaseClient.storage.from(BUCKET).download(r.data.archivo_path);if(d.error)throw d.error;const del=await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',id).eq('user_id',uid);if(del.error)throw del.error;await processFile(new File([d.data],`catalogo-${id}.pdf`,{type:'application/pdf'}),id,r.data.tipo)}catch(e){console.error(e);status(`Error V5.5: ${e.message||e}`);alert(`No se pudo reprocesar el catálogo.\n\n${e.message||e}`)}finally{running=false;if(button){button.disabled=false;button.textContent='Releer catálogo'}}}
async function list(){const w=document.querySelector('#cat4List');if(!w)return;try{const u=await user(),r=await supabaseClient.from('catalogos_pdf').select('id,nombre,tipo,paginas,estado,paginas_procesadas,productos_encontrados,error_detalle').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;w.innerHTML=(r.data||[]).map(c=>{const s=String(c.estado||'').toUpperCase();return`<article class="cat4-row"><div class="cat4-file">PDF</div><div class="cat4-main"><b>${esc(c.nombre)}</b><span>${c.tipo==='PROVEEDOR'?'Proveedor · precio compra':'Mi catálogo · precio venta'} · ${c.paginas||'?'} páginas</span><small>${s==='PROCESADO'?'✓ Procesado':s==='PROCESANDO'?`⏳ Página ${c.paginas_procesadas||0}/${c.paginas||'?'} `:`⚠ ${esc(c.error_detalle||'Error')}`} · ${c.productos_encontrados||0} productos únicos</small></div>${s==='PROCESADO'?`<button class="btn btn-secondary cat4-v5" data-id="${c.id}">Releer catálogo</button>`:`<button class="btn btn-secondary cat4-resume" data-id="${c.id}">${s==='ERROR'?'Reintentar':'Continuar'}</button>`}<button class="cat4-delete" data-id="${c.id}">×</button></article>`}).join('')||'<div class="cat4-empty"><b>📚 No hay catálogos</b><span>Selecciona un PDF para importar productos.</span></div>';w.querySelectorAll('.cat4-v5,.cat4-resume').forEach(b=>b.onclick=()=>reprocess(b.dataset.id,b));w.querySelectorAll('.cat4-delete').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este catálogo y sus productos detectados?'))return;const u=await user(),x=await supabaseClient.from('catalogos_pdf').select('archivo_path').eq('id',b.dataset.id).single();if(x.data?.archivo_path)await supabaseClient.storage.from(BUCKET).remove([x.data.archivo_path]);await supabaseClient.from('catalogo_items').delete().eq('catalogo_id',b.dataset.id).eq('user_id',u.id);await supabaseClient.from('catalogos_pdf').delete().eq('id',b.dataset.id).eq('user_id',u.id);await list()})}catch(e){w.innerHTML=`<div class="cat4-empty">${esc(e.message)}</div>`}}
function hookInputs(){const own=document.querySelector('#cat4Own'),prov=document.querySelector('#cat4Prov');const bind=(el,type)=>{if(!el||el.dataset.v55)return;el.dataset.v55='1';el.addEventListener('change',e=>{e.stopImmediatePropagation();const f=e.target.files?.[0];if(f){window.__MARC_CATALOG_TYPE=type;upload(f,type)}},true)};bind(own,'PROPIO');bind(prov,'PROVEEDOR')}
const start=()=>{hookInputs();new MutationObserver(()=>hookInputs()).observe(document.body,{childList:true,subtree:true});setTimeout(list,600)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else setTimeout(start,250);window.MARC_REPROCESS_CATALOG=reprocess;window.MARC_V55_UPLOAD=upload;
})();
