/* M.A.R.C. — módulo Clientes */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='clients') return oldRender(section);
    const content=document.querySelector('#content'); if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Clientes</h1><p>Empresas y personas, listas para cotizaciones e informes.</p></div></div><div class="clients-kpis"><button class="client-kpi active" data-filter="all"><small>Total clientes</small><strong id="clientsKpiTotal">0</strong></button><button class="client-kpi" data-filter="RUC"><small>Empresas · RUC</small><strong id="clientsKpiRuc">0</strong></button><button class="client-kpi" data-filter="DNI"><small>Personas · DNI</small><strong id="clientsKpiDni">0</strong></button><button class="client-kpi" data-filter="contact"><small>Con contacto</small><strong id="clientsKpiContact">0</strong></button></div><section class="panel table-panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="clientsSearch" placeholder="Buscar por nombre, documento, contacto, teléfono o correo..."></div><button class="btn btn-primary" id="newClientBtn">＋ Nuevo cliente</button></div><div class="client-filters"><button type="button" class="client-filter active" data-filter="all">Todos</button><button type="button" class="client-filter" data-filter="RUC">Empresas</button><button type="button" class="client-filter" data-filter="DNI">Personas</button><button type="button" class="client-filter" data-filter="contact">Con contacto</button></div><div id="clientsTableWrap"><div class="clients-loading">Cargando clientes...</div></div></section>`;
    loadClients();
  };
  async function loadClients(){
    const wrap=document.querySelector('#clientsTableWrap'); if(!wrap)return;
    const {data:{user}}=await supabaseClient.auth.getUser();
    if(!user){wrap.innerHTML='<div class="clients-empty">Inicia sesión para ver tus clientes.</div>';return;}
    const {data,error}=await supabaseClient.from('clientes').select('id,tipo_documento,documento,nombre_razon_social,nombre_contacto,telefono,correo,direccion,notas').eq('user_id',user.id).order('nombre_razon_social',{ascending:true});
    if(error){wrap.innerHTML=`<div class="clients-empty">No se pudieron cargar los clientes.<br><small>${esc(error.message)}</small></div>`;return;}
    const rows=data||[];
    const count=(fn)=>rows.filter(fn).length;
    const setText=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=String(v)};
    setText('#clientsKpiTotal',rows.length);setText('#clientsKpiRuc',count(c=>String(c.tipo_documento).toUpperCase()==='RUC'));setText('#clientsKpiDni',count(c=>String(c.tipo_documento).toUpperCase()==='DNI'));setText('#clientsKpiContact',count(c=>Boolean(String(c.nombre_contacto||'').trim()||String(c.telefono||'').trim()||String(c.correo||'').trim())));
    let activeFilter='all';
    const matchesFilter=c=>activeFilter==='all'||(activeFilter==='contact'?(Boolean(String(c.nombre_contacto||'').trim()||String(c.telefono||'').trim()||String(c.correo||'').trim())):String(c.tipo_documento||'').toUpperCase()===activeFilter);
    const draw=()=>{
      const q=(document.querySelector('#clientsSearch')?.value||'').toLowerCase().trim();
      const list=rows.filter(c=>matchesFilter(c)&&[c.nombre_razon_social,c.documento,c.nombre_contacto,c.telefono,c.correo,c.direccion].some(v=>String(v||'').toLowerCase().includes(q)));
      if(!list.length){wrap.innerHTML='<div class="clients-empty"><div class="clients-empty-icon">♙</div><h3>No se encontraron clientes</h3><p>Prueba con otro criterio de búsqueda o registra un nuevo cliente.</p></div>';return;}
      wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Cliente / razón social</th><th>Documento</th><th>Contacto</th><th>Teléfono</th><th>Correo</th><th>Acciones</th></tr></thead><tbody>${list.map(c=>`<tr><td><strong>${esc(c.nombre_razon_social)}</strong></td><td><span class="client-doc-badge">${esc(c.tipo_documento)} ${esc(c.documento)}</span></td><td>${esc(c.nombre_contacto||'—')}</td><td>${esc(c.telefono||'—')}</td><td>${esc(c.correo||'—')}</td><td><button class="table-action client-edit" data-id="${c.id}">✎</button> <button class="table-action client-delete" data-id="${c.id}">×</button></td></tr>`).join('')}</tbody></table></div><div class="table-foot">Mostrando ${list.length} de ${rows.length} clientes</div>`;
      document.querySelectorAll('.client-edit').forEach(b=>b.addEventListener('click',()=>openClientModal(rows.find(c=>c.id===b.dataset.id))));
      document.querySelectorAll('.client-delete').forEach(b=>b.addEventListener('click',()=>deleteClient(b.dataset.id,rows)));
    };
    document.querySelector('#clientsSearch')?.addEventListener('input',draw);
    document.querySelectorAll('.client-filter,.client-kpi').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter||'all';document.querySelectorAll('.client-filter,.client-kpi').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));draw();}));
    const open=()=>openClientModal();document.querySelector('#newClientBtn')?.addEventListener('click',open);draw();
  }
  function openClientModal(c=null){
    document.querySelector('#clientModal')?.remove();
    const modal=document.createElement('div');modal.id='clientModal';modal.className='client-modal-backdrop';
    modal.innerHTML=`<div class="client-modal"><div class="client-modal-head"><div><p class="eyebrow">M.A.R.C. / CLIENTES</p><h2>${c?'Editar cliente':'Nuevo cliente'}</h2></div><button type="button" class="client-close">×</button></div><form id="clientForm" class="client-form"><div class="client-grid"><label>Tipo de documento<select name="tipo_documento"><option ${c?.tipo_documento==='RUC'?'selected':''}>RUC</option><option ${c?.tipo_documento==='DNI'?'selected':''}>DNI</option><option ${c?.tipo_documento==='CE'?'selected':''}>CE</option><option ${c?.tipo_documento==='OTRO'?'selected':''}>OTRO</option></select></label><label>Número de documento<input name="documento" required value="${esc(c?.documento)}" placeholder="20678901234"></label></div><label>Nombre / razón social<input name="nombre_razon_social" required value="${esc(c?.nombre_razon_social)}" placeholder="Empresa o persona"></label><div class="client-grid"><label>Contacto<input name="nombre_contacto" value="${esc(c?.nombre_contacto)}"></label><label>Teléfono<input name="telefono" value="${esc(c?.telefono)}"></label></div><div class="client-grid"><label>Correo<input type="email" name="correo" value="${esc(c?.correo)}"></label><label>Dirección<input name="direccion" value="${esc(c?.direccion)}"></label></div><label>Notas<textarea name="notas" rows="3">${esc(c?.notas)}</textarea></label><div class="client-modal-actions"><button type="button" class="btn btn-secondary client-cancel">Cancelar</button><button type="submit" class="btn btn-primary">${c?'Guardar cambios':'Guardar cliente'}</button></div><div id="clientFormMsg" class="client-form-msg"></div></form></div>`;
    document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.client-close').onclick=close;modal.querySelector('.client-cancel').onclick=close;
    modal.querySelector('#clientForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,msg=modal.querySelector('#clientFormMsg'),btn=form.querySelector('button[type="submit"]');if(btn)btn.disabled=true;try{const {data:{user},error:userError}=await supabaseClient.auth.getUser();if(userError||!user)throw new Error('Tu sesión no está disponible. Cierra sesión y vuelve a ingresar.');const fd=new FormData(form),documento=String(fd.get('documento')||'').trim(),nombre=String(fd.get('nombre_razon_social')||'').trim();if(!documento||!nombre)throw new Error('Completa el documento y el nombre o razón social.');const payload={tipo_documento:String(fd.get('tipo_documento')||'RUC'),documento,nombre_razon_social:nombre,nombre_contacto:String(fd.get('nombre_contacto')||'').trim()||null,telefono:String(fd.get('telefono')||'').trim()||null,correo:String(fd.get('correo')||'').trim()||null,direccion:String(fd.get('direccion')||'').trim()||null,notas:String(fd.get('notas')||'').trim()||null,updated_at:new Date().toISOString()};let result;if(c)result=await supabaseClient.from('clientes').update(payload).eq('id',c.id).eq('user_id',user.id).select('id').single();else result=await supabaseClient.from('clientes').insert({...payload,user_id:user.id}).select('id').single();if(result.error){if(result.error.code==='23505')throw new Error('Ya existe otro cliente con ese tipo y número de documento.');throw result.error;}close();loadClients();}catch(err){msg.textContent=err?.message||'No se pudo guardar el cliente.';msg.className='client-form-msg error';}finally{if(btn)btn.disabled=false;}});
  }
  async function deleteClient(id,rows){const c=rows.find(x=>x.id===id);if(!c)return;if(!window.confirm(`¿Eliminar a ${c.nombre_razon_social}?`))return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {error}=await supabaseClient.from('clientes').delete().eq('id',id).eq('user_id',user.id);if(error)window.alert(error.message);else loadClients();}
  const s=document.createElement('style');s.textContent='.clients-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.client-kpi{border:1px solid #d9e6f1;background:#fff;border-radius:14px;padding:14px 16px;text-align:left;cursor:pointer;box-shadow:0 4px 15px #153a5c08}.client-kpi.active{border-color:#8cc7ff;box-shadow:0 0 0 2px #087cf51a}.client-kpi small{display:block;color:#6f87a1;font-size:10px;font-weight:700}.client-kpi strong{display:block;color:#12365e;font-size:24px;margin-top:4px}.client-filters{display:flex;gap:7px;flex-wrap:wrap;margin:-3px 0 14px}.client-filter{border:1px solid #d4e2ed;background:#fff;color:#55718e;border-radius:9px;padding:7px 11px;font-size:10px;font-weight:700;cursor:pointer}.client-filter.active{background:#eaf5ff;border-color:#9acbfa;color:#087cf5}.client-doc-badge{display:inline-block;padding:4px 7px;border-radius:7px;background:#f0f6fb;color:#476681;font-size:10px;font-weight:700}.clients-loading,.clients-empty{padding:55px 20px;text-align:center;color:#7891ad;font-size:12px}.clients-empty-icon{width:64px;height:64px;margin:0 auto 12px;border-radius:18px;background:#eaf5ff;color:#087cf5;display:grid;place-items:center;font-size:27px}.clients-empty h3{margin:0 0 6px;color:#24496e;font-size:16px}.clients-empty p{margin:0 auto 15px}.client-modal-backdrop{position:fixed;inset:0;background:#071d38aa;backdrop-filter:blur(6px);z-index:100;display:grid;place-items:center;padding:18px}.client-modal{width:min(650px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:24px}.client-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.client-modal-head h2{margin:0;color:#102b54;font-size:23px}.client-close{border:0;background:#eef5fb;color:#557493;border-radius:9px;width:34px;height:34px;font-size:22px}.client-form{display:grid;gap:13px}.client-form label{display:grid;gap:6px;color:#536b89;font-size:11px;font-weight:700}.client-form input,.client-form select,.client-form textarea{width:100%;border:1px solid #d2e0ec;border-radius:10px;background:#f8fbfe;color:#173452;padding:11px;font-size:12px}.client-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.client-modal-actions{display:flex;justify-content:flex-end;gap:9px}.client-form-msg{min-height:17px;font-size:10px}.client-form-msg.error{color:#d13d4e}@media(max-width:700px){.clients-kpis{grid-template-columns:1fr 1fr}}@media(max-width:600px){.client-grid{grid-template-columns:1fr}.client-modal{padding:19px}}';document.head.appendChild(s);
})();