/* M.A.R.C. — módulo Clientes */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='clients') return oldRender(section);
    const content=document.querySelector('#content');
    if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Clientes</h1><p>Empresas y personas, listas para cotizaciones e informes.</p></div></div><section class="panel table-panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="clientsSearch" placeholder="Buscar cliente..."></div><button class="btn btn-primary" id="newClientBtn">＋ Nuevo cliente</button></div><div id="clientsTableWrap"><div class="clients-loading">Cargando clientes...</div></div></section>`;
    loadClients();
  };
  async function loadClients(){
    const wrap=document.querySelector('#clientsTableWrap');
    if(!wrap)return;
    const {data:{user}}=await supabaseClient.auth.getUser();
    if(!user){wrap.innerHTML='<div class="clients-empty">Inicia sesión para ver tus clientes.</div>';return;}
    const {data,error}=await supabaseClient.from('clientes').select('id,tipo_documento,documento,nombre_razon_social,nombre_contacto,telefono,correo,direccion,notas').eq('user_id',user.id).order('nombre_razon_social',{ascending:true});
    if(error){wrap.innerHTML=`<div class="clients-empty">No se pudieron cargar los clientes.<br><small>${esc(error.message)}</small></div>`;return;}
    const rows=data||[];
    const draw=list=>{
      if(!list.length){wrap.innerHTML='<div class="clients-empty"><div class="clients-empty-icon">♙</div><h3>No tienes clientes todavía</h3><p>Agrega tu primer cliente para comenzar.</p><button class="btn btn-primary" id="emptyNewClient">＋ Agregar cliente</button></div>';return;}
      wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Cliente / razón social</th><th>Documento</th><th>Contacto</th><th>Teléfono</th><th>Correo</th><th>Acciones</th></tr></thead><tbody>${list.map(c=>`<tr><td><strong>${esc(c.nombre_razon_social)}</strong></td><td>${esc(c.tipo_documento)} ${esc(c.documento)}</td><td>${esc(c.nombre_contacto||'—')}</td><td>${esc(c.telefono||'—')}</td><td>${esc(c.correo||'—')}</td><td><button class="table-action client-edit" data-id="${c.id}">✎</button> <button class="table-action client-delete" data-id="${c.id}">×</button></td></tr>`).join('')}</tbody></table></div><div class="table-foot">Mostrando ${list.length} de ${rows.length} clientes</div>`;
    };
    draw(rows);
    document.querySelector('#clientsSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();draw(rows.filter(c=>[c.nombre_razon_social,c.documento,c.nombre_contacto,c.telefono,c.correo].some(v=>String(v||'').toLowerCase().includes(q))));});
    const open=()=>openClientModal();document.querySelector('#newClientBtn')?.addEventListener('click',open);document.querySelector('#emptyNewClient')?.addEventListener('click',open);
    document.querySelectorAll('.client-edit').forEach(b=>b.addEventListener('click',()=>openClientModal(rows.find(c=>c.id===b.dataset.id))));
    document.querySelectorAll('.client-delete').forEach(b=>b.addEventListener('click',()=>deleteClient(b.dataset.id,rows)));
  }
  function openClientModal(c=null){
    document.querySelector('#clientModal')?.remove();
    const modal=document.createElement('div');modal.id='clientModal';modal.className='client-modal-backdrop';
    modal.innerHTML=`<div class="client-modal"><div class="client-modal-head"><div><p class="eyebrow">M.A.R.C. / CLIENTES</p><h2>${c?'Editar cliente':'Nuevo cliente'}</h2></div><button type="button" class="client-close">×</button></div><form id="clientForm" class="client-form"><div class="client-grid"><label>Tipo de documento<select name="tipo_documento"><option ${c?.tipo_documento==='RUC'?'selected':''}>RUC</option><option ${c?.tipo_documento==='DNI'?'selected':''}>DNI</option><option ${c?.tipo_documento==='CE'?'selected':''}>CE</option><option ${c?.tipo_documento==='OTRO'?'selected':''}>OTRO</option></select></label><label>Número de documento<input name="documento" required value="${esc(c?.documento)}" placeholder="20678901234"></label></div><label>Nombre / razón social<input name="nombre_razon_social" required value="${esc(c?.nombre_razon_social)}" placeholder="Empresa o persona"></label><div class="client-grid"><label>Contacto<input name="nombre_contacto" value="${esc(c?.nombre_contacto)}"></label><label>Teléfono<input name="telefono" value="${esc(c?.telefono)}"></label></div><div class="client-grid"><label>Correo<input type="email" name="correo" value="${esc(c?.correo)}"></label><label>Dirección<input name="direccion" value="${esc(c?.direccion)}"></label></div><label>Notas<textarea name="notas" rows="3">${esc(c?.notas)}</textarea></label><div class="client-modal-actions"><button type="button" class="btn btn-secondary client-cancel">Cancelar</button><button type="submit" class="btn btn-primary">${c?'Guardar cambios':'Guardar cliente'}</button></div><div id="clientFormMsg" class="client-form-msg"></div></form></div>`;
    document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.client-close').onclick=close;modal.querySelector('.client-cancel').onclick=close;
    modal.querySelector('#clientForm').addEventListener('submit',async e=>{e.preventDefault();const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const fd=new FormData(e.currentTarget);const payload={user_id:user.id,tipo_documento:fd.get('tipo_documento'),documento:String(fd.get('documento')).trim(),nombre_razon_social:String(fd.get('nombre_razon_social')).trim(),nombre_contacto:String(fd.get('nombre_contacto')).trim()||null,telefono:String(fd.get('telefono')).trim()||null,correo:String(fd.get('correo')).trim()||null,direccion:String(fd.get('direccion')).trim()||null,notas:String(fd.get('notas')).trim()||null,updated_at:new Date().toISOString()};const r=c?await supabaseClient.from('clientes').update(payload).eq('id',c.id).eq('user_id',user.id):await supabaseClient.from('clientes').insert(payload);if(r.error){const m=modal.querySelector('#clientFormMsg');m.textContent=r.error.message;m.className='client-form-msg error';return;}close();loadClients();});
  }
  async function deleteClient(id,rows){const c=rows.find(x=>x.id===id);if(!c)return;if(!window.confirm(`¿Eliminar a ${c.nombre_razon_social}?`))return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {error}=await supabaseClient.from('clientes').delete().eq('id',id).eq('user_id',user.id);if(error)window.alert(error.message);else loadClients();}
  const s=document.createElement('style');s.textContent='.clients-loading,.clients-empty{padding:55px 20px;text-align:center;color:#7891ad;font-size:12px}.clients-empty-icon{width:64px;height:64px;margin:0 auto 12px;border-radius:18px;background:#eaf5ff;color:#087cf5;display:grid;place-items:center;font-size:27px}.clients-empty h3{margin:0 0 6px;color:#24496e;font-size:16px}.clients-empty p{margin:0 auto 15px}.client-modal-backdrop{position:fixed;inset:0;background:#071d38aa;backdrop-filter:blur(6px);z-index:100;display:grid;place-items:center;padding:18px}.client-modal{width:min(650px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:24px}.client-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.client-modal-head h2{margin:0;color:#102b54;font-size:23px}.client-close{border:0;background:#eef5fb;color:#557493;border-radius:9px;width:34px;height:34px;font-size:22px}.client-form{display:grid;gap:13px}.client-form label{display:grid;gap:6px;color:#536b89;font-size:11px;font-weight:700}.client-form input,.client-form select,.client-form textarea{width:100%;border:1px solid #d2e0ec;border-radius:10px;background:#f8fbfe;color:#173452;padding:11px;font-size:12px}.client-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.client-modal-actions{display:flex;justify-content:flex-end;gap:9px}.client-form-msg{min-height:17px;font-size:10px}.client-form-msg.error{color:#d13d4e}@media(max-width:600px){.client-grid{grid-template-columns:1fr}.client-modal{padding:19px}}';document.head.appendChild(s);
})();
