/* M.A.R.C. — filtros rápidos + resumen financiero de cotizaciones */
(function(){
'use strict';
const sb=()=>window.supabaseClient;
const money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima'}).format(d)};
const clientName=q=>String(q?.cliente_snapshot?.nombre_razon_social||'Venta directa').trim()||'Venta directa';
const gain=q=>{const g=Number(q?.ganancia);if(Number.isFinite(g)&&q?.ganancia!==null&&q?.ganancia!==undefined)return g;const total=Number(q?.total||0),cost=Number(q?.costo_total||0);return cost>0?total-cost:0};
let rows=[];let busy=false;
function style(){if(document.getElementById('marc-resumen-style'))return;const s=document.createElement('style');s.id='marc-resumen-style';s.textContent=`
.marc-resumen-kpi{position:relative}.marc-resumen-kpi.gain small{color:#087a49!important}.marc-resumen-kpi.gain b{color:#087a49!important}.marc-resumen-kpi.margin{background:#f7fff9!important;border-color:#d2eedf!important}.marc-resumen-kpi.margin b{color:#087a49!important}.marc-resumen-sub{display:block;color:#7890a7;font-size:8px;font-weight:500;margin-top:2px}.marc-calendar-btn{border:1px solid #cdddea;border-radius:9px;background:#fff;color:#173b5d;padding:8px 10px;font-size:11px;font-weight:800;white-space:nowrap;cursor:pointer}.marc-calendar-btn:active{transform:translateY(1px)}.marc-date-control{display:flex;gap:6px;align-items:center}.marc-date-control input{min-width:0;flex:1}.marc-date-clear{border:1px solid #cdddea;border-radius:9px;background:#fff;color:#607c97;padding:8px 10px;font-weight:900;cursor:pointer}@media(max-width:520px){.marc-calendar-btn{width:100%}.marc-date-control{flex-wrap:wrap}.marc-date-control input{min-width:120px}}
`;document.head.appendChild(s)}
async function user(){const s=sb();if(!s)throw Error('Supabase no disponible');const r=await s.auth.getUser();if(r.error||!r.data?.user)throw Error('Sesión no disponible');return r.data.user}
async function load(){if(busy)return;busy=true;try{const u=await user();const r=await sb().from('cotizaciones').select('id,numero,total,costo_total,ganancia,created_at,cliente_snapshot,cliente_id,ubicacion').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;rows=r.data||[];refreshSummary()}catch(e){console.warn('MARC resumen cotizaciones',e)}finally{busy=false}}
function filtered(){const search=(document.querySelector('#marcQSearch')?.value||'').trim().toLowerCase();const day=document.querySelector('#marcQDay')?.value||'';const client=document.querySelector('#marcQClient')?.value||'all';return rows.filter(q=>{const name=clientName(q),txt=`${q.numero||''} ${q.id||''} ${name} ${q.ubicacion||''}`.toLowerCase();return(!search||txt.includes(search))&&(!day||dateKey(q.created_at)===day)&&(client==='all'||name===client)})}
function refreshSummary(){const root=document.querySelector('#qv3list .marc-q-report-root');if(!root)return;const r=filtered(),total=r.reduce((a,q)=>a+Number(q.total||0),0),g=r.reduce((a,q)=>a+gain(q),0),pct=total>0?g/total*100:0;let grid=root.querySelector('.marc-q-kpis');if(!grid)return;grid.querySelector('.marc-resumen-kpi')?.remove();grid.querySelector('.marc-resumen-margin')?.remove();const kg=document.createElement('div');kg.className='marc-q-kpi marc-resumen-kpi gain';kg.innerHTML=`<small>Ganancia total</small><b>${money(g)}</b><span class="marc-resumen-sub">Ganancia registrada</span>`;const km=document.createElement('div');km.className='marc-q-kpi marc-resumen-margin margin';km.innerHTML=`<small>% de ganancia</small><b>${pct.toLocaleString('es-PE',{minimumFractionDigits:1,maximumFractionDigits:1})}%</b><span class="marc-resumen-sub">Ganancia ÷ total cotizado</span>`;grid.appendChild(kg);grid.appendChild(km)}
function enhanceDate(){const day=document.querySelector('#marcQDay');if(!day||day.dataset.marcCalendar==='1')return;day.dataset.marcCalendar='1';const label=day.closest('label');if(!label)return;const wrap=document.createElement('div');wrap.className='marc-date-control';day.parentElement.insertBefore(wrap,day);wrap.appendChild(day);const btn=document.createElement('button');btn.type='button';btn.className='marc-calendar-btn';btn.textContent='📅 Elegir día';btn.onclick=()=>{if(typeof day.showPicker==='function'){try{day.showPicker();return}catch(_){}}day.focus()};const clear=document.createElement('button');clear.type='button';clear.className='marc-date-clear';clear.textContent='×';clear.title='Quitar fecha';clear.onclick=()=>{day.value='';day.dispatchEvent(new Event('input',{bubbles:true}));refreshSummary()};wrap.append(btn,clear)}
function hook(){const list=document.querySelector('#qv3list');if(!list||location.hash.replace(/^#/,'')!=='quotes')return;style();enhanceDate();refreshSummary()}
new MutationObserver(()=>setTimeout(hook,80)).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(()=>{if(location.hash.replace(/^#/,'')==='quotes'){load();hook()}},150));document.addEventListener('input',e=>{if(e.target.id==='marcQSearch'||e.target.id==='marcQDay')setTimeout(refreshSummary,20)});document.addEventListener('change',e=>{if(e.target.id==='marcQClient')setTimeout(refreshSummary,20)});setInterval(()=>{if(location.hash.replace(/^#/,'')==='quotes'){hook();if(rows.length===0)load()}},1500);setTimeout(()=>{style();load();hook()},900);
})();