/* M.A.R.C. — Cotizaciones V1: texto/voz, con/sin cliente, margen, IGV opcional y PDF */
(function(){
'use strict';
const sb=window.supabaseClient;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`S/ ${Number(n||0).toFixed(2)}`;
const uid=async()=>{const {data}=await sb.auth.getUser();return data?.user?.id||null};
let state={clients:[],products:[],services:[],items:[],client:null,igv:false,igvRate:18,logo:localStorage.getItem('marc_quote_logo')||'',number:'',voice:null};
function getItems(){return state.items.map(x=>({...x,qty:Math.max(0,Number(x.qty)||0),price:Math.max(0,Number(x.price)||0),cost:Math.max(0,Number(x.cost)||0)}))}
function totals(){let sub=getItems().reduce((a,x)=>a+x.qty*x.price,0),cost=getItems().reduce((a,x)=>a+x.qty*x.cost,0),tax=state.igv?sub*state.igvRate/100:0;return{sub,cost,tax,total:sub+tax,gain:sub-cost,margin:sub?((sub-cost)/sub*100):0}}
async function loadData(){
 const user=await uid(); if(!user)return;
 const [c,p,s]=await Promise.all([
  sb.from('clientes').select('*').eq('user_id',user).order('nombre',{ascending:true}),
  sb.from('productos').select('id,codigo,nombre,marca,modelo,unidad,precio_compra,precio_venta,stock,activo').eq('user_id',user).eq('activo',true).order('nombre'),
  sb.from('servicios').select('*').eq('user_id',user).order('nombre')
 ]);
 state.clients=c.data||[];state.products=p.data||[];state.services=s.data||[];
}
function renderQuotes(){
 window.render=window.render||function(){};
 loadData().then(()=>drawList());
}
function drawList(){
 const content=document.querySelector('#content'); if(!content)return;
 content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Cotizaciones</h1><p>Crea proformas con texto o voz, con o sin cliente, calcula tu ganancia y genera un PDF profesional.</p></div><button class="btn btn-primary" id="newQuote">＋ Nueva cotización</button></div>
 <div class="kpis"><div class="kpi blue"><span>▧</span><small>Cotizaciones</small><strong id="qCount">0</strong></div><div class="kpi green"><span>✓</span><small>Con cliente</small><strong>${state.clients.length}</strong></div><div class="kpi orange"><span>◈</span><small>Productos</small><strong>${state.products.length}</strong></div><div class="kpi purple"><span>⚙</span><small>IGV</small><strong>18%</strong></div></div>
 <section class="panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="qSearch" placeholder="Buscar cotización, cliente o número..."></div><button class="btn btn-secondary" id="qRefresh">↻ Actualizar</button></div><div id="qList"><div class="empty-state">Cargando cotizaciones…</div></div></section>`;
 document.querySelector('#newQuote').onclick=openEditor;document.querySelector('#qRefresh').onclick=loadQuotes;document.querySelector('#qSearch').oninput=()=>loadQuotes(document.querySelector('#qSearch').value);loadQuotes();
}
async function loadQuotes(search=''){
 const box=document.querySelector('#qList');if(!box)return;const user=await uid();if(!user)return;
 let q=sb.from('cotizaciones').select('*').eq('user_id',user).order('created_at',{ascending:false});if(search)q=q.or(`numero.ilike.%${search}%,cliente_nombre.ilike.%${search}%`);
 const {data,error}=await q;const rows=data||[];document.querySelector('#qCount').textContent=rows.length;if(error){box.innerHTML=`<div class="empty-state">Todavía no hay cotizaciones guardadas o falta crear la tabla <code>cotizaciones</code>.</div>`;return}
 box.innerHTML=rows.length?`<div class="table-scroll"><table><thead><tr><th>Número</th><th>Cliente</th><th>Fecha</th><th>Subtotal</th><th>IGV</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.numero||'—')}</strong></td><td>${esc(r.cliente_nombre||'Sin cliente')}</td><td>${esc((r.fecha||r.created_at||'').slice(0,10))}</td><td>${money(r.subtotal)}</td><td>${money(r.igv)}</td><td><strong>${money(r.total)}</strong></td><td><mark>${esc(r.estado||'BORRADOR')}</mark></td><td><button class="table-action" data-q="${esc(r.id)}">👁</button> <button class="table-action" data-p="${esc(r.id)}">PDF</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No hay cotizaciones todavía. Crea la primera.</div>';
 box.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>viewQuote(b.dataset.q));box.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>viewQuote(b.dataset.p,true));
}
function modal(html){document.querySelector('#marcQuoteModal')?.remove();const d=document.createElement('div');d.id='marcQuoteModal';d.className='marc-modal-backdrop';d.innerHTML=`<div class="marc-modal">${html}</div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.remove()});return d.querySelector('.marc-modal')}
function openEditor(){
 state.items=[];state.client=null;state.igv=false;state.igvRate=18;state.number='COT-'+Date.now().toString().slice(-6);
 const m=modal(`<div class="marc-q-head"><div><p class="eyebrow">NUEVA PROFORMA</p><h2>${state.number}</h2></div><button class="table-action" id="qClose">✕</button></div>
 <div class="q-grid"><section><label>Cliente (opcional)<select id="qClient"><option value="">Sin cliente</option>${state.clients.map(c=>`<option value="${esc(c.id)}">${esc(c.nombre||c.razon_social||c.nombre_completo||'Cliente')}</option>`).join('')}</select></label></section><section><label>Fecha<input id="qDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label></section></div>
 <section class="q-ai-box"><div><strong>⚡ Carga rápida por texto o voz</strong><p>Ej.: “3 cámaras Hikvision DS-2CD1027, 2 discos 1TB y mano de obra de instalación”.</p></div><div class="q-ai-actions"><button class="btn btn-secondary" id="qVoice">🎙 Dictar</button><button class="btn btn-secondary" id="qParse">✨ Interpretar texto</button></div><textarea id="qText" rows="3" placeholder="Escribe lo que necesitas cotizar…"></textarea><small id="qVoiceStatus"></small></section>
 <div class="q-toolbar"><button class="btn btn-secondary" id="qAddProduct">＋ Producto</button><button class="btn btn-secondary" id="qAddService">＋ Servicio</button><label class="q-igv"><input id="qIgv" type="checkbox"> Aplicar IGV</label><input id="qRate" type="number" value="18" min="0" max="100" step="0.01" title="Tasa IGV"> %</div>
 <div id="qItems"></div><div id="qTotals"></div>
 <div class="q-profit"><strong>💰 Ganancia estimada antes de terminar</strong><span id="qGain">S/ 0.00</span><small id="qMargin">Margen 0%</small></div>
 <div class="q-design"><strong>Diseño del PDF</strong><label><input type="file" id="qLogo" accept="image/*"> Logo opcional</label><button class="btn btn-secondary" id="qLogoClear">Quitar logo</button><span id="qLogoName">${state.logo?'Logo cargado':'Sin logo'}</span></div>
 <div class="marc-q-actions"><button class="btn btn-secondary" id="qCancel">Cancelar</button><button class="btn btn-secondary" id="qPreview">Vista previa PDF</button><button class="btn btn-primary" id="qSave">Guardar y generar PDF</button></div>`);
 m.querySelector('#qClose').onclick=m.closest('.marc-modal-backdrop').remove.bind(m.closest('.marc-modal-backdrop'));m.querySelector('#qCancel').onclick=()=>m.closest('.marc-modal-backdrop').remove();
 m.querySelector('#qAddProduct').onclick=()=>addPicker('producto');m.querySelector('#qAddService').onclick=()=>addPicker('servicio');m.querySelector('#qIgv').onchange=e=>{state.igv=e.target.checked;drawItems()};m.querySelector('#qRate').oninput=e=>{state.igvRate=Number(e.target.value)||0;drawItems()};m.querySelector('#qClient').onchange=e=>state.client=state.clients.find(x=>x.id===e.target.value)||null;
 m.querySelector('#qVoice').onclick=startVoice;m.querySelector('#qParse').onclick=parseText;m.querySelector('#qLogo').onchange=readLogo;m.querySelector('#qLogoClear').onclick=()=>{state.logo='';localStorage.removeItem('marc_quote_logo');m.querySelector('#qLogoName').textContent='Sin logo';};m.querySelector('#qPreview').onclick=()=>previewQuote(false);m.querySelector('#qSave').onclick=saveQuote;drawItems();
}
function addPicker(type){const arr=type==='producto'?state.products:state.services;const m=modal(`<h3>Agregar ${type}</h3><select id="pick">${arr.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)}${x.codigo?' — '+esc(x.codigo):''}</option>`).join('')}</select><div class="marc-q-actions"><button class="btn btn-secondary" id="pc">Cancelar</button><button class="btn btn-primary" id="pa">Agregar</button></div>`);m.querySelector('#pc').onclick=()=>m.closest('.marc-modal-backdrop').remove();m.querySelector('#pa').onclick=()=>{const id=m.querySelector('#pick').value,x=arr.find(a=>a.id===id);if(x){state.items.push({type,id,name:x.nombre||x.descripcion||'Servicio',code:x.codigo||'',qty:1,price:Number(type==='producto'?x.precio_venta:x.precio)||0,cost:Number(type==='producto'?x.precio_compra:0)||0,unit:x.unidad||'UND'});m.closest('.marc-modal-backdrop').remove();document.querySelector('#marcQuoteModal')?.querySelector('#qItems')&&drawItems()}}}
function drawItems(){const m=document.querySelector('#marcQuoteModal .marc-modal');if(!m)return;const items=getItems();m.querySelector('#qItems').innerHTML=items.length?`<div class="table-scroll"><table><thead><tr><th>Tipo</th><th>Producto / servicio</th><th>Cant.</th><th>P. unit.</th><th>Ganancia</th><th>Total</th><th></th></tr></thead><tbody>${items.map((x,i)=>{const gain=(x.price-x.cost)*x.qty;return `<tr><td>${x.type==='producto'?'Producto':'Servicio'}</td><td><strong>${esc(x.name)}</strong><small>${esc(x.code)}</small></td><td><input class="qi" data-i="${i}" type="number" min="0" step="0.01" value="${x.qty}"></td><td><input class="qp" data-i="${i}" type="number" min="0" step="0.01" value="${x.price.toFixed(2)}"></td><td>${money(gain)}</td><td><strong>${money(x.qty*x.price)}</strong></td><td><button class="table-action qdel" data-i="${i}">✕</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-state">Agrega productos o servicios.</div>';
 m.querySelectorAll('.qi').forEach(e=>e.oninput=()=>{state.items[Number(e.dataset.i)].qty=Number(e.value)||0;drawItems()});m.querySelectorAll('.qp').forEach(e=>e.oninput=()=>{state.items[Number(e.dataset.i)].price=Number(e.value)||0;drawItems()});m.querySelectorAll('.qdel').forEach(e=>e.onclick=()=>{state.items.splice(Number(e.dataset.i),1);drawItems()});const t=totals();m.querySelector('#qTotals').innerHTML=`<div class="q-total-grid"><span>Subtotal <b>${money(t.sub)}</b></span><span>IGV ${state.igv?'('+state.igvRate+'%)':'(no aplicado)'} <b>${money(t.tax)}</b></span><span class="grand">Total <b>${money(t.total)}</b></span></div>`;m.querySelector('#qGain').textContent=money(t.gain);m.querySelector('#qMargin').textContent=`Margen ${t.margin.toFixed(1)}% · Costo ${money(t.cost)}`;
}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Este navegador no permite reconocimiento de voz. Puedes usar el campo de texto.');return}const r=new SR();r.lang='es-PE';r.interimResults=true;r.continuous=false;const ta=document.querySelector('#qText'),st=document.querySelector('#qVoiceStatus');st.textContent='Escuchando…';r.onresult=e=>{ta.value=[...e.results].map(x=>x[0].transcript).join(' ')};r.onerror=()=>st.textContent='No se pudo reconocer el audio.';r.onend=()=>st.textContent='Listo. Revisa el texto antes de interpretar.';r.start();state.voice=r}
function parseText(){const text=document.querySelector('#qText')?.value.trim();if(!text)return alert('Escribe o dicta primero.');let added=0;const all=[...state.products.map(x=>({...x,__type:'producto'})),...state.services.map(x=>({...x,__type:'servicio'}))];all.forEach(x=>{const hay=(text+' '+(x.codigo||'')+' '+(x.nombre||'')).toLowerCase();if(hay.includes(String(x.codigo||'').toLowerCase())&&x.codigo){const m=text.match(new RegExp('(\\d+(?:[.,]\\d+)?)\\s*(?:x|unid|unidad|unidades)?\\s*[^,;]*'+x.codigo.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&'),'i'));state.items.push({type:x.__type,id:x.id,name:x.nombre,code:x.codigo,qty:m?Number(m[1].replace(',','.')):1,price:Number(x.__type==='producto'?x.precio_venta:x.precio)||0,cost:Number(x.__type==='producto'?x.precio_compra:0)||0,unit:x.unidad||'UND'});added++}});if(!added){const words=text.toLowerCase().split(/\s+/);all.forEach(x=>{const n=String(x.nombre||'').toLowerCase();if(n&&words.some(w=>w.length>4&&n.includes(w))){state.items.push({type:x.__type,id:x.id,name:x.nombre,code:x.codigo||'',qty:1,price:Number(x.__type==='producto'?x.precio_venta:x.precio)||0,cost:Number(x.__type==='producto'?x.precio_compra:0)||0,unit:x.unidad||'UND'});added++}})}drawItems();alert(added?`Se agregaron ${added} coincidencia(s). Revisa y corrige antes de guardar.`:'No encontré coincidencias exactas en tu catálogo. Agrega los productos manualmente.');}
function readLogo(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.logo=r.result;localStorage.setItem('marc_quote_logo',state.logo);document.querySelector('#qLogoName').textContent=f.name};r.readAsDataURL(f)}
async function saveQuote(){const user=await uid();if(!user)return;const t=totals();if(!state.items.length)return alert('Agrega al menos un producto o servicio.');const clientName=state.client?(state.client.nombre||state.client.razon_social||state.client.nombre_completo||'Cliente'):'';const payload={user_id:user,numero:state.number,fecha:document.querySelector('#qDate')?.value||new Date().toISOString().slice(0,10),cliente_id:state.client?.id||null,cliente_nombre:clientName,subtotal:t.sub,igv:t.tax,total:t.total,estado:'BORRADOR',observaciones:document.querySelector('#qText')?.value||'',datos_extra:{items:getItems(),igv_aplicado:state.igv,igv_tasa:state.igvRate,ganancia:t.gain,margen:t.margin,logo:state.logo||null}};const {data,error}=await sb.from('cotizaciones').insert(payload).select().single();if(error){alert('No se pudo guardar: '+error.message+'\n\nSi la tabla cotizaciones aún no existe, aplica el SQL de la siguiente migración.');return}previewQuote(true,data);loadQuotes()}
function quoteDoc(saved){const t=saved?{subtotal:saved.subtotal,igv:saved.igv,total:saved.total}:{...totals(),subtotal:totals().sub};const items=saved?.datos_extra?.items||getItems();const client=saved?.cliente_nombre||((state.client?.nombre||state.client?.razon_social)||'');return {number:saved?.numero||state.number,date:saved?.fecha||new Date().toISOString().slice(0,10),client,items,t,logo:saved?.datos_extra?.logo||state.logo,igvApplied:saved?.datos_extra?.igv_aplicado??state.igv,rate:saved?.datos_extra?.igv_tasa??state.igvRate};}
function previewQuote(saved=false,data=null){const q=quoteDoc(data);const rows=q.items.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b><small>${esc(x.code||'')}</small></td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(q.number)}</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;background:#f3f5f8}.page{max-width:850px;margin:30px auto;background:#fff;padding:44px;box-shadow:0 8px 30px #0001}.head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #087cf5;padding-bottom:22px}.logo{max-width:190px;max-height:80px;object-fit:contain}.brand{font-size:25px;font-weight:800}.muted{color:#667085}.client{margin:28px 0;padding:18px;background:#f7f9fc;border-radius:10px}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{padding:12px 9px;border-bottom:1px solid #e5e7eb;text-align:left}th{background:#f7f9fc}td:nth-child(3),td:nth-child(4),td:nth-child(5){text-align:right}small{display:block;color:#667085}.totals{margin:22px 0 0 auto;max-width:310px}.totals div{display:flex;justify-content:space-between;padding:8px}.grand{font-size:21px;font-weight:800;border-top:2px solid #172033;margin-top:7px;padding-top:12px}.foot{margin-top:45px;color:#667085;font-size:12px}@media print{body{background:white}.page{margin:0;box-shadow:none;max-width:none}}button{padding:10px 16px;border:0;border-radius:8px;background:#087cf5;color:white;font-weight:700;cursor:pointer}</style></head><body><div class="page"><div class="head"><div>${q.logo?`<img class="logo" src="${q.logo}" alt="Logo">`:'<div class="brand">M.A.R.C.</div>'}<div class="muted">COTIZACIÓN</div></div><div style="text-align:right"><b>${esc(q.number)}</b><br><span class="muted">Fecha: ${esc(q.date)}</span></div></div><div class="client"><b>Cliente</b><br>${esc(q.client||'Cotización sin cliente')}</div><table><thead><tr><th>#</th><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div>Subtotal <b>${money(q.t.subtotal)}</b></div>${q.igvApplied?`<div>IGV (${q.rate}%) <b>${money(q.t.igv)}</b></div>`:''}<div class="grand">TOTAL <b>${money(q.t.total)}</b></div></div><div class="foot">Cotización generada con M.A.R.C. · Precios sujetos a confirmación. ${saved?'':'Vista previa: revisa los datos antes de entregar.'}</div><button onclick="window.print()">Imprimir / Guardar como PDF</button></div></body></html>`;const w=window.open('','_blank');if(!w)return alert('Permite ventanas emergentes para generar el PDF.');w.document.write(html);w.document.close()}
async function viewQuote(id,pdf){const {data,error}=await sb.from('cotizaciones').select('*').eq('id',id).single();if(error)return alert(error.message);previewQuote(true,data)}
window.marcQuotes={openEditor,renderQuotes};
const oldRender=window.render;window.render=function(section){if(section==='quotes')return renderQuotes();return oldRender?oldRender(section):null};
const style=document.createElement('style');style.textContent=`.marc-modal-backdrop{position:fixed;inset:0;background:#0b122099;z-index:9999;display:grid;place-items:center;padding:18px}.marc-modal{background:#fff;border-radius:18px;max-width:1050px;width:min(100%,1050px);max-height:94vh;overflow:auto;padding:24px;box-shadow:0 25px 70px #0004}.marc-q-head{display:flex;justify-content:space-between;align-items:flex-start}.q-grid{display:grid;grid-template-columns:2fr 1fr;gap:14px}.q-grid label,.q-design label{display:flex;flex-direction:column;gap:7px;font-weight:700}.q-grid input,.q-grid select,.q-ai-box textarea,.q-toolbar input,.q-items input,.marc-modal select{padding:11px;border:1px solid #d7dce5;border-radius:9px}.q-ai-box{margin:18px 0;padding:16px;border:1px solid #dce6f7;background:#f7faff;border-radius:13px}.q-ai-box p{margin:5px 0 12px;color:#667085}.q-ai-actions{display:flex;gap:8px;flex-wrap:wrap}.q-ai-box textarea{width:100%;box-sizing:border-box;margin-top:10px}.q-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:16px 0}.q-igv{margin-left:auto;display:flex;gap:7px;align-items:center}.q-toolbar>input{width:55px}.q-profit{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin:18px 0;padding:17px;border-radius:12px;background:#eefaf3;border:1px solid #ccebd9}.q-profit span{font-size:23px;font-weight:800}.q-profit small{color:#167447}.q-design{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:16px;background:#f7f8fa;border-radius:12px}.q-total-grid{margin:15px 0 0 auto;max-width:400px}.q-total-grid span{display:flex;justify-content:space-between;padding:7px}.q-total-grid .grand{font-size:20px;border-top:2px solid #182230;margin-top:5px}.marc-q-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px;flex-wrap:wrap}.empty-state{text-align:center;padding:45px;color:#667085}.marc-modal mark{padding:4px 8px;border-radius:7px}.marc-modal td small{display:block;color:#667085}.marc-modal input{box-sizing:border-box}@media(max-width:700px){.q-grid{grid-template-columns:1fr}.q-igv{margin-left:0}.marc-modal{padding:16px}.q-toolbar{align-items:stretch}.q-toolbar .btn{flex:1}}`;document.head.appendChild(style);
})();
