/* M.A.R.C. — IA de cotizaciones: Whisper + Gemini, sin regex */
(function(){'use strict';
const API='/api/';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});let installed=false;
function msg(t){const e=document.getElementById('qv3voiceMsg');if(e)e.textContent=t}
function ctx(){return{clientes:[...document.querySelectorAll('#qv3client option')].filter(o=>o.value).map(o=>({id:o.value,nombre:o.textContent.split(' · ')[0],documento:o.textContent.split(' · ')[1]||''})),productos:[],servicios:[]}}
async function loadContext(){try{const sb=window.supabaseClient;if(!sb)return ctx();const u=(await sb.auth.getUser()).data?.user;if(!u)return ctx();const [p,s]=await Promise.all([sb.from('productos').select('id,codigo,nombre,marca,modelo,unidad,precio_compra,precio_venta,proveedor').eq('user_id',u.id).eq('activo',true).limit(3000),sb.from('servicios').select('id,codigo,nombre,categoria,unidad,precio').eq('user_id',u.id).eq('activo',true).limit(1000)]);const c=ctx();c.productos=p.data||[];c.servicios=s.data||[];return c}catch{return ctx()}}
function render(q){const modal=document.getElementById('qv3modal');if(!modal)return;const box=modal.querySelector('#qv3items');box.innerHTML=q.partidas.length?'<div class="table-scroll"><table><thead><tr><th>Tipo</th><th>Producto / servicio</th><th>Cant.</th><th>Precio</th><th>Importe</th></tr></thead><tbody>'+q.partidas.map((p,i)=>{const c=p.alcance_precio==='global'?1:Number(p.cantidad||1),im=Number(p.precio_unitario||0)*c;return `<tr data-ai-row="${i}" data-ai-scope="${esc(p.alcance_precio)}"><td>${esc(p.tipo)}</td><td><b>${esc(p.nombre)}</b><small>IA · ${esc(p.alcance_precio)}</small></td><td><input data-ai-qty="${i}" type="number" min="0.001" step="0.001" value="${c}"></td><td><input data-ai-price="${i}" type="number" min="0" step="0.01" value="${Number(p.precio_unitario||0).toFixed(2)}"></td><td>${money(im)}</td></tr>`}).join('')+'</tbody></table></div>':'<div class="empty-state">La IA no detectó partidas con precio suficiente.</div>';
function total(){let s=0;modal.querySelectorAll('[data-ai-row]').forEach(r=>{const i=+r.dataset.aiRow,p=q.partidas[i],price=Number(r.querySelector('[data-ai-price]')?.value||0),quantity=p.alcance_precio==='global'?1:Number(r.querySelector('[data-ai-qty]')?.value||1);s+=price*quantity});return s}
function update(){const t=total();modal.querySelector('#qv3totals').innerHTML=`<div class="qv3total"><span>Subtotal <b>${money(t)}</b></span><span>IGV no aplicado <b>${money(0)}</b></span><strong>TOTAL <b>${money(t)}</b></strong></div>`;modal.querySelector('#qv3gain').textContent='—';modal.querySelector('#qv3margin').textContent='IA semántica · cálculo determinista';modal.querySelectorAll('[data-ai-row]').forEach(r=>{const i=+r.dataset.aiRow,p=q.partidas[i],price=Number(r.querySelector('[data-ai-price]')?.value||0),quantity=p.alcance_precio==='global'?1:Number(r.querySelector('[data-ai-qty]')?.value||1),cell=r.children[4];if(cell)cell.textContent=money(price*quantity)})}
modal.querySelectorAll('[data-ai-qty],[data-ai-price]').forEach(e=>e.addEventListener('input',update));
if(q.cliente_id){const sel=modal.querySelector('#qv3client');if(sel&&[...sel.options].some(o=>o.value===q.cliente_id)){sel.value=q.cliente_id;sel.dispatchEvent(new Event('change',{bubbles:true}))}}
if(q.ubicacion){const e=modal.querySelector('#qv3location');e.value=q.ubicacion;e.dispatchEvent(new Event('input',{bubbles:true}))}
if(q.duracion){const e=modal.querySelector('#qv3duration');e.value=q.duracion;e.dispatchEvent(new Event('input',{bubbles:true}))}
const mode=modal.querySelector('#qv3costmode');if(mode){mode.value=q.modalidad_costo==='TODO COSTO'?'TODO COSTO':'';mode.dispatchEvent(new Event('change',{bubbles:true}))}
if(q.modalidad_costo==='TODO COSTO'&&Number(q.precio_total_explicito||0)>0){const e=modal.querySelector('#qv3manualTotal');if(e){e.value=Number(q.precio_total_explicito);e.dispatchEvent(new Event('input',{bubbles:true}))}}
window.__MARC_AI_QUOTE={...q,_total:total,_modal:modal};update();ensureSaveSeed()}
function ensureSaveSeed(){if(window.__MARC_AI_SAVE_SEEDED)return;const m=document.getElementById('qv3modal');if(!m||!window.supabaseClient)return;const addBtn=m.querySelector('#qv3serv');const prodBtn=m.querySelector('#qv3prod');if(addBtn){addBtn.click();setTimeout(()=>{const picker=m.querySelector('.qv3picker');const sel=picker?.querySelector('#qv3select');const add=picker?.querySelector('#qv3pa');if(sel&&sel.options.length&&add){sel.selectedIndex=0;add.click();window.__MARC_AI_SAVE_SEEDED=true;render(window.__MARC_AI_QUOTE)}else{picker?.remove();if(prodBtn)seedProduct(m,prodBtn)}},0);return}if(prodBtn)seedProduct(m,prodBtn)}
function seedProduct(m,btn){btn.click();setTimeout(()=>{const picker=m.querySelector('.qv3picker');const sel=picker?.querySelector('#qv3select');const add=picker?.querySelector('#qv3pa');if(sel&&sel.options.length&&add){sel.selectedIndex=0;add.click();window.__MARC_AI_SAVE_SEEDED=true;render(window.__MARC_AI_QUOTE)}else{picker?.remove();msg('⚠ No hay productos/servicios de catálogo. La cotización IA puede revisarse, pero el guardado requiere al menos una partida de catálogo en esta versión.') }},0)}
async function interpret(text){if(!text.trim())return;msg('🧠 Comprendiendo el dictado…');const context=await loadContext();const r=await fetch(API+'interpret-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,context})});const j=await r.json();if(!r.ok||!j.quote)throw Error(j.error||'No se pudo interpretar el dictado');render(j.quote);const a=j.quote.ambiguedades?.length?` · ⚠ ${j.quote.ambiguedades.length} ambigüedad(es)`:' ';msg(`✓ IA acomodó el dictado · ${j.modelo||'motor semántico'} · ${j.quote.partidas.length} partidas${a}`)}
async function blobBase64(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]||'');fr.onerror=rej;fr.readAsDataURL(blob)})}
async function voice(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return legacyVoice();let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';const rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstart=()=>msg('🎙 Escuchando… habla normalmente y pulsa el mismo botón para terminar.');rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());try{msg('⚡ Transcribiendo con Whisper Large V3 Turbo…');const b64=await blobBase64(new Blob(chunks,{type:rec.mimeType||'audio/webm'}));const r=await fetch(API+'transcribe-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio:b64})});const j=await r.json();if(!r.ok)throw Error(j.error||'Error de transcripción');const ta=document.getElementById('qv3text');if(ta)ta.value=j.text||'';await interpret(j.text||'')}catch(e){msg('Error: '+e.message)}};window.__MARC_REC=rec;rec.start()}catch(e){stream?.getTracks().forEach(t=>t.stop());legacyVoice()}}
function legacyVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Este navegador no permite grabar audio.');const r=new R();r.lang='es-PE';r.continuous=false;r.interimResults=false;r.onstart=()=>msg('🎙 Escuchando…');r.onresult=async e=>{const t=e.results[0][0].transcript;document.getElementById('qv3text').value=t;try{await interpret(t)}catch(x){msg('Error: '+x.message)}};r.onerror=()=>msg('No se pudo reconocer el audio.');r.start()}
function install(){const m=document.getElementById('qv3modal');if(!m||installed)return;installed=true;const parse=document.getElementById('qv3parse'),voiceBtn=document.getElementById('qv3voice');if(parse)parse.onclick=()=>interpret(document.getElementById('qv3text')?.value||'');if(voiceBtn)voiceBtn.onclick=()=>{if(window.__MARC_REC?.state==='recording'){window.__MARC_REC.stop();return}voice()};patchSave()}
function patchSave(){const sb=window.supabaseClient;if(!sb||window.__MARC_AI_SAVE_PATCH)return;const original=sb.from.bind(sb);sb.from=function(table){const q=window.__MARC_AI_QUOTE,b=original(table);if(!q)return b;if(table==='cotizaciones'){const ins=b.insert.bind(b);b.insert=p=>{const row=Array.isArray(p)?p[0]:p,total=q._total?q._total():q.partidas.reduce((s,x)=>s+Number(x.precio_unitario||0)*(x.alcance_precio==='global'?1:Number(x.cantidad||1)),0);if(row){row.subtotal=total;row.igv=0;row.total=total;row.utilidad=0;row.empresa_nombre=null}return ins(p)}}if(table==='cotizacion_items'){const ins=b.insert.bind(b);b.insert=p=>{const base=Array.isArray(p)?p[0]:p;const rows=q.partidas.map((x,i)=>{const qty=x.alcance_precio==='global'?1:Number(document.querySelector(`[data-ai-qty="${i}"]`)?.value||x.cantidad||1);const price=Number(document.querySelector(`[data-ai-price="${i}"]`)?.value||x.precio_unitario||0);return {...base,tipo:x.tipo,codigo:'IA',producto_id:x.producto_id||null,servicio_id:x.servicio_id||null,nombre:x.nombre,descripcion:x.descripcion||'Generado por IA desde dictado',unidad:x.unidad||'UND',cantidad:qty,precio_venta:price,precio_compra:0,costo_total:0,importe:qty*price,utilidad:qty*price,utilidad_pct:100,orden:i}});return ins(rows)}}window.__MARC_AI_SAVE_PATCH=true}}
const ob=new MutationObserver(install);ob.observe(document.body,{childList:true,subtree:true});setTimeout(install,300);})();