/* M.A.R.C. — Stock mínimo y alertas de inventario */
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let timer=0;
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
function install(){const wrap=document.querySelector('#inventoryTableWrap');if(!wrap)return;const table=wrap.querySelector('table');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('.inv-min-head')){const th=document.createElement('th');th.className='inv-min-head';th.textContent='Mínimo';const cells=[...head.children];const status=cells.find(x=>x.textContent.trim()==='Estado');if(status)head.insertBefore(th,status);else head.appendChild(th)}wrap.querySelectorAll('tbody tr').forEach(tr=>{if(tr.querySelector('.inv-min-edit'))return;const action=tr.querySelector('.inv-move');if(!action)return;const id=action.dataset.id;const product=window.__MARC_INV_ROWS?.find?.(p=>p.id===id);if(!product)return;const status=[...tr.children].find(x=>x.textContent.trim()==='Disponible'||x.textContent.trim()==='Bajo'||x.textContent.trim()==='Agotado');if(!status)return;const td=document.createElement('td');td.innerHTML=`<div style="display:flex;align-items:center;gap:5px"><input class="inv-min-edit" data-id="${esc(id)}" type="number" min="0" step="1" value="${Number(product.stock_minimo||0)}" title="Stock mínimo"><button type="button" class="inv-min-save" data-id="${esc(id)}" title="Guardar mínimo">✓</button></div>`;status.parentElement.insertBefore(td,status)})}
async function save(id,input,btn){const n=Number(input.value);if(!Number.isFinite(n)||n<0){window.alert('El stock mínimo debe ser un número igual o mayor que 0.');return}btn.disabled=true;try{const u=await user();const {error}=await supabaseClient.from('productos').update({stock_minimo:n,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);if(error)throw error;input.value=n;window.dispatchEvent(new CustomEvent('marc:inventory-refresh'))}catch(e){window.alert('No se pudo guardar el stock mínimo: '+e.message)}finally{btn.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.inv-min-save');if(!b)return;const input=b.parentElement.querySelector('.inv-min-edit');if(input)save(b.dataset.id,input,b)});document.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const input=e.target.closest?.('.inv-min-edit');if(!input)return;e.preventDefault();const b=input.parentElement.querySelector('.inv-min-save');if(b)save(input.dataset.id,input,b)});window.addEventListener('marc:inventory-rows',e=>{window.__MARC_INV_ROWS=e.detail||[];clearTimeout(timer);timer=setTimeout(install,20)});window.addEventListener('marc:inventory-refresh',()=>{document.querySelector('#refreshInventory')?.click()});new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,30)}).observe(document.body,{childList:true,subtree:true});setTimeout(install,1000);
})();
