/* M.A.R.C. — fixes de navegación, persistencia y compatibilidad */
(function(){
  const add=(id,href)=>{if(document.querySelector(`link[data-marc="${id}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.marc=id;document.head.appendChild(l)};
  const load=(id,src)=>{if(document.querySelector(`script[data-marc="${id}"]`))return;const s=document.createElement('script');s.src=src;s.dataset.marc=id;document.head.appendChild(s)};
  add('catalog-css','./catalogos-v4.css?v=8');add('editor-css','./catalogos-editor.css?v=6');
  load('catalog-sync','./catalogos-sync.js?v=6');load('catalog-general','./catalogo-general.js?v=2');load('catalog-v7','./catalogos-v7.js?v=3');load('catalog-editor','./catalogos-editor.js?v=6');load('inventory-tools','./inventario-tools.js?v=4');load('inventory-history','./inventario-historial.js?v=1');load('inventory-detail','./inventario-detalle.js?v=1');load('products-tools','./productos-tools.js?v=1');load('quote-categories','./cotizaciones-categorias.js?v=1');load('quote-ai','./cotizaciones-ia.js?v=7');load('quote-description','./cotizaciones-descripcion.js?v=2');load('quote-pricing-guard','./cotizaciones-precios-guard.js?v=1');load('quote-pdf-fix','./cotizaciones-pdf-fix.js?v=3');load('quote-edit','./cotizaciones-editar.js?v=1');load('quote-delete','./cotizaciones-eliminar.js?v=1');
  window.__MARC_CATALOG_TYPE='PROPIO';try{Object.defineProperty(window,'tipo',{configurable:true,get(){return window.__MARC_CATALOG_TYPE||'PROPIO'},set(v){window.__MARC_CATALOG_TYPE=v||'PROPIO'}})}catch{}
  document.addEventListener('change',e=>{const id=e.target?.id;if(id==='cat4Own'||id==='catOwn')window.__MARC_CATALOG_TYPE='PROPIO';if(id==='cat4Prov'||id==='catSupplier')window.__MARC_CATALOG_TYPE='PROVEEDOR'},true);
  const validSections=new Set(['dashboard','clients','products','services','inventory','quotes','reports','documents','ai','company','settings']);let current=location.hash.replace(/^#/,'');if(!validSections.has(current))current='dashboard';
  function syncCatalogVisibility(){const panel=document.querySelector('#cat4Panel');if(!panel)return;panel.hidden=current!=='inventory';panel.style.display=current==='inventory'?'':'none';if(current==='inventory'&&!panel.querySelector('.marc-ai-warning')){const w=document.createElement('div');w.className='marc-ai-warning';w.innerHTML='<p>M.A.R.C. no garantiza que la información extraída automáticamente sea exacta o completa.</p><p>Ningún producto será incorporado al inventario sin la revisión y aprobación del usuario.</p>';const target=panel.querySelector('#cat4Progress');if(target)panel.insertBefore(w,target);else panel.appendChild(w)}}
  const originalRender=window.render;if(typeof originalRender==='function')window.render=function(section='dashboard'){if(validSections.has(section))current=section;originalRender(section);requestAnimationFrame(syncCatalogVisibility)};
  const main=document.querySelector('.main');if(main)new MutationObserver(()=>requestAnimationFrame(syncCatalogVisibility)).observe(main,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',()=>setTimeout(syncCatalogVisibility,300));setTimeout(syncCatalogVisibility,500);
  const originalShowApp=window.showApp;if(typeof originalShowApp==='function')window.showApp=function(session){if(!session)return;const a=document.querySelector('#authScreen'),s=document.querySelector('#appShell');if(a)a.hidden=true;if(s)s.hidden=false;const email=session.user?.email||'';const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v};set('#userEmail',email);set('#companyUser',email.split('@')[0]||'Usuario');set('#userName',email.split('@')[0]||'Usuario');originalRender(validSections.has(current)?current:'dashboard');requestAnimationFrame(syncCatalogVisibility)};
  document.addEventListener('click',e=>{const nav=e.target.closest?.('.nav-item');if(nav&&validSections.has(nav.dataset.section)){current=nav.dataset.section;history.replaceState(null,'','#'+current);requestAnimationFrame(syncCatalogVisibility)}},true);
  window.addEventListener('hashchange',()=>{const section=location.hash.replace(/^#/,'');if(validSections.has(section)){current=section;if(typeof window.render==='function')window.render(section);else syncCatalogVisibility()}});
  const NativeFormData=window.FormData;if(NativeFormData){window.FormData=function(form,...args){if(form&&!(form instanceof HTMLFormElement))form=document.querySelector('#productForm')||form;if(!form)form=document.querySelector('#productForm')||undefined;return form===undefined?new NativeFormData(...args):new NativeFormData(form)};window.FormData.prototype=NativeFormData.prototype}
})();
