/* M.A.R.C. — herramientas avanzadas de Productos */
(function(){
'use strict';
let busy=false,observer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function user(){const r=await supabaseClient.auth.getUser();if(r.error||!r.data.user)throw new Error('Tu sesión expiró.');return r.data.user}
async function softDelete(e){const b=e.target.closest?.('.product-delete');if(!b)return; e.preventDefault();e.stopImmediatePropagation(); if(b.dataset.marcDeleting)return;b.dataset.marcDeleting='1';try{const u=await user();const {data:p,error:q}=await supabaseClient.from('productos').select('id,nombre,codigo,imagen_url').eq('id',b.dataset.id).eq('user_id',u.id).maybeSingle();if(q)throw q;if(!p)return;if(!confirm(`¿Retirar "${p.nombre||p.codigo}" del catálogo?\n\nEl producto no se borrará físicamente. Quedará inactivo y se conservarán sus datos e historial.`))return;const {error}=await supabaseClient.from('productos').update({activo:false,updated_at:new Date().toISOString()}).eq('id',p.id).eq('user_id',u.id);if(error)throw error;window.render('products')}catch(x){alert('No se pudo retirar el producto: '+(x.message||x))}finally{delete b.dataset.marcDeleting}}
function css(){if(document.getElementById('marc-products-tools-css'))return;const s=document.createElement('style');s.id='marc-products-tools-css';s.textContent='.marc-products-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:0 0 14px}.marc-products-kpi{background:#fff;border:1px solid #e0eaf3;border-radius:14px;padding:13px}.marc-products-kpi small{display:block;color:#7891ad;font-size:9px}.marc-products-kpi strong{display:block;color:#183b60;font-size:21px;margin-top:4px}.marc-products-kpi.low strong{color:#a66a00}.marc-products-kpi.out strong{color:#c83d4e}.marc-products-filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.marc-products-filter{border:1px solid #d6e3ee;background:#fff;color:#526f8d;border-radius:999px;padding:7px 11px;font-size:10px;font-weight:700;cursor:pointer}.marc-products-filter.active{background:#087cf5;color:#fff;border-color:#087cf5}.marc-products-filter.inactive{color:#9a5560}.marc-product-inactive-row{opacity:.65}.marc-product-inactive-row td:first-child{border-left:3px solid #c83d4e}@media(max-width:650px){.marc-products-kpis{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function enhance(){if(busy)return;const wrap=document.querySelector('#productsTableWrap');if(!wrap||!wrap.querySelector('table')||wrap.querySelector('.marc-products-filters'))return;busy=true;try{css();const table=wrap.querySelector('table'),body=table.querySelector('tbody');const rows=[...body.querySelectorAll('tr')];const allRows=rows.map(tr=>{const btn=tr.querySelector('.product-edit,.product-delete');return{id:btn?.dataset.id||'',tr,active:!tr.textContent.includes('Inactivo'),low:/Stock bajo/i.test(tr.textContent),out:/\b0\s*(?:UND|MTR|ROL|CJ|PAR)?\b/.test(tr.textContent)}});const bar=document.createElement('div');bar.className='marc-products-filters';bar.innerHTML='<button type="button" class="marc-products-filter active" data-f="all">Todos</button><button type="button" class="marc-products-filter" data-f="active">Activos</button><button type="button" class="marc-products-filter" data-f="low">Stock bajo</button><button type="button" class="marc-products-filter" data-f="out">Agotados</button><button type="button" class="marc-products-filter inactive" data-f="inactive">Inactivos</button>';wrap.insertBefore(bar,table.parentElement||table);const k=document.createElement('div');k.className='marc-products-kpis';const active=allRows.filter(x=>x.active),low=allRows.filter(x=>x.active&&x.low),out=allRows.filter(x=>x.active&&x.out),inactive=allRows.filter(x=>!x.active);k.innerHTML=`<div class="marc-products-kpi"><small>Productos activos</small><strong>${active.length}</strong></div><div class="marc-products-kpi"><small>Unidades en stock</small><strong>${allRows.reduce((n,x)=>{const c=x.tr.children[6]?.textContent.match(/-?\d+(?:[.,]\d+)?/);return n+(c?Number(c[0].replace(',','.')):0)},0).toLocaleString('es-PE')}</strong></div><div class="marc-products-kpi low"><small>Stock bajo</small><strong>${low.length}</strong></div><div class="marc-products-kpi out"><small>Agotados</small><strong>${out.length}</strong></div>`;wrap.parentElement?.insertBefore(k,wrap);bar.querySelectorAll('[data-f]').forEach(btn=>btn.onclick=()=>{bar.querySelectorAll('[data-f]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.f;allRows.forEach(x=>{let show=f==='all'||(f==='active'&&x.active)||(f==='inactive'&&!x.active)||(f==='low'&&x.active&&x.low)||(f==='out'&&x.active&&x.out);x.tr.style.display=show?'':'none'})});allRows.forEach(x=>x.tr.classList.toggle('marc-product-inactive-row',!x.active));
}catch(e){console.warn('MARC productos tools',e)}finally{busy=false}}
document.addEventListener('click',softDelete,true);
function start(){enhance();if(observer)observer.disconnect();observer=new MutationObserver(()=>setTimeout(enhance,80));observer.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,700));else setTimeout(start,700);
window.MARC_PRODUCTS_TOOLS={enhance};
})();
