/* M.A.R.C. — módulo Productos */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='products') return oldRender(section);
    const content=document.querySelector('#content'); if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Productos</h1><p>Catálogo, precios, modelos y existencias.</p></div></div><section class="panel table-panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="productsSearch" placeholder="Buscar producto..."></div><button class="btn btn-primary" id="newProductBtn">＋ Nuevo producto</button></div><div id="productsTableWrap"><div class="products-loading">Cargando productos...</div></div></section>`;
    loadProducts();
  };
  async function loadProducts(){
    const wrap=document.querySelector('#productsTableWrap'); if(!wrap)return;
    const {data:{user}}=await supabaseClient.auth.getUser();
    if(!user){wrap.innerHTML='<div class="products-empty">Inicia sesión para ver tus productos.</div>';return;}
    const {data,error}=await supabaseClient.from('productos').select('id,codigo,nombre,descripcion,marca,modelo,categoria,unidad,precio_compra,precio_venta,stock,stock_minimo,imagen_url,activo').eq('user_id',user.id).order('nombre',{ascending:true});
    if(error){wrap.innerHTML=`<div class="products-empty">No se pudieron cargar los productos.<br><small>${esc(error.message)}</small></div>`;return;}
    const rows=data||[];
    const draw=list=>{ if(!list.length){wrap.innerHTML='<div class="products-empty"><div class="products-empty-icon">◈</div><h3>No tienes productos todavía</h3><p>Agrega tu primer producto al catálogo.</p><button class="btn btn-primary" id="emptyNewProduct">＋ Agregar producto</button></div>';return;}
      wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Código</th><th>Producto</th><th>Marca</th><th>Modelo</th><th>Precio venta</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>{const low=Number(p.stock)<=Number(p.stock_minimo);return `<tr><td>${esc(p.codigo)}</td><td><strong>${esc(p.nombre)}</strong></td><td>${esc(p.marca||'—')}</td><td>${esc(p.modelo||'—')}</td><td>S/ ${Number(p.precio_venta||0).toFixed(2)}</td><td>${Number(p.stock||0)} ${esc(p.unidad||'UND')}</td><td><mark class="${!p.activo?'critical':low?'critical':''}">${!p.activo?'Inactivo':low?'Stock bajo':'Disponible'}</mark></td><td><button class="table-action product-edit" data-id="${p.id}">✎</button> <button class="table-action product-delete" data-id="${p.id}">×</button></td></tr>`}).join('')}</tbody></table></div><div class="table-foot">Mostrando ${list.length} de ${rows.length} productos</div>`;
    };
    draw(rows);
    document.querySelector('#productsSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();draw(rows.filter(p=>[p.codigo,p.nombre,p.marca,p.modelo,p.categoria].some(v=>String(v||'').toLowerCase().includes(q))));});
    const open=()=>openProductModal();document.querySelector('#newProductBtn')?.addEventListener('click',open);document.querySelector('#emptyNewProduct')?.addEventListener('click',open);
    document.querySelectorAll('.product-edit').forEach(b=>b.addEventListener('click',()=>openProductModal(rows.find(p=>p.id===b.dataset.id))));
    document.querySelectorAll('.product-delete').forEach(b=>b.addEventListener('click',()=>deleteProduct(b.dataset.id,rows)));
  }
  function openProductModal(p=null){
    document.querySelector('#productModal')?.remove(); const modal=document.createElement('div'); modal.id='productModal';modal.className='product-modal-backdrop';
    modal.innerHTML=`<div class="product-modal"><div class="product-modal-head"><div><p class="eyebrow">M.A.R.C. / PRODUCTOS</p><h2>${p?'Editar producto':'Nuevo producto'}</h2></div><button type="button" class="product-close">×</button></div><form id="productForm" class="product-form"><div class="product-grid"><label>Código<input name="codigo" required value="${esc(p?.codigo)}" placeholder="CAM-001"></label><label>Unidad<select name="unidad"><option ${p?.unidad==='UND'||!p?'selected':''}>UND</option><option ${p?.unidad==='MTR'?'selected':''}>MTR</option><option ${p?.unidad==='ROL'?'selected':''}>ROL</option><option ${p?.unidad==='CJ'?'selected':''}>CJ</option><option ${p?.unidad==='PAR'?'selected':''}>PAR</option></select></label></div><label>Nombre<input name="nombre" required value="${esc(p?.nombre)}" placeholder="Cámara IP 4MP"></label><div class="product-grid"><label>Marca<input name="marca" value="${esc(p?.marca)}" placeholder="Hikvision"></label><label>Modelo<input name="modelo" value="${esc(p?.modelo)}" placeholder="DS-2CD..."></label></div><div class="product-grid"><label>Categoría<input name="categoria" value="${esc(p?.categoria)}" placeholder="Cámaras"></label><label>Descripción<input name="descripcion" value="${esc(p?.descripcion)}"></label></div><div class="product-grid"><label>Precio compra (S/)<input name="precio_compra" type="number" min="0" step="0.01" value="${p?.precio_compra??0}"></label><label>Precio venta (S/)<input name="precio_venta" type="number" min="0" step="0.01" value="${p?.precio_venta??0}"></label></div><div class="product-grid"><label>Stock<input name="stock" type="number" min="0" step="0.01" value="${p?.stock??0}"></label><label>Stock mínimo<input name="stock_minimo" type="number" min="0" step="0.01" value="${p?.stock_minimo??0}"></label></div><label>URL de imagen<input name="imagen_url" type="url" value="${esc(p?.imagen_url)}" placeholder="https://..."></label><label class="product-check"><input name="activo" type="checkbox" ${p?.activo!==false?'checked':''}> Producto activo</label><div class="product-modal-actions"><button type="button" class="btn btn-secondary product-cancel">Cancelar</button><button type="submit" class="btn btn-primary">${p?'Guardar cambios':'Guardar producto'}</button></div><div id="productFormMsg" class="product-form-msg"></div></form></div>`;
    document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.product-close').onclick=close;modal.querySelector('.product-cancel').onclick=close;
    modal.querySelector('#productForm').addEventListener('submit',async e=>{e.preventDefault();const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const fd=new FormData(e.currentTarget);const payload={user_id:user.id,codigo:String(fd.get('codigo')||'').trim(),nombre:String(fd.get('nombre')||'').trim(),marca:String(fd.get('marca')||'').trim()||null,modelo:String(fd.get('modelo')||'').trim()||null,categoria:String(fd.get('categoria')||'').trim()||null,descripcion:String(fd.get('descripcion')||'').trim()||null,unidad:String(fd.get('unidad')||'UND'),precio_compra:Number(fd.get('precio_compra')||0),precio_venta:Number(fd.get('precio_venta')||0),stock:Number(fd.get('stock')||0),stock_minimo:Number(fd.get('stock_minimo')||0),imagen_url:String(fd.get('imagen_url')||'').trim()||null,activo:fd.get('activo')==='on',updated_at:new Date().toISOString()};const r=p?await supabaseClient.from('productos').update(payload).eq('id',p.id).eq('user_id',user.id):await supabaseClient.from('productos').insert(payload);if(r.error){const m=modal.querySelector('#productFormMsg');m.textContent=r.error.message;m.className='product-form-msg error';return;}close();loadProducts();});
  }
  async function deleteProduct(id,rows){const p=rows.find(x=>x.id===id);if(!p)return;if(!window.confirm(`¿Eliminar ${p.nombre}?`))return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {error}=await supabaseClient.from('productos').delete().eq('id',id).eq('user_id',user.id);if(error)window.alert(error.message);else loadProducts();}
  const s=document.createElement('style');s.textContent='.products-loading,.products-empty{padding:55px 20px;text-align:center;color:#7891ad;font-size:12px}.products-empty-icon{width:64px;height:64px;margin:0 auto 12px;border-radius:18px;background:#eaf5ff;color:#087cf5;display:grid;place-items:center;font-size:27px}.products-empty h3{margin:0 0 6px;color:#24496e;font-size:16px}.products-empty p{margin:0 auto 15px}.product-modal-backdrop{position:fixed;inset:0;background:#071d38aa;backdrop-filter:blur(6px);z-index:100;display:grid;place-items:center;padding:18px}.product-modal{width:min(700px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:24px}.product-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.product-modal-head h2{margin:0;color:#102b54;font-size:23px}.product-close{border:0;background:#eef5fb;color:#557493;border-radius:9px;width:34px;height:34px;font-size:22px}.product-form{display:grid;gap:13px}.product-form label{display:grid;gap:6px;color:#536b89;font-size:11px;font-weight:700}.product-form input,.product-form select{width:100%;border:1px solid #d2e0ec;border-radius:10px;background:#f8fbfe;color:#173452;padding:11px;font-size:12px}.product-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.product-check{display:flex!important;align-items:center;gap:8px}.product-check input{width:auto}.product-modal-actions{display:flex;justify-content:flex-end;gap:9px}.product-form-msg{min-height:17px;font-size:10px}.product-form-msg.error{color:#d13d4e}@media(max-width:600px){.product-grid{grid-template-columns:1fr}.product-modal{padding:19px}}';document.head.appendChild(s);
})();
