/* M.A.R.C. — módulo Servicios */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  window.render=function(section='dashboard'){
    if(section!=='services') return oldRender(section);
    const content=document.querySelector('#content'); if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Servicios</h1><p>Catálogo de servicios, precios y condiciones para tus cotizaciones.</p></div></div><section class="panel table-panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="servicesSearch" placeholder="Buscar servicio..."></div><button type="button" class="btn btn-primary" id="newServiceBtn">＋ Nuevo servicio</button></div><div id="servicesTableWrap"><div class="services-loading">Cargando servicios...</div></div></section>`;
    document.querySelector('#newServiceBtn')?.addEventListener('click',()=>openServiceModal());
    loadServices();
  };
  async function loadServices(){
    const wrap=document.querySelector('#servicesTableWrap'); if(!wrap)return;
    const {data:{user}}=await supabaseClient.auth.getUser();
    if(!user){wrap.innerHTML='<div class="services-empty">Inicia sesión para ver tus servicios.</div>';return;}
    const {data,error}=await supabaseClient.from('servicios').select('id,codigo,nombre,descripcion,categoria,unidad,precio,activo').eq('user_id',user.id).order('nombre',{ascending:true});
    if(error){wrap.innerHTML=`<div class="services-empty">No se pudieron cargar los servicios.<br><small>${esc(error.message)}</small></div>`;return;}
    const rows=data||[];
    const draw=list=>{
      if(!list.length){wrap.innerHTML='<div class="services-empty"><div class="services-empty-icon">◇</div><h3>No tienes servicios todavía</h3><p>Agrega tu primer servicio al catálogo.</p><button type="button" class="btn btn-primary" id="emptyNewService">＋ Agregar servicio</button></div>';document.querySelector('#emptyNewService')?.addEventListener('click',()=>openServiceModal());return;}
      wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Código</th><th>Servicio</th><th>Categoría</th><th>Unidad</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${list.map(s=>`<tr><td>${esc(s.codigo||'—')}</td><td><strong>${esc(s.nombre)}</strong><br><small>${esc(s.descripcion||'')}</small></td><td>${esc(s.categoria||'—')}</td><td>${esc(s.unidad||'SERVICIO')}</td><td>S/ ${Number(s.precio||0).toFixed(2)}</td><td><mark class="${s.activo?'':'critical'}">${s.activo?'Activo':'Inactivo'}</mark></td><td><button type="button" class="table-action service-edit" data-id="${s.id}">✎</button> <button type="button" class="table-action service-delete" data-id="${s.id}">×</button></td></tr>`).join('')}</tbody></table></div><div class="table-foot">Mostrando ${list.length} de ${rows.length} servicios</div>`;
      document.querySelectorAll('.service-edit').forEach(b=>b.addEventListener('click',()=>openServiceModal(rows.find(s=>s.id===b.dataset.id))));
      document.querySelectorAll('.service-delete').forEach(b=>b.addEventListener('click',()=>deleteService(b.dataset.id,rows)));
    };
    draw(rows);
    document.querySelector('#servicesSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();draw(rows.filter(s=>[s.codigo,s.nombre,s.categoria,s.descripcion].some(v=>String(v||'').toLowerCase().includes(q))));});
  }
  function openServiceModal(s=null){
    document.querySelector('#serviceModal')?.remove();
    const modal=document.createElement('div'); modal.id='serviceModal'; modal.className='service-modal-backdrop';
    modal.innerHTML=`<div class="service-modal"><div class="service-modal-head"><div><p class="eyebrow">M.A.R.C. / SERVICIOS</p><h2>${s?'Editar servicio':'Nuevo servicio'}</h2></div><button type="button" class="service-close">×</button></div><form id="serviceForm" class="service-form"><div class="service-grid"><label>Código<input name="codigo" value="${esc(s?.codigo)}" placeholder="SRV-001"></label><label>Unidad<select name="unidad"><option ${s?.unidad==='SERVICIO'||!s?'selected':''}>SERVICIO</option><option ${s?.unidad==='HORA'?'selected':''}>HORA</option><option ${s?.unidad==='VISITA'?'selected':''}>VISITA</option><option ${s?.unidad==='INSTALACION'?'selected':''}>INSTALACION</option><option ${s?.unidad==='MANTENIMIENTO'?'selected':''}>MANTENIMIENTO</option></select></label></div><label>Nombre del servicio<input name="nombre" required value="${esc(s?.nombre)}" placeholder="Instalación de cámara CCTV"></label><div class="service-grid"><label>Categoría<input name="categoria" value="${esc(s?.categoria)}" placeholder="CCTV"></label><label>Precio (S/)<input name="precio" type="number" min="0" step="0.01" value="${s?.precio??0}"></label></div><label>Descripción<textarea name="descripcion" rows="4" placeholder="Incluye instalación, configuración, pruebas...">${esc(s?.descripcion)}</textarea></label><label class="service-check"><input name="activo" type="checkbox" ${s?.activo!==false?'checked':''}> Servicio activo</label><div class="service-modal-actions"><button type="button" class="btn btn-secondary service-cancel">Cancelar</button><button type="submit" class="btn btn-primary">${s?'Guardar cambios':'Guardar servicio'}</button></div><div id="serviceFormMsg" class="service-form-msg"></div></form></div>`;
    document.body.appendChild(modal); const close=()=>modal.remove(); modal.querySelector('.service-close').onclick=close; modal.querySelector('.service-cancel').onclick=close;
    modal.querySelector('#serviceForm').addEventListener('submit',async e=>{
      e.preventDefault(); const form=e.currentTarget,msg=modal.querySelector('#serviceFormMsg'),btn=form.querySelector('button[type="submit"]'); btn.disabled=true;
      try{const {data:{user}}=await supabaseClient.auth.getUser();if(!user)throw new Error('Tu sesión expiró. Inicia sesión nuevamente.');const fd=new FormData(form);const nombre=String(fd.get('nombre')||'').trim();if(!nombre)throw new Error('Escribe el nombre del servicio.');const payload={user_id:user.id,codigo:String(fd.get('codigo')||'').trim()||null,nombre,descripcion:String(fd.get('descripcion')||'').trim()||null,categoria:String(fd.get('categoria')||'').trim()||null,unidad:String(fd.get('unidad')||'SERVICIO'),precio:Number(fd.get('precio')||0),activo:fd.get('activo')==='on',updated_at:new Date().toISOString()};const r=s?await supabaseClient.from('servicios').update(payload).eq('id',s.id).eq('user_id',user.id):await supabaseClient.from('servicios').insert(payload);if(r.error)throw r.error;close();loadServices();}catch(err){msg.textContent=err?.message||'No se pudo guardar el servicio.';msg.className='service-form-msg error';btn.disabled=false;}}
  );
  }
  async function deleteService(id,rows){const s=rows.find(x=>x.id===id);if(!s)return;if(!window.confirm(`¿Eliminar ${s.nombre}?`))return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {error}=await supabaseClient.from('servicios').delete().eq('id',id).eq('user_id',user.id);if(error)window.alert(error.message);else loadServices();}
  const style=document.createElement('style');style.textContent='.services-loading,.services-empty{padding:55px 20px;text-align:center;color:#7891ad;font-size:12px}.services-empty-icon{width:64px;height:64px;margin:0 auto 12px;border-radius:18px;background:#eaf5ff;color:#087cf5;display:grid;place-items:center;font-size:27px}.services-empty h3{margin:0 0 6px;color:#24496e;font-size:16px}.services-empty p{margin:0 auto 15px}.service-modal-backdrop{position:fixed;inset:0;background:#071d38aa;backdrop-filter:blur(6px);z-index:100;display:grid;place-items:center;padding:18px}.service-modal{width:min(650px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:24px}.service-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.service-modal-head h2{margin:0;color:#102b54;font-size:23px}.service-close{border:0;background:#eef5fb;color:#557493;border-radius:9px;width:34px;height:34px;font-size:22px}.service-form{display:grid;gap:13px}.service-form label{display:grid;gap:6px;color:#536b89;font-size:11px;font-weight:700}.service-form input,.service-form select,.service-form textarea{width:100%;border:1px solid #d2e0ec;border-radius:10px;background:#f8fbfe;color:#173452;padding:11px;font-size:12px}.service-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.service-check{display:flex!important;grid-template-columns:none!important;align-items:center;gap:9px!important}.service-check input{width:auto}.service-modal-actions{display:flex;justify-content:flex-end;gap:9px}.service-form-msg{min-height:17px;font-size:10px}.service-form-msg.error{color:#d13d4e}@media(max-width:600px){.service-grid{grid-template-columns:1fr}.service-modal{padding:19px}}';document.head.appendChild(style);
})();