/* M.A.R.C. — Servicios: voz + IA + códigos automáticos */
(function(){
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const oldRender=window.render;
  const TYPE_PREFIX={CCTV:'CCTV',COMPUTACION:'COMP',REDES:'RED',MANTENIMIENTO:'MANT',INSTALACION:'INST',SOPORTE:'SOP',OTROS:'SRV'};
  window.render=function(section='dashboard'){
    if(section!=='services') return oldRender(section);
    const content=document.querySelector('#content'); if(!content)return;
    content.innerHTML=`<div class="page-head"><div><p class="eyebrow">M.A.R.C. / OPERACIONES</p><h1>Servicios</h1><p>Catálogo de servicios, precios y condiciones para tus cotizaciones.</p></div></div><div class="services-kpis"><button class="service-kpi active" data-filter="all"><small>Total servicios</small><strong id="servicesKpiTotal">0</strong></button><button class="service-kpi" data-filter="active"><small>Servicios activos</small><strong id="servicesKpiActive">0</strong></button><button class="service-kpi" data-filter="inactive"><small>Inactivos</small><strong id="servicesKpiInactive">0</strong></button><button class="service-kpi" data-filter="priced"><small>Con precio</small><strong id="servicesKpiPriced">0</strong></button></div><section class="panel table-panel"><div class="table-toolbar"><div class="search-box local"><span>⌕</span><input id="servicesSearch" placeholder="Buscar por código, servicio, tipo o descripción..."></div><button type="button" class="btn btn-primary" id="newServiceBtn">＋ Nuevo servicio</button></div><div class="service-filters"><button type="button" class="service-filter active" data-filter="all">Todos</button><button type="button" class="service-filter" data-filter="active">Activos</button><button type="button" class="service-filter" data-filter="inactive">Inactivos</button><button type="button" class="service-filter" data-filter="priced">Con precio</button></div><div id="servicesTableWrap"><div class="services-loading">Cargando servicios...</div></div></section>`;
    document.querySelector('#newServiceBtn')?.addEventListener('click',()=>openServiceModal());
    loadServices();
  };
  async function getUser(){const {data:{user},error}=await supabaseClient.auth.getUser();if(error||!user)throw new Error('Tu sesión expiró. Inicia sesión nuevamente.');return user;}
  async function nextCode(type,excludeId=null){const prefix=TYPE_PREFIX[type]||'SRV';const {data,error}=await supabaseClient.from('servicios').select('codigo,id').ilike('codigo',`${prefix}-%`);if(error)return `${prefix}-001`;let max=0;(data||[]).forEach(x=>{if(excludeId&&x.id===excludeId)return;const m=String(x.codigo||'').match(new RegExp(`^${prefix}-(\\d+)$`,'i'));if(m)max=Math.max(max,Number(m[1]));});return `${prefix}-${String(max+1).padStart(3,'0')}`;}
  async function loadServices(){
    const wrap=document.querySelector('#servicesTableWrap');if(!wrap)return;
    try{const user=await getUser();const {data,error}=await supabaseClient.from('servicios').select('id,codigo,nombre,descripcion,categoria,unidad,precio,activo').eq('user_id',user.id).order('nombre',{ascending:true});if(error){wrap.innerHTML=`<div class="services-empty">No se pudieron cargar los servicios.<br><small>${esc(error.message)}</small></div>`;return;}const rows=data||[];
      const count=fn=>rows.filter(fn).length;const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=String(v)};set('#servicesKpiTotal',rows.length);set('#servicesKpiActive',count(s=>s.activo));set('#servicesKpiInactive',count(s=>!s.activo));set('#servicesKpiPriced',count(s=>Number(s.precio||0)>0));
      let activeFilter='all';const matches=s=>activeFilter==='all'||activeFilter==='active'?Boolean(s.activo):activeFilter==='inactive'?!s.activo:Number(s.precio||0)>0;
      const draw=()=>{const q=(document.querySelector('#servicesSearch')?.value||'').toLowerCase().trim();const list=rows.filter(s=>matches(s)&&[s.codigo,s.nombre,s.categoria,s.descripcion].some(v=>String(v||'').toLowerCase().includes(q)));if(!list.length){wrap.innerHTML='<div class="services-empty"><div class="services-empty-icon">◇</div><h3>No se encontraron servicios</h3><p>Prueba otro filtro o registra un nuevo servicio.</p></div>';return;}wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Código</th><th>Servicio</th><th>Tipo</th><th>Unidad</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${list.map(s=>`<tr><td><strong>${esc(s.codigo||'—')}</strong></td><td><strong>${esc(s.nombre)}</strong><br><small>${esc(s.descripcion||'')}</small></td><td>${esc(s.categoria||'—')}</td><td>${esc(s.unidad||'SERVICIO')}</td><td>S/ ${Number(s.precio||0).toFixed(2)}</td><td><mark class="${s.activo?'':'critical'}">${s.activo?'Activo':'Inactivo'}</mark></td><td><button type="button" class="table-action service-edit" data-id="${s.id}">✎</button> <button type="button" class="table-action service-delete" data-id="${s.id}">×</button></td></tr>`).join('')}</tbody></table></div><div class="table-foot">Mostrando ${list.length} de ${rows.length} servicios</div>`;document.querySelectorAll('.service-edit').forEach(b=>b.addEventListener('click',()=>openServiceModal(rows.find(s=>s.id===b.dataset.id))));document.querySelectorAll('.service-delete').forEach(b=>b.addEventListener('click',()=>deleteService(b.dataset.id,rows)));};
      document.querySelector('#servicesSearch')?.addEventListener('input',draw);document.querySelectorAll('.service-filter,.service-kpi').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter||'all';document.querySelectorAll('.service-filter,.service-kpi').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));draw();}));draw();
    }catch(err){wrap.innerHTML=`<div class="services-empty">${esc(err.message)}</div>`;}
  }
  function openServiceModal(s=null){
    document.querySelector('#serviceModal')?.remove();const modal=document.createElement('div');modal.id='serviceModal';modal.className='service-modal-backdrop';modal.innerHTML=`<div class="service-modal"><div class="service-modal-head"><div><p class="eyebrow">M.A.R.C. / SERVICIOS</p><h2>${s?'Editar servicio':'Nuevo servicio'}</h2></div><button type="button" class="service-close">×</button></div><div class="voice-box"><button type="button" class="btn btn-primary" id="voiceServiceBtn">🎙️ Hablar con M.A.R.C.</button><span id="voiceStatus">Describe el servicio por voz y la IA llenará los campos.</span></div><form id="serviceForm" class="service-form"><div class="service-grid"><label>Tipo de servicio<select name="tipo"><option value="CCTV">CCTV</option><option value="COMPUTACION">Computación</option><option value="REDES">Redes</option><option value="MANTENIMIENTO">Mantenimiento</option><option value="INSTALACION">Instalación</option><option value="SOPORTE">Soporte</option><option value="OTROS">Otros</option></select></label><label>Código<input name="codigo" readonly value="${esc(s?.codigo)}" placeholder="Se genera automáticamente"><small>El código se genera según el tipo.</small></label></div><div class="service-grid"><label>Unidad<select name="unidad"><option ${s?.unidad==='SERVICIO'||!s?'selected':''}>SERVICIO</option><option ${s?.unidad==='HORA'?'selected':''}>HORA</option><option ${s?.unidad==='VISITA'?'selected':''}>VISITA</option><option ${s?.unidad==='INSTALACION'?'selected':''}>INSTALACION</option><option ${s?.unidad==='MANTENIMIENTO'?'selected':''}>MANTENIMIENTO</option></select></label><label>Precio (S/)<input name="precio" type="number" min="0" step="0.01" value="${s?.precio??0}"></label></div><label>Nombre del servicio<input name="nombre" required value="${esc(s?.nombre)}" placeholder="Instalación de cámara CCTV"></label><label>Descripción<textarea name="descripcion" rows="4" placeholder="Incluye instalación, configuración, pruebas...">${esc(s?.descripcion)}</textarea></label><label class="service-check"><input name="activo" type="checkbox" ${s?.activo!==false?'checked':''}> Servicio activo</label><div class="service-modal-actions"><button type="button" class="btn btn-secondary service-cancel">Cancelar</button><button type="submit" class="btn btn-primary">${s?'Guardar cambios':'Guardar servicio'}</button></div><div id="serviceFormMsg" class="service-form-msg"></div></form></div>`;
    document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.service-close').onclick=close;modal.querySelector('.service-cancel').onclick=close;const form=modal.querySelector('#serviceForm'),typeEl=form.querySelector('[name="tipo"]'),codeEl=form.querySelector('[name="codigo"]'),voiceBtn=modal.querySelector('#voiceServiceBtn'),voiceStatus=modal.querySelector('#voiceStatus');if(s)typeEl.value=Object.keys(TYPE_PREFIX).find(k=>TYPE_PREFIX[k]===String(s.codigo||'').split('-')[0])||'OTROS';else nextCode(typeEl.value).then(c=>codeEl.value=c);typeEl.addEventListener('change',async()=>{if(!s)codeEl.value=await nextCode(typeEl.value);});
    let recognition=null;voiceBtn.addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){voiceStatus.textContent='Este navegador no permite reconocimiento de voz. Usa Chrome en Android o escribe los datos.';return;}if(recognition){recognition.stop();return;}recognition=new SR();recognition.lang='es-PE';recognition.interimResults=false;recognition.continuous=false;voiceBtn.textContent='⏹️ Escuchando...';voiceStatus.textContent='Habla ahora. Ejemplo: “instalación de 4 cámaras Hikvision, precio 850 soles”.';recognition.onresult=async e=>{const text=e.results?.[0]?.[0]?.transcript||'';voiceStatus.textContent=`Entendido: “${text}”. Analizando...`;await analyzeVoice(text)};recognition.onerror=e=>{voiceStatus.textContent=`No pude escuchar: ${e.error||'error de voz'}.`};recognition.onend=()=>{recognition=null;voiceBtn.textContent='🎙️ Hablar con M.A.R.C.'};recognition.start()});
    async function analyzeVoice(text){try{const r=await fetch('/api/analyze-service',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo analizar la descripción.');const d=j.data||{};if(d.tipo&&TYPE_PREFIX[d.tipo])typeEl.value=d.tipo;if(d.unidad)form.querySelector('[name="unidad"]').value=d.unidad;if(d.nombre)form.querySelector('[name="nombre"]').value=d.nombre;if(d.descripcion)form.querySelector('[name="descripcion"]').value=d.descripcion;if(d.precio!==null&&d.precio!==undefined&&d.precio!=='')form.querySelector('[name="precio"]').value=Number(d.precio)||0;if(!s)codeEl.value=await nextCode(typeEl.value);voiceStatus.textContent=`✓ IA completó ${Object.values(d).filter(v=>v!==null&&v!==undefined&&String(v).trim()!=='').length} datos. Revísalos y guarda.`}catch(err){voiceStatus.textContent=`Error: ${err.message}`}}
    form.addEventListener('submit',async e=>{e.preventDefault();const msg=modal.querySelector('#serviceFormMsg'),btn=form.querySelector('button[type="submit"]');btn.disabled=true;msg.textContent='';try{const user=await getUser();const fd=new FormData(form),nombre=String(fd.get('nombre')||'').trim();if(!nombre)throw new Error('Escribe o dicta el nombre del servicio.');const payload={user_id:user.id,codigo:String(fd.get('codigo')||'').trim()||await nextCode(String(fd.get('tipo')||'OTROS')),nombre,descripcion:String(fd.get('descripcion')||'').trim()||null,categoria:String(fd.get('tipo')||'OTROS'),unidad:String(fd.get('unidad')||'SERVICIO'),precio:Number(fd.get('precio')||0),activo:fd.get('activo')==='on',updated_at:new Date().toISOString()};const r=s?await supabaseClient.from('servicios').update(payload).eq('id',s.id).eq('user_id',user.id):await supabaseClient.from('servicios').insert(payload);if(r.error)throw r.error;close();loadServices()}catch(err){msg.textContent=err?.message||'No se pudo guardar el servicio.';msg.className='service-form-msg error';btn.disabled=false}});
  }
  async function deleteService(id,rows){const s=rows.find(x=>x.id===id);if(!s)return;if(!window.confirm(`¿Eliminar ${s.nombre}?`))return;const user=await getUser();const {error}=await supabaseClient.from('servicios').delete().eq('id',id).eq('user_id',user.id);if(error)window.alert(error.message);else loadServices();}
  const style=document.createElement('style');style.textContent='.services-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.service-kpi{border:1px solid #d9e6f1;background:#fff;border-radius:14px;padding:14px 16px;text-align:left;cursor:pointer;box-shadow:0 4px 15px #153a5c08}.service-kpi.active{border-color:#8cc7ff;box-shadow:0 0 0 2px #087cf51a}.service-kpi small{display:block;color:#6f87a1;font-size:10px;font-weight:700}.service-kpi strong{display:block;color:#12365e;font-size:24px;margin-top:4px}.service-filters{display:flex;gap:7px;flex-wrap:wrap;margin:-3px 0 14px}.service-filter{border:1px solid #d4e2ed;background:#fff;color:#55718e;border-radius:9px;padding:7px 11px;font-size:10px;font-weight:700;cursor:pointer}.service-filter.active{background:#eaf5ff;border-color:#9acbfa;color:#087cf5}.services-loading,.services-empty{padding:55px 20px;text-align:center;color:#7891ad;font-size:12px}.services-empty-icon{width:64px;height:64px;margin:0 auto 12px;border-radius:18px;background:#eaf5ff;color:#087cf5;display:grid;place-items:center;font-size:27px}.services-empty h3{margin:0 0 6px;color:#24496e;font-size:16px}.services-empty p{margin:0 auto 15px}.service-modal-backdrop{position:fixed;inset:0;background:#071d38aa;backdrop-filter:blur(6px);z-index:100;display:grid;place-items:center;padding:18px}.service-modal{width:min(650px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:24px}.service-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:14px}.service-modal-head h2{margin:0;color:#102b54;font-size:23px}.service-close{border:0;background:#eef5fb;color:#557493;border-radius:9px;width:34px;height:34px;font-size:22px}.voice-box{display:flex;gap:10px;align-items:center;background:#edf7ff;border:1px solid #d4eafa;border-radius:14px;padding:12px;margin-bottom:15px}.voice-box span{font-size:11px;color:#56728f}.service-form{display:grid;gap:13px}.service-form label{display:grid;gap:6px;color:#536b89;font-size:11px;font-weight:700}.service-form input,.service-form select,.service-form textarea{width:100%;border:1px solid #d2e0ec;border-radius:10px;background:#f8fbfe;color:#173452;padding:11px;font-size:12px}.service-form small{font-size:9px;font-weight:400;color:#8196aa}.service-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.service-check{display:flex!important;align-items:center;gap:9px!important}.service-check input{width:auto}.service-modal-actions{display:flex;justify-content:flex-end;gap:9px}.service-form-msg{min-height:17px;font-size:10px}.service-form-msg.error{color:#d13d4e}@media(max-width:700px){.services-kpis{grid-template-columns:1fr 1fr}}@media(max-width:600px){.service-grid{grid-template-columns:1fr}.service-modal{padding:19px}.voice-box{align-items:flex-start;flex-direction:column}}';document.head.appendChild(style);
})();