const schema={type:'object',properties:{cliente_id:{type:'string'},cliente_texto:{type:'string'},ubicacion:{type:'string'},duracion:{type:'string'},modalidad_costo:{type:'string'},precio_total_explicito:{type:'number'},currency:{type:'string'},cantidad_global:{type:'number'},descripcion_trabajo:{type:'string'},partidas:{type:'array',items:{type:'object',properties:{tipo:{type:'string'},nombre:{type:'string'},producto_id:{type:'string'},servicio_id:{type:'string'},cantidad:{type:'number'},unidad:{type:'string'},precio_unitario:{type:'number'},alcance_precio:{type:'string'},descripcion:{type:'string'}},required:['tipo','nombre','producto_id','servicio_id','cantidad','unidad','precio_unitario','alcance_precio','descripcion']}},confianza:{type:'number'},ambiguedades:{type:'array',items:{type:'string'}}},required:['cliente_id','cliente_texto','ubicacion','duracion','modalidad_costo','precio_total_explicito','currency','cantidad_global','descripcion_trabajo','partidas','confianza','ambiguedades']};
const pricingSchema={type:'object',properties:{precios:{type:'array',items:{type:'object',properties:{indice:{type:'integer'},precio_unitario:{type:'number'},alcance_precio:{type:'string'},cantidad:{type:'number'}},required:['indice','precio_unitario','alcance_precio','cantidad']}}},required:['precios']};
const clean=v=>{if(typeof v!=='string')return v;const s=v.trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{return JSON.parse(s)}catch{const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(s.slice(a,b+1))}catch{}}return null}};
const normalize=j=>{const x=j||{};return{cliente_id:x.cliente_id?String(x.cliente_id):null,cliente_texto:String(x.cliente_texto||''),ubicacion:String(x.ubicacion||''),duracion:String(x.duracion||''),modalidad_costo:String(x.modalidad_costo||'DESGLOSADO').toUpperCase(),precio_total_explicito:Number(x.precio_total_explicito||0)||null,currency:String(x.currency||'PEN'),cantidad_global:Number(x.cantidad_global||1),descripcion_trabajo:String(x.descripcion_trabajo||'').trim(),partidas:Array.isArray(x.partidas)?x.partidas.map(p=>({tipo:String(p.tipo||'SERVICIO').toUpperCase(),nombre:String(p.nombre||'').trim(),producto_id:p.producto_id?String(p.producto_id):null,servicio_id:p.servicio_id?String(p.servicio_id):null,cantidad:Number(p.cantidad||1),unidad:String(p.unidad||'UND'),precio_unitario:Number(p.precio_unitario||0),alcance_precio:String(p.alcance_precio||'global').toLowerCase(),descripcion:String(p.descripcion||'')})).filter(p=>p.nombre):[],confianza:Math.max(0,Math.min(1,Number(x.confianza||0))),ambiguedades:Array.isArray(x.ambiguedades)?x.ambiguedades.map(String):[]}};
const compact=(a,fields,max=160)=>(Array.isArray(a)?a:[]).slice(0,max).map(x=>{const o={};for(const k of fields)if(x?.[k]!==undefined&&x?.[k]!==null&&String(x[k]).trim()!=='')o[k]=x[k];return o});
const compactContext=ctx=>({clientes:compact(ctx?.clientes,['id','nombre','documento'],300),productos:compact(ctx?.productos,['id','codigo','nombre','marca','modelo','unidad','precio_venta'],160),servicios:compact(ctx?.servicios,['id','codigo','nombre','categoria','unidad','precio'],120)});
const promptFor=(text,ctx)=>`Eres el motor semántico de M.A.R.C., sistema empresarial de cotizaciones en Perú. Interpreta TODO el dictado y devuelve SOLO el objeto JSON solicitado.
REGLAS:
1. Extrae cliente, ubicación, duración, modalidad, descripcion_trabajo y TODAS las partidas con precio explícito.
2. descripcion_trabajo debe ser profesional y breve, usando SOLO hechos dichos por el usuario: qué se hará, dónde, qué se instalará y objetivo si fue indicado. No inventes marcas, modelos, cantidades, medidas, procedimientos ni estándares.
3. No confundas cliente con ubicación. "cliente X" es cliente; "ubicación/dirección X" es ubicación. Si hay varias referencias de dirección/ubicación, consérvalas combinadas sin meter el cliente en ubicación.
4. El catálogo solo sirve para encontrar IDs. NUNCA descartes una partida porque no exista en catálogo. Si no coincide, deja producto_id y servicio_id vacíos.
5. Nunca inventes IDs. Para cliente usa solo candidatos reales. Si no coincide, cliente_id vacío y conserva cliente_texto.
6. "instalación de dos cámaras" => cantidad 2 para cámaras y sus precios por cámara cuando así se indique.
7. "cada", "por cámara", "por unidad", "por equipo", "por pieza", "por metro", "por hora" => alcance_precio unitario.
8. "materiales 800" o "instalación 300" sin alcance por unidad => global; no multiplicar.
9. TODO COSTO solo si el usuario lo dice inequívocamente; en ese caso una sola partida global con el total explícito.
10. Conserva partidas detalladas aunque también exista un total explícito.
11. Formato peruano: 13.500=13500, 8 mil 200=8200, 150 soles=150.
12. Características como 4 megapíxeles, doble vivo, ColorVu, bullet deben conservarse en nombre/descripcion sin inventar modelo.
13. Todo precio dicho por el usuario tiene prioridad sobre catálogo.
14. Si el usuario dice "precio por cámara IP 150", crea cámara cantidad 2, precio 150, unitario. "materiales necesarios 800" => materiales cantidad 1, precio 800, global. "precio de instalación 140 por cámara" => instalación cantidad 2, precio 140, unitario.
15. precio_total_explicito=0 si no hay total final explícito. confianza entre 0 y 1.
DICTADO:
${String(text||'').slice(0,12000)}
CONTEXTO:
${JSON.stringify(compactContext(ctx))}`;
const pricingPrompt=(text,parts)=>`Verifica SOLO precios explícitos del dictado y asigna cada uno a su partida. No uses precios de catálogo.
DICTADO: ${String(text||'').slice(0,12000)}
PARTIDAS: ${JSON.stringify((parts||[]).map((p,i)=>({indice:i,nombre:p.nombre,cantidad:p.cantidad,precio_unitario:p.precio_unitario,alcance_precio:p.alcance_precio,descripcion:p.descripcion})))}
Reglas: "precio por cámara 150"=150 unitario; "materiales 800" sin "por cámara"=800 global; "instalación 140 por cámara"=140 unitario. Si no hay precio explícito, 0. Devuelve solo JSON.`;
async function callGemini(apiKey,model,prompt,responseSchema=null){const url='https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent';const generationConfig={responseMimeType:'application/json',maxOutputTokens:3500};if(responseSchema)generationConfig.responseSchema=responseSchema;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig})});let j={};try{j=await r.json()}catch{}const raw=(j?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>p?.text||'').join('').trim();const parsed=clean(raw);const reason=j?.promptFeedback?.blockReason||j?.candidates?.[0]?.finishReason||'';const detail=j?.error?.message||reason||(r.ok?(raw?'JSON no válido devuelto por Gemini':'Gemini devolvió 200 sin texto de candidato'):`HTTP ${r.status}`);return{ok:r.ok&&!!parsed,status:r.status,detail,parsed,raw};}
async function repairPricing(apiKey,model,text,quote){if(!quote.partidas.length||!quote.partidas.some(p=>Number(p.precio_unitario||0)<=0))return quote;const r=await callGemini(apiKey,model,pricingPrompt(text,quote.partidas),pricingSchema);if(!r.ok||!r.parsed?.precios)return quote;const map=new Map((r.parsed.precios||[]).map(x=>[Number(x.indice),x]));quote.partidas=quote.partidas.map((p,i)=>{const x=map.get(i);if(!x)return p;const price=Number(x.precio_unitario||0);return{...p,precio_unitario:price>0?price:p.precio_unitario,cantidad:Number(x.cantidad||p.cantidad||1),alcance_precio:String(x.alcance_precio||p.alcance_precio||'global').toLowerCase()}});return quote;}
export async function onRequestPost(context){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};try{const body=await context.request.json();const text=String(body?.text||'').trim();if(!text)return new Response(JSON.stringify({error:'Falta el texto del dictado'}),{status:400,headers});const apiKey=String(context.env?.GEMINI_API_KEY2||'').trim();if(!apiKey)return new Response(JSON.stringify({error:'GEMINI_API_KEY2 no está configurada en Cloudflare'}),{status:503,headers});const models=['gemini-3.6-flash','gemini-3.5-flash-lite'];let lastDetail='';for(const model of models){let r=await callGemini(apiKey,model,promptFor(text,body?.context||{}),schema);if(!r.ok){const plainPrompt=promptFor(text,body?.context||{})+'\n\nIMPORTANTE: devuelve un único objeto JSON válido, sin Markdown ni texto adicional.';const retry=await callGemini(apiKey,model,plainPrompt,null);if(retry.ok)r=retry;else lastDetail=`${r.detail}${retry.detail&&retry.detail!==r.detail?' | reintento: '+retry.detail:''}`;}if(r.ok&&r.parsed){const quote=await repairPricing(apiKey,model,text,normalize(r.parsed));return new Response(JSON.stringify({quote,modelo:model}),{status:200,headers});}if(!lastDetail)lastDetail=r.detail;if(r.status!==429&&r.status!==503&&model===models[models.length-1])break;}return new Response(JSON.stringify({error:`Gemini no pudo interpretar el dictado: ${lastDetail||'respuesta vacía'}`}),{status:502,headers});}catch(error){return new Response(JSON.stringify({error:String(error?.message||error)}),{status:503,headers});}}